<?php

namespace App\Console\Commands;

use App\Enums\ApplicationStorageEnums;
use App\Enums\QuoteTypeId;
use App\Models\CarQuote;
use App\Services\MACRMService;
use Illuminate\Console\Command;

class SyncCourierQuoteOnce extends Command
{
    protected $signature = 'sync:courier-quotes-once';
    protected $description = 'Sync courier quotes with MACRM for a list of RefIds, running only once on deployment.';
    protected $refIds = [
        '98TG4H75',
        '33MY7MY5',
        'LBHHZSRF',
        'HBCKW9UY',
        'RQKEHYX9',
        'BYTFGGFU',
        'Z8YDTECT',
        '7VSUBRHJ',
        '3BCCEGP8',
        '6975LMEC',
        'FUUWP8VS',
        'CYL5XTLS',
        'XEPREVCN',
        'LBUDL7CU',
        'CEW9YFAA',
        'QMW3U3GS',
        'ML57G6CG',
        '36QQ4YUS',
        'P6WKEQW6',
        'SKJERKWP',
        'QSXLQ5DQ',
        'XS4LSBM5',
        '7FJ65R4J',
        'R3KNSGJ7',
        '6DMYVDTG',
        '2BXX8VSP',
        'G2YCUJFP',
        'PLJTTCW3',
        'SAAPCC67',
        'VRN6MC9S',
        'LAJ8V2WU',
        'D2M5QDSZ',
        'GTJLNJSS',
        'H88U5C97',
        'Q4JYWVJW',
        'JSFT6FKS',
        'VAYRLK79',
        '9USRQ2NF',
        'N22L24Z4',
        'PD2E5EBQ',
        'YGJY4QMV',
        'NSL3E6BJ',
        '8P96TDB2',
        'KUMJHPPP',
        'HVA7AF4P',
        '49DB4P7N',
        'U9UD43YV',
        'CS2RLQ6E',
        'WUXEP6E7',
        'CAHHGDFM',
        'KATV7DDJ',
        'TR47AUL3',
        'VZCZBYE2',
        'E6GTZUYE',
        '2L9QMEGX',
        'WKK5XU7G',
        'TXBTD22J',
        'FK52MMBR',
        'KPDTSN5J',
        'WYKEGMSG',
        '5GMPD2RW',
        'NB2UCY98',
        'PKYRXTU6',
        'YK78RXX7',
        'A78UMBUF',
        'FUU26537',
        'YX4S8G5W',
        'E2JAMSYV',
        'DG6ZDCXG',
        'HJG4RU2C',
        'XTALPT92',
        '97NPRMWZ',
        'R9R6F5QM',
        'SQ4D8GUU',
        'K26BM2ZP',
        '9UWKTUP5',
        '64282ZY8',
        '5Y27YLH5',
        '36QGJL6H',
        '9UWR3NVB',
        'GFQCYUSD',
        'YJQ7A9P5',
        '7KTQPPVP',
        '46645PBF',
        '3F8CNAB9',
        'TQCHBM75',
        'UV3G62LC',
        'MWA3NLBW',
        'EEBDDGEF',
        'JGHKJTS2',
        '8Y2DUW5X',
        '3YXUKRZA',
        '28XY9MVC',
        'XL26E24J',
        '896ZBCQ8',
        '9FNAPX8T',
        '7J4PM4XY',
        'FDGHKAE2',
        'XGF84P5T',
        '5GQFZFRF',
        'LJUJE6HM',
        '27JYAAR7',
        'EU37ZG8D',
        'KTCNZTC8',
        'NXBCLRMS',
        'MABXZ94U',
        '7BNPGAQB',
        '8BLRYV35',
        'HR3W7P8D',
        '95PRDXP8',
        '6PBNL5M5',
        'QPL2MAXH',
        'YFMFT223',
        'HXHX3ALR',
        'XWRVPE6A',
        'JU7N8KPE',
        'KP4P6LT6',
        'BKF76TXY',
        '3KPHB553',
        'S3QZNGDG',
        'CFYRBRN2',
        '3VHYWW6W',
        'Y2YXNMJG',
        '2NBWN5YM',
        'EA2X7PRG',
        'CPUPSRNQ',
        'ETG2L4SX',
        '93NS2ZYC',
        'YGSLQLZ8',
        'JMQPTYK6',
        'YCJ8TXVR',
        'JZYMWHLM',
        'HR8DRDXF',
        'PU7D6NAA',
        'LVM6SH9Q',
        'UN96URJN',
        '8E6NGZJK',
        'NF7KPLVG',
        'FUJWFJDQ',
        '36HHZ7EG',
        'HTET6SWE',
        'AHMQ4RST',
        'UEF53K5V',
        'D8BPW4RW',
        'TH6BUYSZ',
        '3ANZNB2V',
        'Y5N9A5G5',
        '3FGEVUTS',
        'THAYVFJT',
        'P2ZSXYDG',
        'JEVDYP8B',
        'SYQGZQPV',
        'SWAFXD7Z',
        'TWFRQUF2',
        '2B5YGR5R',
        'QT35UAWR',
        '58DUAQ6X',
        'MYCRW2CV',
        'BCRJFT82',
        'N5XBM6HQ',
        'AJSVNFSM',
        '3299CPWR',
        '5LL24AEL',
        'WE7QLH6E',
        '7MWJKWZ4',
        'GGZDBCUE',
        'CEKWXQ9B',
        'KYUY63HW',
        'DHTJE2K7',
        '94NMDZEL',
        'UWJC5P28',
        '2JPYZUB8',
        'WFZJ75A7',
        '5TPEPEY5',
        'YTUS2SKZ',
        '4Q79F2GA',
        'BBZFT3PA',
        'ZKENRTMX',
        'JWFC9LAT',
        '2GZVWQB8',
        'JEXLNZVN',
        'K46EKAUH',
        'XNBHT88F',
        'ACH7BL73',
        'YLPLEG9F',
        '8JRTZU9G',
        '6BBB86GB',
        'Z26AZ9D4',
        'WAAX6SWX',
        'ZZPC9DZ8',
        'GDK5CNAM',
        'JUJU59Y6',
        '537T6EJQ',
        '5K9DJGU9',
        '9BMSKB97',
        'FY7ETS5C',
        'DWWY9KNW',
        '8WE8HF3S',
        'YK5TKGU4',
        '5FTDN5ER',
        'BEVFPUC2',
        'QGU9MZLZ',
        '74HSFTU5',
        '5HAQ6GB9',
        '9D7HURXZ',
        'BB9KZDDA',
        'EE8VUCW4',
        '4ETPMH3P',
        'WHUKPN9B',
        '9A8TPUWM',
        'NYTNU4RH',
        '8RRJUVWP',
        'PAHL7G77',
        '9JRJRDRV',
        'RMZCHW6A',
        'PL2D94YY',
        '8WAY62LW',
        'Q9DBFF3N',
        'S4Z4EPA5',
        'KBMEYUGF',
        'JJUMJ2XU',
        'QT6XCR74',
        'Y3ZSPXVF',
        '4SUUBYTE',
        'MU464KHF',
        'J23PWKJQ',
        'MBNT6UCK',
        'FARJ7CUF',
        'S4DG7KGJ',
        'CE9RQDQT',
        'CJWZ799X',
    ];

    public function handle()
    {
        if (getAppStorageValueByKey(ApplicationStorageEnums::COURIER_QUOTES_SYNC_ENABLED) !== '1') {
            $this->info('SyncCourierQuoteOnce - Courier quotes syncing is disabled.');

            return;
        }

        $this->info('SyncCourierQuoteOnce - Syncing process started at: '.now());
        foreach ($this->refIds as $refId) {
            $quote = CarQuote::where('uuid', $refId)->first();
            if (! $quote) {
                $this->info("SyncCourierQuoteOnce - Quote not found for RefId: {$refId}");

                continue;
            }
            $quoteTypeId = QuoteTypeId::Car;
            $result = MACRMService::syncCourierQuote($quote, $quoteTypeId);

            $result
                ? $this->info("SyncCourierQuoteOnce - Successfully synced quote for RefId: {$refId}")
                : $this->warn("SyncCourierQuoteOnce - Failed to sync quote for RefId: {$refId}");

            // Add a 1-second delay before moving to the next RefId
            sleep(1);
        }
    }
}
