<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AwnicNationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['id' => 1, 'code' => 'Afghan', 'awni_country_code_number' => '1001'],
            ['id' => 2, 'code' => 'Albanian', 'awni_country_code_number' => '1002'],
            ['id' => 3, 'code' => 'Algerian', 'awni_country_code_number' => '1003'],
            ['id' => 4, 'code' => 'American', 'awni_country_code_number' => '1004'],
            ['id' => 5, 'code' => 'Andorran', 'awni_country_code_number' => '1005'],
            ['id' => 6, 'code' => 'Angolan', 'awni_country_code_number' => '1006'],
            ['id' => 8, 'code' => 'Argentinean', 'awni_country_code_number' => '1008'],
            ['id' => 9, 'code' => 'Armenian', 'awni_country_code_number' => '1009'],
            ['id' => 10, 'code' => 'Australian', 'awni_country_code_number' => '1010'],
            ['id' => 11, 'code' => 'Austrian', 'awni_country_code_number' => '1011'],
            ['id' => 12, 'code' => 'Azerbaijani', 'awni_country_code_number' => '1012'],
            ['id' => 13, 'code' => 'Bahamian', 'awni_country_code_number' => '1013'],
            ['id' => 14, 'code' => 'Bahraini', 'awni_country_code_number' => '1014'],
            ['id' => 15, 'code' => 'Bangladeshi', 'awni_country_code_number' => '1015'],
            ['id' => 16, 'code' => 'Barbadian', 'awni_country_code_number' => '1016'],
            ['id' => 19, 'code' => 'Belarusian', 'awni_country_code_number' => '1019'],
            ['id' => 20, 'code' => 'Belgian', 'awni_country_code_number' => '1020'],
            ['id' => 21, 'code' => 'Belizean', 'awni_country_code_number' => '1021'],
            ['id' => 22, 'code' => 'Beninese', 'awni_country_code_number' => '1022'],
            ['id' => 23, 'code' => 'Bhutanese', 'awni_country_code_number' => '1023'],
            ['id' => 24, 'code' => 'Bolivian', 'awni_country_code_number' => '1024'],
            ['id' => 25, 'code' => 'Bosnian', 'awni_country_code_number' => '1025'],
            ['id' => 26, 'code' => 'Brazilian', 'awni_country_code_number' => '1026'],
            ['id' => 27, 'code' => 'British', 'awni_country_code_number' => '1027'],
            ['id' => 28, 'code' => 'Bruneian', 'awni_country_code_number' => '1028'],
            ['id' => 29, 'code' => 'Bulgarian', 'awni_country_code_number' => '1029'],
            ['id' => 30, 'code' => 'Burkinabe', 'awni_country_code_number' => '1030'],
            ['id' => 31, 'code' => 'Burmese', 'awni_country_code_number' => '2005'],
            ['id' => 32, 'code' => 'Burundian', 'awni_country_code_number' => '1032'],
            ['id' => 33, 'code' => 'Cambodian', 'awni_country_code_number' => '1033'],
            ['id' => 34, 'code' => 'Cameroonian', 'awni_country_code_number' => '1034'],
            ['id' => 35, 'code' => 'Canadian', 'awni_country_code_number' => '1035'],
            ['id' => 36, 'code' => 'Cape Verdean', 'awni_country_code_number' => '1036'],
            ['id' => 37, 'code' => 'Central African', 'awni_country_code_number' => '1037'],
            ['id' => 38, 'code' => 'Chadian', 'awni_country_code_number' => '1038'],
            ['id' => 39, 'code' => 'Chilean', 'awni_country_code_number' => '1039'],
            ['id' => 40, 'code' => 'Chinese', 'awni_country_code_number' => '1040'],
            ['id' => 41, 'code' => 'Colombian', 'awni_country_code_number' => '1041'],
            ['id' => 42, 'code' => 'Comoran', 'awni_country_code_number' => '1042'],
            ['id' => 43, 'code' => 'Congolese', 'awni_country_code_number' => '1043'],
            ['id' => 44, 'code' => 'Costa Rican', 'awni_country_code_number' => '1045'],
            ['id' => 45, 'code' => 'Croatian', 'awni_country_code_number' => '1046'],
            ['id' => 46, 'code' => 'Cuban', 'awni_country_code_number' => '1047'],
            ['id' => 47, 'code' => 'Cypriot', 'awni_country_code_number' => '1048'],
            ['id' => 48, 'code' => 'Czech', 'awni_country_code_number' => '1049'],
            ['id' => 49, 'code' => 'Danish', 'awni_country_code_number' => '1050'],
            ['id' => 50, 'code' => 'Djiboutian', 'awni_country_code_number' => '1051'],
            ['id' => 51, 'code' => 'Dominican', 'awni_country_code_number' => '1052'],
            ['id' => 52, 'code' => 'Dutch', 'awni_country_code_number' => '1054'],
            ['id' => 53, 'code' => 'East Timorese', 'awni_country_code_number' => '1057'],
            ['id' => 54, 'code' => 'Ecuadorean', 'awni_country_code_number' => '1058'],
            ['id' => 55, 'code' => 'Egyptian', 'awni_country_code_number' => '1059'],
            ['id' => 56, 'code' => 'Emirati', 'awni_country_code_number' => '1060'],
            ['id' => 57, 'code' => 'Equatorial Guinean', 'awni_country_code_number' => '1061'],
            ['id' => 58, 'code' => 'Eritrean', 'awni_country_code_number' => '1062'],
            ['id' => 59, 'code' => 'Estonian', 'awni_country_code_number' => '1063'],
            ['id' => 60, 'code' => 'Ethiopian', 'awni_country_code_number' => '1064'],
            ['id' => 61, 'code' => 'Fijian', 'awni_country_code_number' => '1065'],
            ['id' => 62, 'code' => 'Filipino', 'awni_country_code_number' => '2001'],
            ['id' => 63, 'code' => 'Finnish', 'awni_country_code_number' => '1067'],
            ['id' => 64, 'code' => 'French', 'awni_country_code_number' => '1068'],
            ['id' => 65, 'code' => 'Gabonese', 'awni_country_code_number' => '1069'],
            ['id' => 66, 'code' => 'Gambian', 'awni_country_code_number' => '1070'],
            ['id' => 67, 'code' => 'Georgian', 'awni_country_code_number' => '1071'],
            ['id' => 68, 'code' => 'German', 'awni_country_code_number' => '1072'],
            ['id' => 69, 'code' => 'Ghanaian', 'awni_country_code_number' => '1073'],
            ['id' => 70, 'code' => 'Greek', 'awni_country_code_number' => '1074'],
            ['id' => 71, 'code' => 'Grenadian', 'awni_country_code_number' => '1075'],
            ['id' => 72, 'code' => 'Guatemalan', 'awni_country_code_number' => '1076'],
            ['id' => 73, 'code' => 'Guinea-Bissauan', 'awni_country_code_number' => '1077'],
            ['id' => 74, 'code' => 'Guinean', 'awni_country_code_number' => '1078'],
            ['id' => 75, 'code' => 'Guyanese', 'awni_country_code_number' => '1079'],
            ['id' => 76, 'code' => 'Haitian', 'awni_country_code_number' => '1080'],
            ['id' => 77, 'code' => 'Herzegovinian', 'awni_country_code_number' => '1025'],
            ['id' => 78, 'code' => 'Honduran', 'awni_country_code_number' => '1082'],
            ['id' => 79, 'code' => 'Hungarian', 'awni_country_code_number' => '1083'],
            ['id' => 80, 'code' => 'I-Kiribati', 'awni_country_code_number' => '1084'],
            ['id' => 81, 'code' => 'Icelandic', 'awni_country_code_number' => '1085'],
            ['id' => 82, 'code' => 'Indian', 'awni_country_code_number' => '1086'],
            ['id' => 83, 'code' => 'Indonesian', 'awni_country_code_number' => '1087'],
            ['id' => 84, 'code' => 'Iranian', 'awni_country_code_number' => '1088'],
            ['id' => 85, 'code' => 'Iraqi', 'awni_country_code_number' => '1089'],
            ['id' => 86, 'code' => 'Irish', 'awni_country_code_number' => '1090'],
            ['id' => 87, 'code' => 'Israeli', 'awni_country_code_number' => '2008'],
            ['id' => 88, 'code' => 'Italian', 'awni_country_code_number' => '1092'],
            ['id' => 89, 'code' => 'Ivorian', 'awni_country_code_number' => '1093'],
            ['id' => 90, 'code' => 'Jamaican', 'awni_country_code_number' => '1094'],
            ['id' => 91, 'code' => 'Japanese', 'awni_country_code_number' => '1095'],
            ['id' => 92, 'code' => 'Jordanian', 'awni_country_code_number' => '1096'],
            ['id' => 93, 'code' => 'Kazakhstani', 'awni_country_code_number' => '1097'],
            ['id' => 94, 'code' => 'Kenyan', 'awni_country_code_number' => '1098'],
            ['id' => 95, 'code' => 'Kittian and Nevisian', 'awni_country_code_number' => '1099'],
            ['id' => 96, 'code' => 'Kuwaiti', 'awni_country_code_number' => '1100'],
            ['id' => 97, 'code' => 'Kyrgyz', 'awni_country_code_number' => '1101'],
            ['id' => 98, 'code' => 'Laotian', 'awni_country_code_number' => '1102'],
            ['id' => 99, 'code' => 'Latvian', 'awni_country_code_number' => '1103'],
            ['id' => 100, 'code' => 'Lebanese', 'awni_country_code_number' => '1104'],
            ['id' => 101, 'code' => 'Liberian', 'awni_country_code_number' => '1105'],
            ['id' => 102, 'code' => 'Libyan', 'awni_country_code_number' => '1106'],
            ['id' => 103, 'code' => 'Liechtensteiner', 'awni_country_code_number' => '1107'],
            ['id' => 104, 'code' => 'Lithuanian', 'awni_country_code_number' => '1108'],
            ['id' => 105, 'code' => 'Luxembourger', 'awni_country_code_number' => '1109'],
            ['id' => 106, 'code' => 'Macedonian', 'awni_country_code_number' => '1110'],
            ['id' => 107, 'code' => 'Malagasy', 'awni_country_code_number' => '1111'],
            ['id' => 108, 'code' => 'Malawian', 'awni_country_code_number' => '1112'],
            ['id' => 109, 'code' => 'Malaysian', 'awni_country_code_number' => '1113'],
            ['id' => 110, 'code' => 'Maldivan', 'awni_country_code_number' => '1114'],
            ['id' => 111, 'code' => 'Malian', 'awni_country_code_number' => '1115'],
            ['id' => 112, 'code' => 'Maltese', 'awni_country_code_number' => '1116'],
            ['id' => 113, 'code' => 'Marshallese', 'awni_country_code_number' => '1117'],
            ['id' => 114, 'code' => 'Mauritanian', 'awni_country_code_number' => '1118'],
            ['id' => 115, 'code' => 'Mauritian', 'awni_country_code_number' => '1119'],
            ['id' => 116, 'code' => 'Mexican', 'awni_country_code_number' => '1120'],
            ['id' => 117, 'code' => 'Micronesian', 'awni_country_code_number' => '1121'],
            ['id' => 118, 'code' => 'Moldovan', 'awni_country_code_number' => '1122'],
            ['id' => 119, 'code' => 'Monacan', 'awni_country_code_number' => '1123'],
            ['id' => 120, 'code' => 'Mongolian', 'awni_country_code_number' => '1124'],
            ['id' => 121, 'code' => 'Moroccan', 'awni_country_code_number' => '1125'],
            ['id' => 122, 'code' => 'Mosotho', 'awni_country_code_number' => '1126'],
            ['id' => 124, 'code' => 'Mozambican', 'awni_country_code_number' => '1128'],
            ['id' => 125, 'code' => 'Namibian', 'awni_country_code_number' => '1129'],
            ['id' => 126, 'code' => 'Nauruan', 'awni_country_code_number' => '1130'],
            ['id' => 127, 'code' => 'Nepalese', 'awni_country_code_number' => '1131'],
            ['id' => 128, 'code' => 'New Zealander', 'awni_country_code_number' => '1133'],
            ['id' => 129, 'code' => 'Ni-vanuatu', 'awni_country_code_number' => '1134'],
            ['id' => 130, 'code' => 'Nicaraguan', 'awni_country_code_number' => '1135'],
            ['id' => 131, 'code' => 'Nigerien', 'awni_country_code_number' => '1136'],
            ['id' => 132, 'code' => 'North Korean', 'awni_country_code_number' => '1138'],
            ['id' => 133, 'code' => 'Northern Irish', 'awni_country_code_number' => '1139'],
            ['id' => 134, 'code' => 'Norwegian', 'awni_country_code_number' => '1140'],
            ['id' => 135, 'code' => 'Omani', 'awni_country_code_number' => '1141'],
            ['id' => 136, 'code' => 'Pakistani', 'awni_country_code_number' => '1142'],
            ['id' => 137, 'code' => 'Palestinian', 'awni_country_code_number' => '1201'],
            ['id' => 138, 'code' => 'Palauan', 'awni_country_code_number' => '1143'],
            ['id' => 139, 'code' => 'Panamanian', 'awni_country_code_number' => '1144'],
            ['id' => 140, 'code' => 'Papua New Guinean', 'awni_country_code_number' => '1145'],
            ['id' => 141, 'code' => 'Paraguayan', 'awni_country_code_number' => '1146'],
            ['id' => 142, 'code' => 'Peruvian', 'awni_country_code_number' => '1147'],
            ['id' => 143, 'code' => 'Polish', 'awni_country_code_number' => '1148'],
            ['id' => 145, 'code' => 'Qatari', 'awni_country_code_number' => '1150'],
            ['id' => 146, 'code' => 'Romanian', 'awni_country_code_number' => '1151'],
            ['id' => 147, 'code' => 'Russian', 'awni_country_code_number' => '1152'],
            ['id' => 148, 'code' => 'Rwandan', 'awni_country_code_number' => '1153'],
            ['id' => 149, 'code' => 'Saint Lucian', 'awni_country_code_number' => '1154'],
            ['id' => 150, 'code' => 'Salvadoran', 'awni_country_code_number' => '1155'],
            ['id' => 151, 'code' => 'Samoan', 'awni_country_code_number' => '1156'],
            ['id' => 152, 'code' => 'Sammarinese', 'awni_country_code_number' => '1157'],
            ['id' => 153, 'code' => 'Sao Tomean', 'awni_country_code_number' => '1158'],
            ['id' => 154, 'code' => 'Saudi', 'awni_country_code_number' => '1159'],
            ['id' => 155, 'code' => 'Scottish', 'awni_country_code_number' => '1160'],
            ['id' => 156, 'code' => 'Senegalese', 'awni_country_code_number' => '1161'],
            ['id' => 157, 'code' => 'Serbian', 'awni_country_code_number' => '1162'],
            ['id' => 158, 'code' => 'Seychellois', 'awni_country_code_number' => '1163'],
            ['id' => 159, 'code' => 'Sierra Leonean', 'awni_country_code_number' => '1164'],
            ['id' => 160, 'code' => 'Singaporean', 'awni_country_code_number' => '1165'],
            ['id' => 161, 'code' => 'Slovakian', 'awni_country_code_number' => '1166'],
            ['id' => 162, 'code' => 'Slovenian', 'awni_country_code_number' => '1167'],
            ['id' => 163, 'code' => 'Solomon Islander', 'awni_country_code_number' => '1168'],
            ['id' => 164, 'code' => 'Somali', 'awni_country_code_number' => '1169'],
            ['id' => 165, 'code' => 'South African', 'awni_country_code_number' => '1170'],
            ['id' => 166, 'code' => 'South Korean', 'awni_country_code_number' => '1171'],
            ['id' => 167, 'code' => 'Spanish', 'awni_country_code_number' => '1172'],
            ['id' => 168, 'code' => 'Sri Lankan', 'awni_country_code_number' => '1173'],
            ['id' => 169, 'code' => 'Sudanese', 'awni_country_code_number' => '1174'],
            ['id' => 170, 'code' => 'Surinamese', 'awni_country_code_number' => '1175'],
            ['id' => 171, 'code' => 'Swazi', 'awni_country_code_number' => '1176'],
            ['id' => 172, 'code' => 'Swedish', 'awni_country_code_number' => '1177'],
            ['id' => 173, 'code' => 'Swiss', 'awni_country_code_number' => '1178'],
            ['id' => 174, 'code' => 'Syrian', 'awni_country_code_number' => '1179'],
            ['id' => 175, 'code' => 'Taiwanese', 'awni_country_code_number' => '1180'],
            ['id' => 176, 'code' => 'Tajik', 'awni_country_code_number' => '1181'],
            ['id' => 177, 'code' => 'Tanzanian', 'awni_country_code_number' => '1182'],
            ['id' => 178, 'code' => 'Thai', 'awni_country_code_number' => '1183'],
            ['id' => 179, 'code' => 'Togolese', 'awni_country_code_number' => '1184'],
            ['id' => 180, 'code' => 'TONGAN', 'awni_country_code_number' => '1185'],
            ['id' => 181, 'code' => 'Trinidadian or Tobagonian', 'awni_country_code_number' => '1186'],
            ['id' => 182, 'code' => 'Tunisian', 'awni_country_code_number' => '1187'],
            ['id' => 183, 'code' => 'Turkish', 'awni_country_code_number' => '1188'],
            ['id' => 184, 'code' => 'Tuvaluan', 'awni_country_code_number' => '1189'],
            ['id' => 185, 'code' => 'Ugandan', 'awni_country_code_number' => '1190'],
            ['id' => 186, 'code' => 'Ukrainian', 'awni_country_code_number' => '1191'],
            ['id' => 187, 'code' => 'Uruguayan', 'awni_country_code_number' => '1192'],
            ['id' => 189, 'code' => 'Venezuelan', 'awni_country_code_number' => '1194'],
            ['id' => 190, 'code' => 'Vietnamese', 'awni_country_code_number' => '1195'],
            ['id' => 191, 'code' => 'Welsh', 'awni_country_code_number' => '1196'],
            ['id' => 192, 'code' => 'Yemenite', 'awni_country_code_number' => '1198'],
            ['id' => 193, 'code' => 'Zambian', 'awni_country_code_number' => '1199'],
            ['id' => 194, 'code' => 'Zimbabwean', 'awni_country_code_number' => '1200'],
            ['id' => 214, 'code' => 'Puerto Rico', 'awni_country_code_number' => '2010'],
            ['id' => 227, 'code' => 'Bermudian', 'awni_country_code_number' => '2004'],
            ['id' => 228, 'code' => 'Botswanan', 'awni_country_code_number' => '1018'],
            ['id' => 218, 'code' => 'Nigerian', 'awni_country_code_number' => '1136'],
            ['id' => 251, 'code' => 'Congolese (Congo)', 'awni_country_code_number' => '1043'],
            ['id' => 252, 'code' => 'Congolese (DRC)', 'awni_country_code_number' => '1043'],
            ['id' => 258, 'code' => 'Portuguese', 'awni_country_code_number' => '1149'],
            ['id' => 260, 'code' => 'Antiguan and Barbudan', 'awni_country_code_number' => '2002'],
            ['id' => 289, 'code' => 'Saudi', 'awni_country_code_number' => '1159'],
            ['id' => 299, 'code' => 'Uzbek', 'awni_country_code_number' => '1193'],
        ];

        foreach ($nationalities as $entry) {
            if (empty($entry['id']) || empty($entry['awni_country_code_number'])) {
                continue;
            }

            DB::table('nationality')
                ->where('id', $entry['id'])
                ->update(['awni_country_code_number' => $entry['awni_country_code_number']]);
        }
    }
}
