<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AwnicNationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['code' => 'Afghan', 'awni_country_code_number' => 1001],
            ['code' => 'Albanian', 'awni_country_code_number' => 1002],
            ['code' => 'Algerian', 'awni_country_code_number' => 1003],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'Andorran', 'awni_country_code_number' => 1005],
            ['code' => 'Angolan', 'awni_country_code_number' => 1006],
            ['code' => 'Antiguans', 'awni_country_code_number' => 2002],
            ['code' => 'Argentinean', 'awni_country_code_number' => 1008],
            ['code' => 'Armenian', 'awni_country_code_number' => 1009],
            ['code' => 'Australian', 'awni_country_code_number' => 1010],
            ['code' => 'Austrian', 'awni_country_code_number' => 1011],
            ['code' => 'Azerbaijani', 'awni_country_code_number' => 1012],
            ['code' => 'Bahamian', 'awni_country_code_number' => 1013],
            ['code' => 'Bahraini', 'awni_country_code_number' => 1014],
            ['code' => 'Bangladeshi', 'awni_country_code_number' => 1015],
            ['code' => 'Barbadian', 'awni_country_code_number' => 1016],
            ['code' => 'Batswana', 'awni_country_code_number' => 1018],
            ['code' => 'Belarusian', 'awni_country_code_number' => 1019],
            ['code' => 'Belgian', 'awni_country_code_number' => 1020],
            ['code' => 'Belizean', 'awni_country_code_number' => 1021],
            ['code' => 'Beninese', 'awni_country_code_number' => 1022],
            ['code' => 'Bermuda', 'awni_country_code_number' => 2004],
            ['code' => 'Bhutanese', 'awni_country_code_number' => 1023],
            ['code' => 'Bolivian', 'awni_country_code_number' => 1024],
            ['code' => 'Bosnian', 'awni_country_code_number' => 1025],
            ['code' => 'Brazilian', 'awni_country_code_number' => 1026],
            ['code' => 'British', 'awni_country_code_number' => 1027],
            ['code' => 'Bruneian', 'awni_country_code_number' => 1028],
            ['code' => 'Bulgarian', 'awni_country_code_number' => 1029],
            ['code' => 'Burkinabe', 'awni_country_code_number' => 1030],
            ['code' => 'Burkinan', 'awni_country_code_number' => 1030],
            ['code' => 'Burmese', 'awni_country_code_number' => 2005],
            ['code' => 'Cambodian', 'awni_country_code_number' => 1033],
            ['code' => 'Cameroonian', 'awni_country_code_number' => 1034],
            ['code' => 'Canadian', 'awni_country_code_number' => 1035],
            ['code' => 'Cape Verdean', 'awni_country_code_number' => 1036],
            ['code' => 'Central African', 'awni_country_code_number' => 1037],
            ['code' => 'Chadian', 'awni_country_code_number' => 1038],
            ['code' => 'Chilean', 'awni_country_code_number' => 1039],
            ['code' => 'Chinese', 'awni_country_code_number' => 1040],
            ['code' => 'Colombian', 'awni_country_code_number' => 1041],
            ['code' => 'Comoran', 'awni_country_code_number' => 1042],
            ['code' => 'Congolese', 'awni_country_code_number' => 1043],
            ['code' => 'Congolese (DRC)', 'awni_country_code_number' => 1043],
            ['code' => 'Costa Rican', 'awni_country_code_number' => 1045],
            ['code' => 'Croatian', 'awni_country_code_number' => 1046],
            ['code' => 'Cuban', 'awni_country_code_number' => 1047],
            ['code' => 'Cypriot', 'awni_country_code_number' => 1048],
            ['code' => 'Czech', 'awni_country_code_number' => 1049],
            ['code' => 'Danish', 'awni_country_code_number' => 1050],
            ['code' => 'Dominica', 'awni_country_code_number' => 1052],
            ['code' => 'Dominican', 'awni_country_code_number' => 1052],
            ['code' => 'Dutch', 'awni_country_code_number' => 1054],
            ['code' => 'East Timorese', 'awni_country_code_number' => 1057],
            ['code' => 'Ecuadorean', 'awni_country_code_number' => 1058],
            ['code' => 'Egyptian', 'awni_country_code_number' => 1059],
            ['code' => 'Emirati', 'awni_country_code_number' => 1060],
            ['code' => 'Equatorial Guinean', 'awni_country_code_number' => 1061],
            ['code' => 'Eritrean', 'awni_country_code_number' => 1062],
            ['code' => 'Estonian', 'awni_country_code_number' => 1063],
            ['code' => 'Ethiopian', 'awni_country_code_number' => 1064],
            ['code' => 'Fijian', 'awni_country_code_number' => 1065],
            ['code' => 'Filipino', 'awni_country_code_number' => 2001],
            ['code' => 'Finnish', 'awni_country_code_number' => 1067],
            ['code' => 'French', 'awni_country_code_number' => 1068],
            ['code' => 'Gabonese', 'awni_country_code_number' => 1069],
            ['code' => 'Gambian', 'awni_country_code_number' => 1070],
            ['code' => 'Georgian', 'awni_country_code_number' => 1071],
            ['code' => 'German', 'awni_country_code_number' => 1072],
            ['code' => 'Ghanaian', 'awni_country_code_number' => 1073],
            ['code' => 'Greek', 'awni_country_code_number' => 1074],
            ['code' => 'Grenadian', 'awni_country_code_number' => 1075],
            ['code' => 'Guatemalan', 'awni_country_code_number' => 1076],
            ['code' => 'Guinea-Bissauan', 'awni_country_code_number' => 1077],
            ['code' => 'Guinean', 'awni_country_code_number' => 1078],
            ['code' => 'Guyanese', 'awni_country_code_number' => 1079],
            ['code' => 'Haitian', 'awni_country_code_number' => 1080],
            ['code' => 'Honduran', 'awni_country_code_number' => 1082],
            ['code' => 'Hungarian', 'awni_country_code_number' => 1083],
            ['code' => 'Indian', 'awni_country_code_number' => 1086],
            ['code' => 'Indonesian', 'awni_country_code_number' => 1087],
            ['code' => 'Iranian', 'awni_country_code_number' => 1088],
            ['code' => 'Iraqi', 'awni_country_code_number' => 1089],
            ['code' => 'Irish', 'awni_country_code_number' => 1090],
            ['code' => 'Israeli', 'awni_country_code_number' => 2008],
            ['code' => 'Italian', 'awni_country_code_number' => 1092],
            ['code' => 'Kazakhstani', 'awni_country_code_number' => 1097],
            ['code' => 'Kenyan', 'awni_country_code_number' => 1098],
            ['code' => 'I-Kiribati', 'awni_country_code_number' => 1084],
            ['code' => 'Kittian and Nevisian', 'awni_country_code_number' => 1099],
            ['code' => 'Kuwaiti', 'awni_country_code_number' => 1100],
            ['code' => 'Kyrgyz', 'awni_country_code_number' => 1101],
            ['code' => 'Laotian', 'awni_country_code_number' => 1102],
            ['code' => 'Latvian', 'awni_country_code_number' => 1103],
            ['code' => 'Lebanese', 'awni_country_code_number' => 1104],
            ['code' => 'Liberian', 'awni_country_code_number' => 1105],
            ['code' => 'Libyan', 'awni_country_code_number' => 1106],
            ['code' => 'Liechtensteiner', 'awni_country_code_number' => 1107],
            ['code' => 'Lithuanian', 'awni_country_code_number' => 1108],
            ['code' => 'Luxembourger', 'awni_country_code_number' => 1109],
            ['code' => 'Macedonian', 'awni_country_code_number' => 1110],
            ['code' => 'Madeira', 'awni_country_code_number' => 1149],
            ['code' => 'Malagasy', 'awni_country_code_number' => 1111],
            ['code' => 'Malawian', 'awni_country_code_number' => 1112],
            ['code' => 'Malaysian', 'awni_country_code_number' => 1113],
            ['code' => 'Maldivan', 'awni_country_code_number' => 1114],
            ['code' => 'Malian', 'awni_country_code_number' => 1115],
            ['code' => 'Maltese', 'awni_country_code_number' => 1116],
            ['code' => 'Marshallese', 'awni_country_code_number' => 1117],
            ['code' => 'Mauritanian', 'awni_country_code_number' => 1118],
            ['code' => 'Mauritian', 'awni_country_code_number' => 1119],
            ['code' => 'Mexican', 'awni_country_code_number' => 1120],
            ['code' => 'Micronesian', 'awni_country_code_number' => 1121],
            ['code' => 'Moldovan', 'awni_country_code_number' => 1122],
            ['code' => 'Monacan', 'awni_country_code_number' => 1123],
            ['code' => 'Mongolian', 'awni_country_code_number' => 1124],
            ['code' => 'Moroccan', 'awni_country_code_number' => 1125],
            ['code' => 'Mosotho', 'awni_country_code_number' => 1126],
            ['code' => 'Namibian', 'awni_country_code_number' => 1129],
            ['code' => 'Nauruan', 'awni_country_code_number' => 1130],
            ['code' => 'Nepalese', 'awni_country_code_number' => 1131],
            ['code' => 'New Zealander', 'awni_country_code_number' => 1133],
            ['code' => 'Ni-vanuatu', 'awni_country_code_number' => 1134],
            ['code' => 'Nicaraguan', 'awni_country_code_number' => 1135],
            ['code' => 'Nigerian', 'awni_country_code_number' => 1136],
            ['code' => 'Nigerien', 'awni_country_code_number' => 1137],
            ['code' => 'Niuean', 'awni_country_code_number' => 1134],
            ['code' => 'Norwegian', 'awni_country_code_number' => 1140],
            ['code' => 'Omani', 'awni_country_code_number' => 1141],
            ['code' => 'Pakistani', 'awni_country_code_number' => 1142],
            ['code' => 'Palauan', 'awni_country_code_number' => 1143],
            ['code' => 'Palestinian', 'awni_country_code_number' => 1201],
            ['code' => 'Panamanian', 'awni_country_code_number' => 1144],
            ['code' => 'Papua New Guinean', 'awni_country_code_number' => 1145],
            ['code' => 'Paraguayan', 'awni_country_code_number' => 1146],
            ['code' => 'Peruvian', 'awni_country_code_number' => 1147],
            ['code' => 'Polish', 'awni_country_code_number' => 1148],
            ['code' => 'Puerto Rico', 'awni_country_code_number' => 2010],
            ['code' => 'Qatari', 'awni_country_code_number' => 1150],
            ['code' => 'Romanian', 'awni_country_code_number' => 1151],
            ['code' => 'Russian', 'awni_country_code_number' => 1152],
            ['code' => 'Rwandan', 'awni_country_code_number' => 1153],
            ['code' => 'Saint Kitts and Nevis', 'awni_country_code_number' => 1099],
            ['code' => 'Saint Lucian', 'awni_country_code_number' => 1154],
            ['code' => 'Salvadoran', 'awni_country_code_number' => 1155],
            ['code' => 'Sao Tome and Principe', 'awni_country_code_number' => 1158],
            ['code' => 'Sao Tomean', 'awni_country_code_number' => 1158],
            ['code' => 'Saudi', 'awni_country_code_number' => 1159],
            ['code' => 'Senegalese', 'awni_country_code_number' => 1161],
            ['code' => 'Serbian', 'awni_country_code_number' => 1162],
            ['code' => 'Seychellois', 'awni_country_code_number' => 1163],
            ['code' => 'Sierra Leonean', 'awni_country_code_number' => 1164],
            ['code' => 'Singaporean', 'awni_country_code_number' => 1165],
            ['code' => 'Slovakian', 'awni_country_code_number' => 1166],
            ['code' => 'Slovenian', 'awni_country_code_number' => 1167],
            ['code' => 'Solomon Islander', 'awni_country_code_number' => 1168],
            ['code' => 'Solomon Islands', 'awni_country_code_number' => 1168],
            ['code' => 'Somali', 'awni_country_code_number' => 1169],
            ['code' => 'South African', 'awni_country_code_number' => 1170],
            ['code' => 'South Korea', 'awni_country_code_number' => 1171],
            ['code' => 'South Korean', 'awni_country_code_number' => 1171],
            ['code' => 'Spanish', 'awni_country_code_number' => 1172],
            ['code' => 'Sri Lankan', 'awni_country_code_number' => 1173],
            ['code' => 'Sudanese', 'awni_country_code_number' => 1174],
            ['code' => 'Swazi', 'awni_country_code_number' => 1176],
            ['code' => 'Swedish', 'awni_country_code_number' => 1177],
            ['code' => 'Swiss', 'awni_country_code_number' => 1178],
            ['code' => 'Syrian', 'awni_country_code_number' => 1179],
            ['code' => 'Taiwanese', 'awni_country_code_number' => 1180],
            ['code' => 'Tajik', 'awni_country_code_number' => 1181],
            ['code' => 'Tanzanian', 'awni_country_code_number' => 1182],
            ['code' => 'Thai', 'awni_country_code_number' => 1183],
            ['code' => 'Togolese', 'awni_country_code_number' => 1184],
            ['code' => 'Trinidadian or Tobagonian', 'awni_country_code_number' => 1186],
            ['code' => 'Tunisian', 'awni_country_code_number' => 1187],
            ['code' => 'Turkish', 'awni_country_code_number' => 1188],
            ['code' => 'Tuvaluan', 'awni_country_code_number' => 1189],
            ['code' => 'Ugandan', 'awni_country_code_number' => 1190],
            ['code' => 'Ukrainian', 'awni_country_code_number' => 1191],
            ['code' => 'United Kingdom', 'awni_country_code_number' => 1027],
            ['code' => 'Uruguayan', 'awni_country_code_number' => 1192],
            ['code' => 'Uzbekistani', 'awni_country_code_number' => 1193],
            ['code' => 'Venezuelan', 'awni_country_code_number' => 1194],
            ['code' => 'Vietnamese', 'awni_country_code_number' => 1195],
            ['code' => 'Yemenite', 'awni_country_code_number' => 1198],
            ['code' => 'Zambian', 'awni_country_code_number' => 1199],
            ['code' => 'Zimbabwean', 'awni_country_code_number' => 1200],
            ['code' => 'Antiguan and Barbudan', 'awni_country_code_number' => 2002],
            ['code' => 'Bermudian', 'awni_country_code_number' => 2004],
            ['code' => 'Botswanan', 'awni_country_code_number' => 1018],
            ['code' => 'Congolese (Congo)', 'awni_country_code_number' => 1043],
            ['code' => 'Djiboutian', 'awni_country_code_number' => 1051],
            ['code' => 'Herzegovinian', 'awni_country_code_number' => 1025],
            ['code' => 'Icelandic', 'awni_country_code_number' => 1085],
            ['code' => 'Mozambican', 'awni_country_code_number' => 1126],
            ['code' => 'Portuguese', 'awni_country_code_number' => 1149],
            ['code' => 'Surinamese', 'awni_country_code_number' => 1175],
            ['code' => 'TONGAN', 'awni_country_code_number' => 1185],
            ['code' => 'Uzbek', 'awni_country_code_number' => 1193],
            ['code' => 'Ivorian', 'awni_country_code_number' => null],
            ['code' => 'Jamaican', 'awni_country_code_number' => null],
            ['code' => 'Japanese', 'awni_country_code_number' => null],
            ['code' => 'Jordanian', 'awni_country_code_number' => null],
            ['code' => 'North Korean', 'awni_country_code_number' => null],
            ['code' => 'Northern Irish', 'awni_country_code_number' => null],
            ['code' => 'Sammarinese', 'awni_country_code_number' => null],
            ['code' => 'Samoan', 'awni_country_code_number' => null],
            ['code' => 'Scottish', 'awni_country_code_number' => null],
            ['code' => 'Welsh', 'awni_country_code_number' => null],
            ['code' => '(other)', 'awni_country_code_number' => null],
            ['code' => 'Argentinian', 'awni_country_code_number' => null],
            ['code' => 'Azores', 'awni_country_code_number' => null],
            ['code' => 'Balearic Islands', 'awni_country_code_number' => null],
            ['code' => 'Barbudans', 'awni_country_code_number' => null],
            ['code' => 'Belorussian', 'awni_country_code_number' => null],
            ['code' => 'British Virgin Islander', 'awni_country_code_number' => null],
            ['code' => 'Burkinese', 'awni_country_code_number' => null],
            ['code' => 'Burundian', 'awni_country_code_number' => null],
            ['code' => 'Cabo Verdean', 'awni_country_code_number' => null],
            ['code' => 'Canary Islands', 'awni_country_code_number' => null],
            ['code' => 'Channel Islander', 'awni_country_code_number' => null],
            ['code' => 'Citizen of Antigua and Barbuda', 'awni_country_code_number' => null],
            ['code' => 'Citizen of Bosnia and Herzegovina', 'awni_country_code_number' => null],
            ['code' => 'Citizen of Kiribati', 'awni_country_code_number' => null],
            ['code' => 'Citizen of the Dominican Republic', 'awni_country_code_number' => null],
            ['code' => 'Comorian', 'awni_country_code_number' => null],
            ['code' => 'Comoros Islands', 'awni_country_code_number' => null],
            ['code' => "Cote d'Ivoire", 'awni_country_code_number' => null],
            ['code' => 'Crimean and Sevastopolian', 'awni_country_code_number' => null],
            ['code' => 'Cymro', 'awni_country_code_number' => null],
            ['code' => 'Cymry', 'awni_country_code_number' => null],
            ['code' => 'Emarat', 'awni_country_code_number' => null],
            ['code' => 'English', 'awni_country_code_number' => null],
            ['code' => 'Equatoguinean', 'awni_country_code_number' => null],
            ['code' => 'Faroese', 'awni_country_code_number' => null],
            ['code' => 'Great Britain', 'awni_country_code_number' => null],
            ['code' => 'Greenlandic', 'awni_country_code_number' => null],
            ['code' => 'Guadaloupe', 'awni_country_code_number' => null],
            ['code' => 'Guadeloupe', 'awni_country_code_number' => null],
            ['code' => 'Guinea Bissau', 'awni_country_code_number' => null],
            ['code' => 'Islas Canaria', 'awni_country_code_number' => null],
            ['code' => 'Canary Islands', 'awni_country_code_number' => null],
            ['code' => 'Ivory Coast', 'awni_country_code_number' => null],
            ['code' => 'Kazakh', 'awni_country_code_number' => null],
            ['code' => 'Kiribatian', 'awni_country_code_number' => null],
            ['code' => 'Korean', 'awni_country_code_number' => null],
            ['code' => 'Kosovan', 'awni_country_code_number' => null],
            ['code' => 'Kosovar', 'awni_country_code_number' => null],
            ['code' => 'Liechtensteinian', 'awni_country_code_number' => null],
            ['code' => 'Luxembourgian', 'awni_country_code_number' => null],
            ['code' => 'Macanese', 'awni_country_code_number' => null],
            ['code' => 'Madagascan', 'awni_country_code_number' => null],
            ['code' => 'Maldivian', 'awni_country_code_number' => null],
            ['code' => 'Monegasque', 'awni_country_code_number' => null],
            ['code' => 'Montenegrin', 'awni_country_code_number' => null],
            ['code' => 'Motswana', 'awni_country_code_number' => null],
            ['code' => 'North Korean', 'awni_country_code_number' => null],
            ['code' => 'Northern Irish', 'awni_country_code_number' => null],
            ['code' => 'Prydeinig', 'awni_country_code_number' => null],
            ['code' => 'Reunion', 'awni_country_code_number' => null],
            ['code' => 'Saint Lucians', 'awni_country_code_number' => null],
            ['code' => 'Saint Vincent and the Grenadines', 'awni_country_code_number' => null],
            ['code' => 'Salvadorean', 'awni_country_code_number' => null],
            ['code' => 'Sammarinese', 'awni_country_code_number' => null],
            ['code' => 'Samoan', 'awni_country_code_number' => null],
            ['code' => 'Schengenian', 'awni_country_code_number' => null],
            ['code' => 'Scottish', 'awni_country_code_number' => null],
            ['code' => 'Sierra Leonian', 'awni_country_code_number' => null],
            ['code' => 'Slovak', 'awni_country_code_number' => null],
            ['code' => 'St Lucian', 'awni_country_code_number' => null],
            ['code' => 'St.Kitts', 'awni_country_code_number' => null],
            ['code' => 'St.Vincent', 'awni_country_code_number' => null],
            ['code' => 'Tahiti', 'awni_country_code_number' => null],
            ['code' => 'Trinidadian And Toboggan', 'awni_country_code_number' => null],
            ['code' => 'Tristanian', 'awni_country_code_number' => null],
            ['code' => 'Vanuatuan', 'awni_country_code_number' => null],
            ['code' => 'Virgin Islands (Usa)', 'awni_country_code_number' => null],
            ['code' => 'Welsh', 'awni_country_code_number' => null],
            ['code' => 'West Indian', 'awni_country_code_number' => null],
            ['code' => 'Western Samoa', 'awni_country_code_number' => null],
            ['code' => 'Yemeni', 'awni_country_code_number' => null],
            ['code' => 'Zairean', 'awni_country_code_number' => null],
            ['code' => 'Anguillan', 'awni_country_code_number' => null],
            ['code' => 'Cayman Islander', 'awni_country_code_number' => null],
            ['code' => 'Cook Islander', 'awni_country_code_number' => null],
            ['code' => 'Faroe Islands', 'awni_country_code_number' => null],
            ['code' => 'Faroe Islands', 'awni_country_code_number' => null],
            ['code' => 'Gibraltar', 'awni_country_code_number' => null],
            ['code' => 'Guam', 'awni_country_code_number' => null],
            ['code' => 'Guam', 'awni_country_code_number' => null],
            ['code' => 'Hong Konger', 'awni_country_code_number' => null],
            ['code' => 'Martinique', 'awni_country_code_number' => null],
            ['code' => 'Martinique', 'awni_country_code_number' => null],
            ['code' => 'Montserratian', 'awni_country_code_number' => null],
            ['code' => 'Pitcairn Islander', 'awni_country_code_number' => null],
            ['code' => 'South Sudanese', 'awni_country_code_number' => null],
            ['code' => 'St Helenian', 'awni_country_code_number' => null],
            ['code' => 'Turkmen', 'awni_country_code_number' => null],
            ['code' => 'TCA', 'awni_country_code_number' => null],
            ['code' => 'Vatican City', 'awni_country_code_number' => null],
            ['code' => 'Vincentian', 'awni_country_code_number' => null],
            ['code' => 'Virgin Islands ( British)', 'awni_country_code_number' => null],
            ['code' => 'Virgin Islands ( British)', 'awni_country_code_number' => null],
            ['code' => 'WLF', 'awni_country_code_number' => null],
            ['code' => 'ESH', 'awni_country_code_number' => null],
        ];

        DB::transaction(function () use ($nationalities): void {
            foreach ($nationalities as $entry) {
                DB::table('nationality')
                    ->where('code', $entry['code'])
                    ->update(['awni_country_code_number' => $entry['awni_country_code_number']]);
            }
        }, 5);
    }
}
