<?php

namespace Database\Seeders;

use App\Services\Logger\LoggerService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AwnicNationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['code' => 'Afghan', 'awni_country_code_number' => 1001],
            ['code' => 'Albanian', 'awni_country_code_number' => 1002],
            ['code' => 'Algerian', 'awni_country_code_number' => 1003],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'American', 'awni_country_code_number' => 1004],
            ['code' => 'Andorran', 'awni_country_code_number' => 1005],
            ['code' => 'Angolan', 'awni_country_code_number' => 1006],
            ['code' => 'Antiguans', 'awni_country_code_number' => 2002],
            ['code' => 'Argentinean', 'awni_country_code_number' => 1008],
            ['code' => 'Armenian', 'awni_country_code_number' => 1009],
            ['code' => 'Australian', 'awni_country_code_number' => 1010],
            ['code' => 'Australian', 'awni_country_code_number' => 1010],
            ['code' => 'Austrian', 'awni_country_code_number' => 1011],
            ['code' => 'Azerbaijani', 'awni_country_code_number' => 1012],
            ['code' => 'Bahamian', 'awni_country_code_number' => 1013],
            ['code' => 'Bahraini', 'awni_country_code_number' => 1014],
            ['code' => 'Bangladeshi', 'awni_country_code_number' => 1015],
            ['code' => 'Barbadian', 'awni_country_code_number' => 1016],
            ['code' => 'Batswana', 'awni_country_code_number' => 1018],
            ['code' => 'Belarusian', 'awni_country_code_number' => 1019],
            ['code' => 'Belgian', 'awni_country_code_number' => 1020],
            ['code' => 'Belizean', 'awni_country_code_number' => 1021],
            ['code' => 'Beninese', 'awni_country_code_number' => 1022],
            ['code' => 'Bermuda', 'awni_country_code_number' => 2004],
            ['code' => 'Bhutanese', 'awni_country_code_number' => 1023],
            ['code' => 'Bolivian', 'awni_country_code_number' => 1024],
            ['code' => 'Bosnian', 'awni_country_code_number' => 1025],
            ['code' => 'Brazilian', 'awni_country_code_number' => 1026],
            ['code' => 'British', 'awni_country_code_number' => 1027],
            ['code' => 'British', 'awni_country_code_number' => 1027],
            ['code' => 'British', 'awni_country_code_number' => 1027],
            ['code' => 'Bruneian', 'awni_country_code_number' => 1028],
            ['code' => 'Bulgarian', 'awni_country_code_number' => 1029],
            ['code' => 'Burkinabe', 'awni_country_code_number' => 1030],
            ['code' => 'Burkinan', 'awni_country_code_number' => 1030],
            ['code' => 'Burmese', 'awni_country_code_number' => 2005],
            ['code' => 'Burmese', 'awni_country_code_number' => 2005],
            ['code' => 'Burmese', 'awni_country_code_number' => 2005],
            ['code' => 'Cambodian', 'awni_country_code_number' => 1033],
            ['code' => 'Cameroonian', 'awni_country_code_number' => 1034],
            ['code' => 'Canadian', 'awni_country_code_number' => 1035],
            ['code' => 'Cape Verdean', 'awni_country_code_number' => 1036],
            ['code' => 'Central African', 'awni_country_code_number' => 1037],
            ['code' => 'Chadian', 'awni_country_code_number' => 1038],
            ['code' => 'Chilean', 'awni_country_code_number' => 1039],
            ['code' => 'Chinese', 'awni_country_code_number' => 1040],
            ['code' => 'Colombian', 'awni_country_code_number' => 1041],
            ['code' => 'Comoran', 'awni_country_code_number' => 1042],
            ['code' => 'Congolese', 'awni_country_code_number' => 1043],
            ['code' => 'Congolese (DRC)', 'awni_country_code_number' => 1043],
            ['code' => 'Costa Rican', 'awni_country_code_number' => 1045],
            ['code' => 'Croatian', 'awni_country_code_number' => 1046],
            ['code' => 'Cuban', 'awni_country_code_number' => 1047],
            ['code' => 'Cypriot', 'awni_country_code_number' => 1048],
            ['code' => 'Czech', 'awni_country_code_number' => 1049],
            ['code' => 'Danish', 'awni_country_code_number' => 1050],
            ['code' => 'Djibouti', 'awni_country_code_number' => 1051],
            ['code' => 'Dominican', 'awni_country_code_number' => 1052],
            ['code' => 'Dutch', 'awni_country_code_number' => 1054],
            ['code' => 'East Timorese', 'awni_country_code_number' => 1057],
            ['code' => 'Ecuadorean', 'awni_country_code_number' => 1058],
            ['code' => 'Egyptian', 'awni_country_code_number' => 1059],
            ['code' => 'Emirati', 'awni_country_code_number' => 1060],
            ['code' => 'Equatorial Guinean', 'awni_country_code_number' => 1061],
            ['code' => 'Eritrean', 'awni_country_code_number' => 1062],
            ['code' => 'Estonian', 'awni_country_code_number' => 1063],
            ['code' => 'Ethiopian', 'awni_country_code_number' => 1064],
            ['code' => 'Fijian', 'awni_country_code_number' => 1065],
            ['code' => 'Filipino', 'awni_country_code_number' => 2001],
            ['code' => 'Finnish', 'awni_country_code_number' => 1067],
            ['code' => 'French', 'awni_country_code_number' => 1068],
            ['code' => 'French', 'awni_country_code_number' => 1068],
            ['code' => 'Gabonese', 'awni_country_code_number' => 1069],
            ['code' => 'Gambian', 'awni_country_code_number' => 1070],
            ['code' => 'Georgian', 'awni_country_code_number' => 1071],
            ['code' => 'German', 'awni_country_code_number' => 1072],
            ['code' => 'Ghanaian', 'awni_country_code_number' => 1073],
            ['code' => 'Greek', 'awni_country_code_number' => 1074],
            ['code' => 'Grenadian', 'awni_country_code_number' => 1075],
            ['code' => 'Guatemalan', 'awni_country_code_number' => 1076],
            ['code' => 'Guinea-Bissauan', 'awni_country_code_number' => 1077],
            ['code' => 'Guinean', 'awni_country_code_number' => 1078],
            ['code' => 'Guyanese', 'awni_country_code_number' => 1079],
            ['code' => 'Haitian', 'awni_country_code_number' => 1080],
            ['code' => 'Honduran', 'awni_country_code_number' => 1082],
            ['code' => 'Hungarian', 'awni_country_code_number' => 1083],
            ['code' => 'I-Kiribati', 'awni_country_code_number' => 1084],
            ['code' => 'Icelander', 'awni_country_code_number' => 1085],
            ['code' => 'Indian', 'awni_country_code_number' => 1086],
            ['code' => 'Indonesian', 'awni_country_code_number' => 1087],
            ['code' => 'Iranian', 'awni_country_code_number' => 1088],
            ['code' => 'Iraqi', 'awni_country_code_number' => 1089],
            ['code' => 'Irish', 'awni_country_code_number' => 1090],
            ['code' => 'Israeli', 'awni_country_code_number' => 2008],
            ['code' => 'Italian', 'awni_country_code_number' => 1092],
            ['code' => 'Kazakhstani', 'awni_country_code_number' => 1097],
            ['code' => 'Kenyan', 'awni_country_code_number' => 1098],
            ['code' => 'Kittian and Nevisian', 'awni_country_code_number' => 1099],
            ['code' => 'Kuwaiti', 'awni_country_code_number' => 1100],
            ['code' => 'Kyrgyz', 'awni_country_code_number' => 1101],
            ['code' => 'Laotian', 'awni_country_code_number' => 1102],
            ['code' => 'Latvian', 'awni_country_code_number' => 1103],
            ['code' => 'Lebanese', 'awni_country_code_number' => 1104],
            ['code' => 'Liberian', 'awni_country_code_number' => 1105],
            ['code' => 'Libyan', 'awni_country_code_number' => 1106],
            ['code' => 'Liechtensteiner', 'awni_country_code_number' => 1107],
            ['code' => 'Lithuanian', 'awni_country_code_number' => 1108],
            ['code' => 'Luxembourger', 'awni_country_code_number' => 1109],
            ['code' => 'Macedonian', 'awni_country_code_number' => 1110],
            ['code' => 'Madeira', 'awni_country_code_number' => 1149],
            ['code' => 'Malagasy', 'awni_country_code_number' => 1111],
            ['code' => 'Malawian', 'awni_country_code_number' => 1112],
            ['code' => 'Malaysian', 'awni_country_code_number' => 1113],
            ['code' => 'Maldivan', 'awni_country_code_number' => 1114],
            ['code' => 'Malian', 'awni_country_code_number' => 1115],
            ['code' => 'Maltese', 'awni_country_code_number' => 1116],
            ['code' => 'Marshallese', 'awni_country_code_number' => 1117],
            ['code' => 'Mauritanian', 'awni_country_code_number' => 1118],
            ['code' => 'Mauritian', 'awni_country_code_number' => 1119],
            ['code' => 'Mexican', 'awni_country_code_number' => 1120],
            ['code' => 'Micronesian', 'awni_country_code_number' => 1121],
            ['code' => 'Moldovan', 'awni_country_code_number' => 1122],
            ['code' => 'Monacan', 'awni_country_code_number' => 1123],
            ['code' => 'Mongolian', 'awni_country_code_number' => 1124],
            ['code' => 'Moroccan', 'awni_country_code_number' => 1125],
            ['code' => 'Mosotho', 'awni_country_code_number' => 1126],
            ['code' => 'Namibian', 'awni_country_code_number' => 1129],
            ['code' => 'Nauruan', 'awni_country_code_number' => 1130],
            ['code' => 'Nepalese', 'awni_country_code_number' => 1131],
            ['code' => 'New Zealander', 'awni_country_code_number' => 1133],
            ['code' => 'New Zealander', 'awni_country_code_number' => 1133],
            ['code' => 'Ni-vanuatu', 'awni_country_code_number' => 1134],
            ['code' => 'Ni-vanuatu', 'awni_country_code_number' => 1134],
            ['code' => 'Nicaraguan', 'awni_country_code_number' => 1135],
            ['code' => 'Nigerian', 'awni_country_code_number' => 1136],
            ['code' => 'Nigerian', 'awni_country_code_number' => 1136],
            ['code' => 'Nigerien', 'awni_country_code_number' => 1137],
            ['code' => 'Niuean', 'awni_country_code_number' => 1134],
            ['code' => 'Norwegian', 'awni_country_code_number' => 1140],
            ['code' => 'Norwegian', 'awni_country_code_number' => 1140],
            ['code' => 'Omani', 'awni_country_code_number' => 1141],
            ['code' => 'Pakistani', 'awni_country_code_number' => 1142],
            ['code' => 'Palauan', 'awni_country_code_number' => 1143],
            ['code' => 'Palestinian', 'awni_country_code_number' => 1201],
            ['code' => 'Panamanian', 'awni_country_code_number' => 1144],
            ['code' => 'Papua New Guinean', 'awni_country_code_number' => 1145],
            ['code' => 'Paraguayan', 'awni_country_code_number' => 1146],
            ['code' => 'Peruvian', 'awni_country_code_number' => 1147],
            ['code' => 'Polish', 'awni_country_code_number' => 1148],
            ['code' => 'Puerto Rico', 'awni_country_code_number' => 2010],
            ['code' => 'Puerto Rico', 'awni_country_code_number' => 2010],
            ['code' => 'Qatari', 'awni_country_code_number' => 1150],
            ['code' => 'Romanian', 'awni_country_code_number' => 1151],
            ['code' => 'Russian', 'awni_country_code_number' => 1152],
            ['code' => 'Rwandan', 'awni_country_code_number' => 1153],
            ['code' => 'Saint Lucian', 'awni_country_code_number' => 1154],
            ['code' => 'Salvadoran', 'awni_country_code_number' => 1155],
            ['code' => 'San Marinese', 'awni_country_code_number' => 1157],
            ['code' => 'Sao Tomean', 'awni_country_code_number' => 1158],
            ['code' => 'Saudi', 'awni_country_code_number' => 1159],
            ['code' => 'Senegalese', 'awni_country_code_number' => 1161],
            ['code' => 'Serbian', 'awni_country_code_number' => 1162],
            ['code' => 'Seychellois', 'awni_country_code_number' => 1163],
            ['code' => 'Sierra Leonean', 'awni_country_code_number' => 1164],
            ['code' => 'Singaporean', 'awni_country_code_number' => 1165],
            ['code' => 'Slovakian', 'awni_country_code_number' => 1166],
            ['code' => 'Slovenian', 'awni_country_code_number' => 1167],
            ['code' => 'Solomon Islander', 'awni_country_code_number' => 1168],
            ['code' => 'Somali', 'awni_country_code_number' => 1169],
            ['code' => 'South African', 'awni_country_code_number' => 1170],
            ['code' => 'South Korean', 'awni_country_code_number' => 1171],
            ['code' => 'Spanish', 'awni_country_code_number' => 1172],
            ['code' => 'Sri Lankan', 'awni_country_code_number' => 1173],
            ['code' => 'Sudanese', 'awni_country_code_number' => 1174],
            ['code' => 'Surinamer', 'awni_country_code_number' => 1175],
            ['code' => 'Swazi', 'awni_country_code_number' => 1176],
            ['code' => 'Swedish', 'awni_country_code_number' => 1177],
            ['code' => 'Swiss', 'awni_country_code_number' => 1178],
            ['code' => 'Syrian', 'awni_country_code_number' => 1179],
            ['code' => 'Taiwanese', 'awni_country_code_number' => 1180],
            ['code' => 'Tajik', 'awni_country_code_number' => 1181],
            ['code' => 'Tanzanian', 'awni_country_code_number' => 1182],
            ['code' => 'Thai', 'awni_country_code_number' => 1183],
            ['code' => 'Togolese', 'awni_country_code_number' => 1184],
            ['code' => 'Tongan', 'awni_country_code_number' => 1185],
            ['code' => 'Trinidadian or Tobagonian', 'awni_country_code_number' => 1186],
            ['code' => 'Tunisian', 'awni_country_code_number' => 1187],
            ['code' => 'Turkish', 'awni_country_code_number' => 1188],
            ['code' => 'Tuvaluan', 'awni_country_code_number' => 1189],
            ['code' => 'Ugandan', 'awni_country_code_number' => 1190],
            ['code' => 'Ukrainian', 'awni_country_code_number' => 1191],
            ['code' => 'Uruguayan', 'awni_country_code_number' => 1192],
            ['code' => 'Uzbekistani', 'awni_country_code_number' => 1193],
            ['code' => 'Venezuelan', 'awni_country_code_number' => 1194],
            ['code' => 'Vietnamese', 'awni_country_code_number' => 1195],
            ['code' => 'Yemenite', 'awni_country_code_number' => 1198],
            ['code' => 'Zambian', 'awni_country_code_number' => 1199],
            ['code' => 'Zimbabwean', 'awni_country_code_number' => 1200],
        ];

        /** @var list<array{index: int, code: mixed, awni_country_code_number: mixed}> $skipped */
        $skipped = [];
        /** @var list<array{index: int, code: string, awni_country_code_number: int|float, rows_affected: int}> $updated */
        $updated = [];
        /** @var list<array{index: int, code: string, awni_country_code_number: int|float}> $notUpdated */
        $notUpdated = [];

        foreach ($nationalities as $index => $entry) {
            $oneBasedIndex = $index + 1;

            if (empty($entry['code']) || empty($entry['awni_country_code_number'])) {
                $skipped[] = [
                    'index' => $oneBasedIndex,
                    'code' => $entry['code'] ?? null,
                    'awni_country_code_number' => $entry['awni_country_code_number'] ?? null,
                ];

                continue;
            }

            $rowsAffected = DB::table('nationality')
                ->where('code', $entry['code'])
                ->update(['awni_country_code_number' => $entry['awni_country_code_number']]);

            if ($rowsAffected > 0) {
                $updated[] = [
                    'index' => $oneBasedIndex,
                    'code' => (string) $entry['code'],
                    'awni_country_code_number' => $entry['awni_country_code_number'],
                    'rows_affected' => $rowsAffected,
                ];
            } else {
                $notUpdated[] = [
                    'index' => $oneBasedIndex,
                    'code' => (string) $entry['code'],
                    'awni_country_code_number' => $entry['awni_country_code_number'],
                ];
            }
        }

        LoggerService::info('AwnicNationalitySeeder: AWNIC nationality mapping run', [
            'summary' => [
                'total_entries' => count($nationalities),
                'updated_count' => count($updated),
                'not_updated_count' => count($notUpdated),
                'skipped_invalid_count' => count($skipped),
            ],
            'updated' => $updated,
            'not_updated_no_db_row' => $notUpdated,
            'skipped_invalid_fields' => $skipped,
        ]);
    }
}
