<?php

namespace Database\Seeders;

use App\Models\BusinessActivity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessActivitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $activities = [
            'Agriculture and related activities', 'Hunting, trapping and related service activities',
            'Animal production', 'Mixed farming',
            'Growing of perennial crops', 'Plant propagation',
            'Growing of non-perennial crops', 'Gathering of non-wood forest products',
            'Support services to forestry', 'Silviculture and other forestry activities',
            'Logging', 'Aquaculture',
            'Fishing', 'Mining of hard coal',
            'Mining of lignite', 'Extraction of crude petroleum',
            'Extraction of natural gas', 'Mining of iron ores',
            'Mining of non-ferrous metal ores', 'Mining and processing of ores with hot processes (excl. underground mining and processes)',
            'Mining and processing of ores: cold processes (excl. underground mining and processes)', 'Production of gypsum excl. plasterboards',
            'Mineral mining and processing (e.g. quarry, mine and mill for gravel, clay, limestone)', 'Mining and quarrying n.e.c.',
            'Support activities for petroleum and natural gas extraction', 'Support activities for other mining and quarrying',
            'Manufacture of soap and detergents, cleaning and polishing preparations', 'Varnish, paints, colouring agents, printing ink and adhesives', 'Manufacture of other chemical products',
            'Production of organic and inorganic products (e.g. ammonia, fertiliser, solvents, acids, salts)',
            'Manufacture of perfumes, aerosols and toilet cleaners', 'Air separation units',
            'Production of organic and inorganic products (e.g. ammonia, fertiliser, solvents, acids, salts) with production/usage of ', 'flammable liquids or explosive materials.', 'Production of man-made fibres (polyester, chemical fibres, synthetic fibress)',
            'Manufacture of explosives', 'Manufacture of furniture',
            'Manufacture of transport equipment n.e.c.', 'Manufacture, repair and maintenance of watercraft (shipyard,drydocks, boats etc.)',
            'Manufacture of railway locomotives and rolling stock', 'Aircrafts repair and maintenance including overhauling and re-equipment',
            'Manufacture of military fighting vehicles', 'Manufacture of plastics products such as foils, pre-forms, laminations other than foam mattress.',
            'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres, other rubber products',
            'Plastic product manufacturer by using extrusion, injection / blow moulding & casting under normal condition.',
            'Plastic product manufacturer & foam plastics using flammable liquid above 500 c & pressure over 200 bar.',
            'Manufacture of non-alcoholic beverages (soft drinks)', 'Manufacture of alcoholic beverages',
            'Repair of fabricated metal products, machinery and equipment', 'Installation of industrial machinery and equipment',
            'Food processing factory - fruits and vegetables', 'Processing and preserving of fish, crustaceans and molluscs',
            'Food processing factory - meat and fish products', 'Manufacture of animal food/fodder and pet food',
            'Sugar and non sugar refinery', 'Bakeries',
            'Potato products / snacks processing / corn / other stratch products', 'Manufacture of grain mill products, starches and starch products',
            'Pasta / noodles manufacturing', 'Manufacture of milk and dairy products',
            'Animal and vegetable oil refining/ processing without hydrogeneration.', 'Processing of tea and coffee (bagging & roasting).',
            'Sweets (confectionery, chocolate, syrup)', 'Animal and vegetable oil refining/ processing with hydrogeneration (such as margerine, ghee)',
            'Dehydrated convenience food (pudding, drying powder) and condiments/seasoning/spices', 'Slaughter houses/abattoirs',
            'Manufacture of pharmaceutical and cosmetic products with the use of flammable material.',
            'Manufacture of pharmaceutical and cosmetic products without use of flammable material.',
            'Manufacture of pharmaceuticals, medicinal chemical and botanical products', 'Manufacture of games and toys',
            'Manufacture of medical and dental instruments and supplies', 'Other manufacturing n.e.c.',
            'Manufacture of jewellery, bijouterie and related articles', 'Manufacture of musical instruments',
            'Manufacture of sports goods', 'Manufacture of pillows, quilts, blankets, curtains, etc',
            'Garment manufacturers (knitting, hosiery, embroidery,ready-made garments), sewing.',
            'Spinning mills and yarn manufacture, weaving, cloth processing', 'Steel mill - rolling mill (re-heating only).',
            'Non ferrus powder manufactrurer.', 'Production and processing of gold, silver and jewellery',
            'Aluminium and other non ferous metal industry - rolling mill including wire drawing.',
            'Steel industry - rolling mill, galvanizing, electrical coating, painting, integrated steel plant, foundary. arc furnace, ', 'remelting re-heating.',
            'Aluminium and other non ferous metal industry - refining and smelting (excluding magnasium)',
            'Light engineering works', 'Manufacture of basic precious and other non-ferrous metals',
            'Steel industry - steel plant, foundry, sinter plant, blast furnace.', 'Manufacture of glass and glass products.',
            'Steel industry - coke plant', 'Manufacture of abrasive products and non-metallic mineral products n.e.c.',
            'Cement products such as concrete blocks, pre-casts alike.', 'Production of gypsum, plasterboards',
            'Cement plant with or without rotary kiln (including quarry, crushing and finish product packaging and storage)',
            'Manufacture of porcelain and ceramic products', 'Manufacture of tobacco products',
            'Manufacture of other electronic products', 'Manufacture of magnetic and optical media',
            'Manufacture of optical instruments and photographic equipment',
            'Manufacture of irradiation, electromedical and electrotherapeutic equipment',
            'Manufacture of measuring, testing, navigating and control equipment; watches and clocks',
            'Manufacture of consumer electronics', 'Manufacture of communication equipment',
            'Manufacture of computers and peripheral equipment', 'Manufacture of computers and peripherals',
            'Manufacture of footwear', 'Leather products processing & letaher goods manufacturing.',
            'Manufacture of knitted and crocheted apparel', 'Manufacture of articles of fur',
            'Manufacture of wearing apparel, except fur apparel', 'Manufacture of other fabricated metal products; metalworking service activities',
            'Heavy engineering works', 'Manufacture of weapons and ammunition',
            'Manufacture of structural metal products, tanks, reservoirs and steam generators',
            'Manufacture of hygiene products made of paper,cotton, wool (tissues, diapers etc)',
            'Manufacture of articles of paper and cardboard', 'Manufacture of paper & pulp.',
            'Manufacture of paper and paper products', 'Manufacture of special-purpose machinery',
            'Manufacture of general-purpose machinery', 'Manufacture of wood products including furniture (carpentry works)',
            'Sawmilling and planing of wood', 'Manufacture of other electrical equipment',
            'Manufacture of domestic appliances', 'Manufacture of domestic appliances, lighting equipment and other electrical equipments',
            'Manufacture of electronic and electric wires and cables including fibre-optic cables', 'Manufacture of batteries',
            'Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus',
            'Manufacturing of lubricants from oil refined products', 'Manufacture of refined petroleum products',
            'Coal briquetting', 'Reproduction of recorded media',
            'Printing press', 'Manufacture of parts and accessories for motor vehicles',
            'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers', 'Manufacture of motor vehicles',
            'Photovoltaic plant', 'Solar power plant',
            'Underground cables, pipes and other facilities', 'Combined cycle power plants',
            'Transformers and switchgears', 'Manufacture of gas; distribution of gaseous fuels through mains',
            'Outdoor cooling towers', 'Conventional power plants (excl. nuclear power plants)',
            'Waste water treatment & sewerage', 'Water distribution (potable & sea water)',
            'Remediation activities and other waste management services', 'Waste collection',
            'Waste treatment and disposal plant (oil & gas)', "Separation/sorting/processing of different commercial grades for recycling as a preliminary stage to raw material ',utilisation. 'processing shall be understood as shredding, cleaning, drying, grinding, melting and palletising, solid waste ',treatment and 'disposal plant other than oil & gas.",
            'Construction of buildings', 'Other specialized construction activities',
            'Building completion and finishing', 'Demolition and site preparation',
            'Electrical, plumbing and other construction installation activities', 'Civil works, construction, completed civil structures',
            'Construction of utility projects', 'Construction of other civil engineering projects',
            'Wholesale of machinery, equipment and supplies', 'Other specialized wholesale',
            'Non-specialized wholesale trade', 'Wholesale on a fee or contract basis',
            'Wholesale of agricultural raw materials and live animals', 'Wholesale of food, beverages and tobacco',
            'Wholesale of household goods', 'Motor vehicle showroom including spare parts and accessories',
            'Motor garages/workshops', 'Sale of motor vehicle parts and accessories',
            'Sale, maintenance and repair of motorcycles and related parts and accessories', 'Supermarkets, grocery',
            'Retail sale of food, beverages and tobacco in specialized stores', 'Fuel stations',
            'Retail sale of information and communications equipment in specialized stores', 'Furniture showrooms',
            'Retail sale of cultural and recreation goods in specialized stores', 'Retail others - non hazardous',
            'Retail sale via stalls and markets', 'Retail trade not in stores, stalls or markets',
            'Retail - textiles, carpets, rugs and the like.', 'Commercial shopping malls',
            'Shops in souq', 'Department store, hypermarket',
            'Inland water transport', 'Sea and coastal water transport',
            'Civil structures like bridge, tunnel, dam, dike and wharf', 'Railways depots',
            'Motor vehicle storage (open & covered)', 'Cold stores',
            'Tank farms',
            "Extra hazardous goods warehouse as per nfpa class iv such as ammenities, disposable materials, furniture with foam & plastic, ,liquir, match box, paints, chemicals & liquids with flash point less than 37.8 0 c. and alike commodities. - for more details ,pls refer to the nfpa manual.",

            "Hazardous goods warehouse - as per nfpa class iii - such as aerosols, charcoal, clothes, fiber, yarn, textiles, furniture ,without plastics & foam material, plastics, paper, leather goods, tobaco products, chemicals & liquid with flash point ,between 37.80 c & 600 c and alike commodities. - for more details pls refer to the nfpa manual.",

            'Non hazardous warehouse as per nfpa class - i; such as white goods, metal parts, canned foods, machineries, spare parts, ,cement, dairy products, coffe, non combustible liquid, salt, soya, grains, medicines and alike commodities - refer nfpa ,manual for more details.',

            'State owned warehouse (e.g. customs warehouses)',

            'Low hazardous material as per nfpa class - ii such as batteries, liquid with low flamable liquid (flash point above 600c, paper products (books, magazines), wood products (lumber plywood, prested board), class i matrial packed in combustible, material and alike commodities. - for more details pls refer to the nfpa manual.',

            'Warehousing and storage / open yard (other than automobile)', 'Airplane hangars',
            'Commercial port/harbors, fishing port, sea and river port', 'Freight air transport',
            'Airports',
            'Limousine services picking up third parties for pre booked rides including but not limited to Careem and Uber',
            'Limousine services working on contract basis e.g. Hotels but excluding Uber/Careem services',
            'Taxi service picking up from road side', 'Courier activities',
            'Postal activities', 'Transport via pipeline',
            'Other land transport', 'Transport via railways',
            'Camping grounds, recreational vehicle parks and trailer parks', 'Hotel, health and social clubs',
            'Other accommodation', 'Restaurants / cafes',
            'Beverage serving activities', 'Event catering and other food service activities',
            'Wired telecommunications activities', 'Wireless telecommunications activities',
            'Satellite telecommunications activities', 'Telecommunication',
            'Other telecommunications activities', 'Television programming and broadcasting activities',
            'Media, advertising, radio broadcasting, tv stations', 'Electronic data processing centre',
            'Other information service activities', 'Computer programming, consultancy and related activities',
            'Software publishing', 'Publishing of books, periodicals and other publishing activities',
            'Cinemas', 'Sound recording and music publishing activities',
            'Film studios, film printing plants', 'Trusts, funds and similar financial entities',
            'Financial service activities(banking, insurance,stock exchanges)', 'Activities of holding companies',
            'Other financial service activities, except insurance and pension funding activities',
            'Activities auxiliary to financial service activities, except insurance and pension funding',
            'Activities auxiliary to insurance and pension funding', 'Fund management activities',
            'Reinsurance', 'Pension funding',
            'Insurance', 'Real estate activities with own or leased property',
            'Real estate activities on a fee or contract basis', 'Real estate agencies',
            'Office blocks', 'Multi storied building (less than 15 stories)',
            'Multi storied building (more than 15 stories)', 'Villa complex',
            'Accounting, bookkeeping and auditing activities; tax consultancy', 'Legal activities',
            'Architectural and engineering activities and related technical consultancy', 'Technical testing and analysis',
            'Management consultancy activities', 'Activities of head offices',
            'Advertising', 'Market research and public opinion polling',
            'Research and experimental development on social sciences and humanities', 'Research institutes and laboratories',
            'Veterinary activities', 'Photo studios/laboratories',
            'Photographic activities', 'Specialized design activities',
            'Travel agency and tour operator activities', 'Other reservation service and related activities',
            'Landscape care and maintenance service activities', 'Cleaning activities',
            'Combined facilities support activities', 'Private security activities',
            'Investigation activities', 'Security systems service activities',
            'Business support service activities n.e.c.', 'Organization of conventions and trade shows',
            'Activities of call centres', 'Travel agency/tour operators',
            'Other human resources provision', 'Temporary employment agency activities',
            'Activities of employment placement agencies', 'Leasing of intellectual property and similar products, except copyrighted works',
            'Renting and leasing of motor vehicles', 'Renting and leasing of personal and household goods',
            'Renting and leasing of other machinery, equipment and tangible goods', 'Compulsory social security activities',
            'Provision of services to the community as a whole', 'General public administration activities, municipality services etc.',
            'Secondary education', 'Pre-primary and primary education',
            'Other education', 'Higher education',
            'Educational support activities', 'Schools / colleges/universities',
            'Other social work activities without accommodation', 'Social work activities without accommodation for the elderly and disabled',
            'Other residential care activities', 'Residential care activities for the elderly and disabled',
            'Residential care activities for mental retardation, mental health and substance abuse',
            'Residential nursing care facilities', 'Other human health activities',
            'Medical and dental practice activities', 'Clinics/nursing home/hospitals',
            'Concert halls, theaters', 'Gambling and betting activities',
            'Libraries, archives, museums and other cultural activities', 'Sports activities',
            'Hazardous sports activities', 'Night-clubs, bowling, dancing, discotheques',
            'Public meeting or show under tents or inflated structures', 'Amusement centre/theme parks',
            'Exhibition centres', 'Laundries, crabbing, dry-cleaning shops (also with dyehouse)',
            'Repair of computers and communication equipment', 'Repair of personal and household goods',
            'Churches / mosques / museums', 'Activities of business, employers and professional membership organizations',
            'Activities of trade unions', 'Undifferentiated goods-producing activities of private households for own use',
            'Undifferentiated service-producing activities of private households for own use',
            'Activities of households as employers of domestic personnel', 'Activities of extraterritorial organizations and bodies'
        ];

        foreach($activities as $activity) {
            BusinessActivity::firstOrCreate(['name' => $activity]);
        }
    }
}
