<?php

namespace Database\Seeders;

use App\Models\CanonicalNationality;
use App\Models\Nationality;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CanonicalNationalitySeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['Afghan', 'Afghan', 'CN0001', false, true],
            ['Albanian', 'Albanian', 'CN0002', false, true],
            ['Algerian', 'Algerian', 'CN0003', false, true],
            ['American', 'American', 'CN0004', false, true],
            ['Andorran', 'Andorran', 'CN0005', false, true],
            ['Angolan', 'Angolan', 'CN0006', false, true],
            ['Anguillan', 'Anguillan', 'CN0007', false, true],
            ['Antiguan and Barbudan', 'Antiguan and Barbudan', 'CN0008', false, true],
            ['Antiguans', 'Antiguans', 'CN0009', false, true],
            ['Argentinean', 'Argentinian', 'CN0010', true, true],
            ['Argentinian', 'Argentinian', 'CN0010', false, true],
            ['Armenian', 'Armenian', 'CN0011', false, true],
            ['Australian', 'Australian', 'CN0012', false, true],
            ['Austrian', 'Austrian', 'CN0013', false, true],
            ['Azerbaijani', 'Azerbaijani', 'CN0014', false, true],
            ['Bahraini', 'Bahraini', 'CN0015', false, true],
            ['Balearic Islands', 'Balearic Islands', 'CN0016', false, true],
            ['Bangladeshi', 'Bangladeshi', 'CN0017', false, true],
            ['Barbadian', 'Barbadian', 'CN0018', false, true],
            ['Barbudans', 'Barbudans', 'CN0019', false, true],
            ['Batswana', 'Batswana', 'CN0020', false, true],
            ['Belarusian', 'Belarusian', 'CN0021', false, true],
            ['Belgian', 'Belgian', 'CN0022', false, true],
            ['Belizean', 'Belizean', 'CN0023', false, true],
            ['Belorussian', 'Belarusian', 'CN0021', true, true],
            ['Beninese', 'Beninese', 'CN0024', false, true],
            ['Bermuda', 'Bermuda', 'CN0025', false, true],
            ['Bermudian', 'Bermudian', 'CN0026', false, true],
            ['Bhutanese', 'Bhutanese', 'CN0027', false, true],
            ['Bolivian', 'Bolivian', 'CN0028', false, true],
            ['Bosnian', 'Bosnian', 'CN0029', false, true],
            ['Botswanan', 'Botswanan', 'CN0030', false, true],
            ['Brazilian', 'Brazilian', 'CN0031', false, true],
            ['British', 'British', 'CN0032', false, true],
            ['British Virgin Islander', 'British Virgin Islander', 'CN0033', false, true],
            ['Bulgarian', 'Bulgarian', 'CN0034', false, true],
            ['Burkinabe', 'Burkinabe', 'CN0035', false, true],
            ['Burkinan', 'Burkinabe', 'CN0035', 'Burkinan', true],
            ['Burmese', 'Burmese', 'CN0036', false, true],
            ['Burundian', 'Burundian', 'CN0037', false, true],
            ['Cambodian', 'Cambodian', 'CN0038', false, true],
            ['Cameroonian', 'Cameroonian', 'CN0039', false, true],
            ['Canadian', 'Canadian', 'CN0040', false, true],
            ['Cape Verdean', 'Cape Verdean', 'CN0041', false, true],
            ['Cayman Islander', 'Cayman Islander', 'CN0042', false, true],
            ['Central African', 'Central African', 'CN0043', false, true],
            ['Chadian', 'Chadian', 'CN0044', false, true],
            ['Chilean', 'Chilean', 'CN0045', false, true],
            ['Chinese', 'Chinese', 'CN0046', false, true],
            ['Citizen of Antigua and Barbuda', 'Antiguan and Barbudan', 'CN0008', true, true],
            ['Citizen of Bosnia and Herzegovina', 'Bosnian', 'CN0029', true, true],
            ['Citizen of Seychelles', 'Seychellois', 'CN0047', true, true],
            ['Citizen of the Dominican Republic', 'Dominican', 'CN0048', true, true],
            ['Colombian', 'Colombian', 'CN0049', false, true],
            ['Comoran', 'Comorian', 'CN0050', true, true],
            ['Comorian', 'Comorian', 'CN0050', false, true],
            ['Comoros Islands', 'Comorian', 'CN0050', true, true],
            ['Congolese', 'Congolese', 'CN0051', false, true],
            ['Congolese (Congo)', 'Congolese', 'CN0051', true, true],
            ['Congolese (DRC)', 'Congolese', 'CN0051', true, true],
            ['Costa Rican', 'Costa Rican', 'CN0052', false, true],
            ['Croatian', 'Croatian', 'CN0053', false, true],
            ['Cuban', 'Cuban', 'CN0054', false, true],
            ['Cypriot', 'Cypriot', 'CN0055', false, true],
            ['Czech', 'Czech', 'CN0056', false, true],
            ['Danish', 'Danish', 'CN0057', false, true],
            ['Djiboutian', 'Djiboutian', 'CN0058', false, true],
            ['Dominica', 'Dominican', 'CN0048', true, true],
            ['Dominican', 'Dominican', 'CN0048', false, true],
            ['Dutch', 'Dutch', 'CN0059', false, true],
            ['Ecuadorean', 'Ecuadorian', 'CN0060', false, true],
            ['Egyptian', 'Egyptian', 'CN0061', false, true],
            ['Emarat', 'Emirati', 'CN0062', true, true],
            ['Emirati', 'Emirati', 'CN0062', false, true],
            ['English', 'British', 'CN0032', true, true],
            ['Eritrean', 'Eritrean', 'CN0063', false, true],
            ['Estonian', 'Estonian', 'CN0064', false, true],
            ['Ethiopian', 'Ethiopian', 'CN0065', false, true],
            ['Faroese', 'Faroese', 'CN0066', false, true],
            ['Fijian', 'Fijian', 'CN0067', false, true],
            ['Filipino', 'Filipino', 'CN0068', false, true],
            ['Finnish', 'Finnish', 'CN0069', false, true],
            ['French', 'French', 'CN0070', false, true],
            ['Gabonese', 'Gabonese', 'CN0071', false, true],
            ['Gambian', 'Gambian', 'CN0072', false, true],
            ['Georgian', 'Georgian', 'CN0073', false, true],
            ['German', 'German', 'CN0074', false, true],
            ['Ghanaian', 'Ghanaian', 'CN0075', false, true],
            ['Gibraltar', 'Gibraltar', 'CN0076', false, true],
            ['Great Britain', 'British', 'CN0032', true, true],
            ['Greek', 'Greek', 'CN0077', false, true],
            ['Greenlandic', 'Greenlandic', 'CN0078', false, true],
            ['Grenadian', 'Grenadian', 'CN0079', false, true],
            ['Guadaloupe', 'Guadeloupe', 'CN0080', true, true],
            ['Guinean', 'Guinean', 'CN0081', false, true],
            ['Guyanese', 'Guyanese', 'CN0082', false, true],
            ['Haitian', 'Haitian', 'CN0083', false, true],
            ['Honduran', 'Honduran', 'CN0084', false, true],
            ['Hong Konger', 'Hong Konger', 'CN0085', false, true],
            ['Hungarian', 'Hungarian', 'CN0086', false, true],
            ['Icelandic', 'Icelandic', 'CN0087', false, true],
            ['Indian', 'Indian', 'CN0088', false, true],
            ['Indonesian', 'Indonesian', 'CN0089', false, true],
            ['Iranian', 'Iranian', 'CN0090', false, true],
            ['Iraqi', 'Iraqi', 'CN0091', false, true],
            ['Irish', 'Irish', 'CN0092', false, true],
            ['Israeli', 'Israeli', 'CN0093', false, true],
            ['Italian', 'Italian', 'CN0094', false, true],
            ['Ivorian', 'Ivorian', 'CN0095', false, true],
            ['Jamaican', 'Jamaican', 'CN0096', false, true],
            ['Japanese', 'Japanese', 'CN0097', false, true],
            ['Jordanian', 'Jordanian', 'CN0098', false, true],
            ['Kazakh', 'Kazakhstani', 'CN0099', true, true],
            ['Kazakhstani', 'Kazakhstani', 'CN0099', false, true],
            ['Kenyan', 'Kenyan', 'CN0100', false, true],
            ['Kittian and Nevisian', 'Kittian and Nevisian', 'CN0101', false, true],
            ['Korean', 'Korean', 'CN0102', false, true],
            ['Kosovan', 'Kosovar', 'CN0103', true, true],
            ['Kosovar', 'Kosovar', 'CN0103', false, true],
            ['Kuwaiti', 'Kuwaiti', 'CN0104', false, true],
            ['Kyrgyz', 'Kyrgyz', 'CN0105', false, true],
            ['Latvian', 'Latvian', 'CN0106', false, true],
            ['Lebanese', 'Lebanese', 'CN0107', false, true],
            ['Liberian', 'Liberian', 'CN0108', false, true],
            ['Libyan', 'Libyan', 'CN0109', false, true],
            ['Lithuanian', 'Lithuanian', 'CN0110', false, true],
            ['Luxembourger', 'Luxembourger', 'CN0111', false, true],
            ['Luxembourgian', 'Luxembourger', 'CN0111', true, true],
            ['Macedonian', 'Macedonian', 'CN0112', false, true],
            ['Madagascan', 'Malagasy', 'CN0113', true, true],
            ['Malagasy', 'Malagasy', 'CN0113', false, true],
            ['Malawian', 'Malawian', 'CN0114', false, true],
            ['Malaysian', 'Malaysian', 'CN0115', false, true],
            ['Maldivan', 'Maldivian', 'CN0116', true, true],
            ['Maldivian', 'Maldivian', 'CN0116', false, true],
            ['Malian', 'Malian', 'CN0117', false, true],
            ['Maltese', 'Maltese', 'CN0118', false, true],
            ['Mauritanian', 'Mauritanian', 'CN0119', false, true],
            ['Mauritian', 'Mauritian', 'CN0120', false, true],
            ['Mexican', 'Mexican', 'CN0121', false, true],
            ['Micronesian', 'Micronesian', 'CN0122', false, true],
            ['Moldovan', 'Moldovan', 'CN0123', false, true],
            ['Monacan', 'Monacan', 'CN0124', false, true],
            ['Mongolian', 'Mongolian', 'CN0125', false, true],
            ['Montenegrin', 'Montenegrin', 'CN0126', false, true],
            ['Moroccan', 'Moroccan', 'CN0127', false, true],
            ['Mozambican', 'Mozambican', 'CN0128', false, true],
            ['Namibian', 'Namibian', 'CN0129', false, true],
            ['Nepalese', 'Nepalese', 'CN0130', false, true],
            ['New Zealander', 'New Zealander', 'CN0131', false, true],
            ['Ni-vanuatu', 'Vanuatuan', 'CN0132', true, true],
            ['Nicaraguan', 'Nicaraguan', 'CN0133', false, true],
            ['Nigerian', 'Nigerian', 'CN0134', false, true],
            ['Nigerien', 'Nigerien', 'CN0135', false, true],
            ['Norwegian', 'Norwegian', 'CN0136', false, true],
            ['Omani', 'Omani', 'CN0137', false, true],
            ['Pakistani', 'Pakistani', 'CN0138', false, true],
            ['Palauan', 'Palauan', 'CN0139', false, true],
            ['Palestinian', 'Palestinian', 'CN0140', false, true],
            ['Panamanian', 'Panamanian', 'CN0141', false, true],
            ['Papua New Guinean', 'Papua New Guinean', 'CN0142', false, true],
            ['Paraguayan', 'Paraguayan', 'CN0143', false, true],
            ['Peruvian', 'Peruvian', 'CN0144', false, true],
            ['Polish', 'Polish', 'CN0145', false, true],
            ['Portuguese', 'Portuguese', 'CN0146', false, true],
            ['Qatari', 'Qatari', 'CN0147', false, true],
            ['Reunion', 'Reunion', 'CN0148', false, true],
            ['Romanian', 'Romanian', 'CN0149', false, true],
            ['Russian', 'Russian', 'CN0150', false, true],
            ['Rwandan', 'Rwandan', 'CN0151', false, true],
            ['Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'CN0152', false, true],
            ['Saint Lucian', 'Saint Lucian', 'CN0153', false, true],
            ['Saint Lucians', 'Saint Lucian', 'CN0153', true, true],
            ['Salvadoran', 'Salvadoran', 'CN0154', false, true],
            ['Saudi', 'Saudi Arabian', 'CN0155', true, true],
            ['Saudi Arabian', 'Saudi Arabian', 'CN0155', false, true],
            ['Scottish', 'British', 'CN0032', true, true],
            ['Senegalese', 'Senegalese', 'CN0156', false, true],
            ['Serbian', 'Serbian', 'CN0157', false, true],
            ['Seychellois', 'Seychellois', 'CN0047', false, true],
            ['Sierra Leonean', 'Sierra Leonean', 'CN0158', false, true],
            ['Singaporean', 'Singaporean', 'CN0159', false, true],
            ['Slovak', 'Slovak', 'CN0160', false, true],
            ['Slovakian', 'Slovak', 'CN0160', true, true],
            ['Slovenian', 'Slovenian', 'CN0161', false, true],
            ['Somali', 'Somali', 'CN0162', false, true],
            ['South African', 'South African', 'CN0163', false, true],
            ['South Korea', 'South Korean', 'CN0164', true, true],
            ['South Korean', 'South Korean', 'CN0164', false, true],
            ['South Sudanese', 'South Sudanese', 'CN0165', false, true],
            ['Spanish', 'Spanish', 'CN0166', false, true],
            ['Sri Lankan', 'Sri Lankan', 'CN0167', false, true],
            ['St Lucian', 'Saint Lucian', 'CN0153', true, true],
            ['St.Kitts', 'Kittian and Nevisian', 'CN0101', true, true],
            ['Sudanese', 'Sudanese', 'CN0168', false, true],
            ['Swedish', 'Swedish', 'CN0169', false, true],
            ['Swiss', 'Swiss', 'CN0170', false, true],
            ['Syrian', 'Syrian', 'CN0171', false, true],
            ['Taiwanese', 'Taiwanese', 'CN0172', false, true],
            ['Tajik', 'Tajik', 'CN0173', false, true],
            ['Tanzanian', 'Tanzanian', 'CN0174', false, true],
            ['Thai', 'Thai', 'CN0175', false, true],
            ['Togolese', 'Togolese', 'CN0176', false, true],
            ['Trinidadian And Toboggan', 'Trinidadian or Tobagonian', 'CN0177', true, true],
            ['Trinidadian or Tobagonian', 'Trinidadian or Tobagonian', 'CN0177', false, true],
            ['Tunisian', 'Tunisian', 'CN0178', false, true],
            ['Turkish', 'Turkish', 'CN0179', false, true],
            ['Turkmen', 'Turkmen', 'CN0180', false, true],
            ['Ugandan', 'Ugandan', 'CN0181', false, true],
            ['Ukrainian', 'Ukrainian', 'CN0182', false, true],
            ['United Kingdom', 'British', 'CN0032', true, true],
            ['Uruguayan', 'Uruguayan', 'CN0183', false, true],
            ['Uzbek', 'Uzbekistani', 'CN0184', true, true],
            ['Uzbekistani', 'Uzbekistani', 'CN0184', false, true],
            ['Vanuatuan', 'Vanuatuan', 'CN0132', false, true],
            ['Venezuelan', 'Venezuelan', 'CN0185', false, true],
            ['Vietnamese', 'Vietnamese', 'CN0186', false, true],
            ['Virgin Islands (Usa)', 'Virgin Islands (Usa)', 'CN0187', false, true],
            ['Welsh', 'British', 'CN0032', true, true],
            ['West Indian', 'West Indian', 'CN0188', false, true],
            ['Western Saharan', 'Western Saharan', 'CN0189', false, true],
            ['Yemeni', 'Yemeni', 'CN0190', false, true],
            ['Yemenite', 'Yemeni', 'CN0190', true, true],
            ['Zambian', 'Zambian', 'CN0191', false, true],
            ['Zimbabwean', 'Zimbabwean', 'CN0192', false, true],

        ];

        foreach ($rows as $row) {
            $nationality = Nationality::where('text', $row[0])->first();

            if (! $nationality) {
                continue;
            }

            CanonicalNationality::updateOrCreate(
                [
                    'nationality_id' => $nationality?->id,
                    'canonical_nationality_code' => $row[2],
                ],
                [
                    'canonical_nationality_name' => $row[1],
                    'nationality_synonym' => $row[3],
                    'is_active' => true,
                    'effective_from' => Carbon::create(2026, 2, 2),
                    'effective_to' => Carbon::create(2099, 12, 31),
                ]
            );
        }
    }
}
