<?php

namespace Database\Seeders;

use App\Enums\InsuranceProvidersEnum;
use App\Enums\LookupsEnum;
use App\Enums\QuoteTypeId;
use App\Models\InsuranceProvider;
use App\Models\Lookup;
use App\Models\Nationality;
use App\Services\Logger\LoggerService;
use Illuminate\Database\Seeder;

class CarAdditionalDetailsForLivaSeeder extends Seeder
{
    private $insuranceProviderId;

    public function __construct()
    {
        $this->insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::RSA)
            ->select(['id', 'code'])
            ->first()->id;

        LoggerService::info(self::class.' fn: '.__FUNCTION__, extra: [
            'insurance_provider_id' => $this->insuranceProviderId,
            'insurance_provider_code' => InsuranceProvidersEnum::RSA,
        ]);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->rtaTransactionType();
        $this->rtaPlateCategory();
        $this->vehicleColor();
        $this->bankName();
        $this->annualMileageEstimate();
        $this->nationalityList();
        $this->drivingExperience();
    }

    private function rtaTransactionType()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '10',
            'text' => 'Registration of new vehicle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '20',
            'text' => 'Changing vehicle ownership (current registration valid)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '30',
            'text' => 'Changing vehicle ownership (current registration to expire)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '40',
            'text' => 'Renewal of vehicle (with current number plate)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '50',
            'text' => 'Renewal of vehicle (with new number plate)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function rtaPlateCategory()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '14',
            'text' => 'Private',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '18',
            'text' => 'Motorcycle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '39',
            'text' => 'Delegate',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '42',
            'text' => 'Consulate Authority',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '45',
            'text' => 'Classical',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '36',
            'text' => 'Dubai Flag',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function vehicleColor()
    {
        $vehicleColorList = [
            ['1', 'WHITE'],
            ['2', 'BLACK'],
            ['3', 'RED'],
            ['4', 'BLUE'],
            ['5', 'YELLOW'],
            ['6', 'GREEN'],
            ['7', 'Brown'],
            ['9', 'Bronze'],
            ['8', 'SILVER'],
            ['10', 'Gold'],
            ['11', 'ORANGE'],
            ['12', 'MAROON'],
            ['13', 'Beige'],
            ['14', 'GREY OLD'],
            ['16', 'EBONY'],
            ['20', 'ADRIATIC'],
            ['21', 'ADRIATIC BLUE'],
            ['22', 'AEGEAN BLUE'],
            ['23', 'ALABASTER BLACK'],
            ['24', 'ALABASTER GREY'],
            ['25', 'ALABASTER WHITE'],
            ['26', 'ALASKAN WHITE'],
            ['27', 'ALFA RED'],
            ['28', 'ALLOY'],
            ['29', 'ALPINE WHITE'],
            ['30', 'ALPINE WHITE METALLIC'],
            ['31', 'ALVESTON RED'],
            ['32', 'AM PURPLE/Q.SILVER'],
            ['33', 'AMBER BRONZE METALLIC'],
            ['34', 'AMBER RED'],
            ['35', 'AMETHYST GREY'],
            ['36', 'ANTIQUE GREEN'],
            ['37', 'APPLE GREEN'],
            ['38', 'AQUA'],
            ['39', 'AQUA BLUE'],
            ['40', 'AQUA METALLIC'],
            ['41', 'AQUA SILVER'],
            ['42', 'ARCTIC'],
            ['43', 'ARCTIC BLUE'],
            ['44', 'ARCTIC FROST'],
            ['45', 'ARCTIC SILVER'],
            ['46', 'ARENA RED'],
            ['47', 'AROMA RED'],
            ['48', 'ARTIC WHITE'],
            ['49', 'ASCOT GREEN'],
            ['50', 'ASH GOLD'],
            ['51', 'ASH GOLD METALLIC'],
            ['52', 'ASTLER BLUE'],
            ['53', 'ATACAMA SAND'],
            ['54', 'ATLAS GREY'],
            ['55', 'AUBERGINE'],
            ['56', 'AUTUMN BLAZE'],
            ['57', 'AUTUMN COPPER'],
            ['58', 'AZURE BLUE'],
            ['59', 'BAHIA BEIGE'],
            ['60', 'BARENTS BLUE METALLIC'],
            ['61', 'BASALT BLACK'],
            ['62', 'BASALT BLACK METALLIC'],
            ['63', 'BEIGE BLACK'],
            ['64', 'BEIGE GREY'],
            ['65', 'BEIGE METALLIC'],
            ['66', 'BEIGE MICA METALLIC'],
            ['67', 'BEIGE PEARL'],
            ['68', 'BEIGE/BLUE'],
            ['69', 'BEIGE/BROWN'],
            ['70', 'BEIGE/CASHMERE'],
            ['71', 'BEIGE/GREEN'],
            ['72', 'BEIGE/GREEN/RED'],
            ['73', 'BEIGE/GREY'],
            ['74', 'BEIGE/MAROON'],
            ['75', 'BEIGE/OLIVE GREEN'],
            ['76', 'BEIGE/RED'],
            ['77', 'BEIGE/SILVER'],
            ['78', 'BEIGE/WHITE'],
            ['79', 'BELUGA'],
            ['80', 'BIANCA WHITE'],
            ['81', 'BIARRITZ BLUE'],
            ['82', 'BILLET SILVER METALLIC'],
            ['83', 'BIZZARD'],
            ['85', 'BLACK BEIGE'],
            ['86', 'BLACK CLEARCOAT'],
            ['87', 'BLACK GREEN'],
            ['88', 'BLACK II'],
            ['89', 'BLACK JAVA'],
            ['90', 'BLACK MAROON'],
            ['91', 'BLACK MICA'],
            ['92', 'BLACK OBSIMET'],
            ['93', 'BLACK PEARL'],
            ['94', 'BLACK RAVEN'],
            ['95', 'BLACK SAPPHIRE'],
            ['96', 'BLACK SPARKLING METALLIC'],
            ['97', 'BLACK WHITE MAROON'],
            ['98', 'BLACK/BEIGE'],
            ['99', 'BLACK/BLACK'],
            ['100', 'BLACK/BLUE'],
            ['101', 'BLACK/BROWN'],
            ['102', 'BLACK/COPPER'],
            ['103', 'BLACK/EBONY'],
            ['104', 'BLACK/GOLD'],
            ['105', 'BLACK/GOLDEN'],
            ['106', 'BLACK/GREEN'],
            ['107', 'BLACK/GREY'],
            ['108', 'BLACK/IVORY'],
            ['109', 'BLACK/LEATHER TRIM'],
            ['110', 'BLACK/LIGHT BLUE'],
            ['111', 'BLACK/ORANGE'],
            ['112', 'BLACK/ORANGE/GREEN'],
            ['113', 'BLACK/RED'],
            ['114', 'BLACK/SILVER'],
            ['115', 'BLACK/WHITE'],
            ['116', 'BLACK/WHITE/BLUE'],
            ['117', 'BLACK/WHITE/ORANGE'],
            ['118', 'BLACK/YELLOW'],
            ['119', 'BLACK METALLIC'],
            ['121', 'BLUE CHIP'],
            ['122', 'BLUE COOLSILVER'],
            ['123', 'BLUE GRAPHITE'],
            ['124', 'BLUE GREEN SILVER'],
            ['125', 'BLUE GREY'],
            ['126', 'BLUE GREY SILVER'],
            ['127', 'BLUE JADE'],
            ['128', 'BLUE METALLIC'],
            ['129', 'BLUE MICA'],
            ['130', 'BLUE MYSTIC'],
            ['131', 'BLUE ORANGE'],
            ['132', 'BLUE OVER SILVER'],
            ['133', 'BLUE PEARL'],
            ['134', 'BLUE PURPLE'],
            ['135', 'BLUE RED GREY'],
            ['136', 'BLUE SILVER'],
            ['137', 'BLUE WATER'],
            ['138', 'BLUE/BEIGE'],
            ['139', 'BLUE/BEIGE/ORANGE'],
            ['140', 'BLUE/BROWN'],
            ['141', 'BLUE/GREEN'],
            ['142', 'BLUE/GREEN/WHITE'],
            ['143', 'BLUE/GREEN/YELLOW'],
            ['144', 'BLUE/GREY'],
            ['145', 'BLUE/GREY/LEAD'],
            ['146', 'BLUE/GREY/SILVER'],
            ['147', 'BLUE/GREY/YELLOW'],
            ['148', 'BLUE/LIGHT GREY'],
            ['149', 'BLUE/MILKY'],
            ['150', 'BLUE/ORANGE'],
            ['151', 'BLUE/RED'],
            ['152', 'BLUE/RED/BLACK'],
            ['153', 'BLUE/RED/GREY'],
            ['154', 'BLUE/RED/WHITE'],
            ['155', 'BLUE/SILVER'],
            ['156', 'BLUE/SILVER/GREY'],
            ['157', 'BLUE/SLATE'],
            ['158', 'BLUE/WHITE'],
            ['159', 'BLUE/YELLOW'],
            ['160', 'BLUEGREEN CRYSTAL'],
            ['161', 'BLUEISH BLACK'],
            ['162', 'BLUEISH PEARL'],
            ['163', 'BLUEISH SILVER METALLIC'],
            ['164', 'BLUISH GREEN'],
            ['165', 'BLUISH GREY'],
            ['166', 'BLUISH PEARL'],
            ['167', 'BLUISH RED'],
            ['168', 'BLUISH SILVER'],
            ['169', 'BOLD BEIGE METALLIC'],
            ['170', 'BONATTI GREY'],
            ['171', 'BORDEAUX PONTEVECCHI'],
            ['172', 'BORNITE (PURPLE)'],
            ['173', 'BORREGO BEIGE'],
            ['174', 'BOTANY BLUE'],
            ['175', 'BOTTLE GREEN'],
            ['176', 'BOULDER GREY'],
            ['177', 'BRICK RED'],
            ['178', 'BRIGHT GOLDEN'],
            ['179', 'BRIGHT GREEN'],
            ['180', 'BRIGHT PLATINUM'],
            ['181', 'BRIGHT SILVER'],
            ['182', 'BRIGHT WHITE'],
            ['183', 'BRILLIANT SILVER'],
            ['185', 'BRONZE METALLIC'],
            ['187', 'BROWN GREEN BLACK'],
            ['188', 'BROWN GREY'],
            ['189', 'BROWN SILVER'],
            ['190', 'BROWN/BEIGE'],
            ['191', 'BROWN/BLUE'],
            ['192', 'BROWN/GOLD'],
            ['193', 'BROWN/GOLDEN'],
            ['194', 'BROWN/GREEN'],
            ['195', 'BROWN/GREY'],
            ['196', 'BROWN/SILVER'],
            ['197', 'BROWN/WHITE'],
            ['198', 'BROWNISH'],
            ['199', 'BROWNISH GREY'],
            ['200', 'BUCKINGHAM BLUE'],
            ['201', 'BURGUNDY'],
            ['202', 'BURGUNDY SILVER'],
            ['203', 'BURNING RED'],
            ['204', 'BVO BEIGE'],
            ['205', 'C. GREEN'],
            ['206', 'C. GREEN PEARL'],
            ['207', 'C. RED'],
            ['208', 'C.BLUE'],
            ['209', 'C.GREY'],
            ['210', 'C.SILVER'],
            ['211', 'C.SILVER/GREY'],
            ['212', 'CAIRNS BLUE'],
            ['213', 'CALCITE WHITE'],
            ['214', 'CALYPSO RED'],
            ['215', 'CANAL BLUE'],
            ['216', 'CANARY YELLOW'],
            ['217', 'CANDY RUBY RED'],
            ['218', 'CANDY SWORD BLUE'],
            ['219', 'CANDY WHITE'],
            ['220', 'CANYON RED'],
            ['221', 'CARBON'],
            ['222', 'CARBON BLACK'],
            ['223', 'CARBON GREY'],
            ['224', 'CASABLANCA'],
            ['225', 'CASHMERE'],
            ['226', 'CASHMERE (BEIGE)'],
            ['227', 'CASHMERE METALLIC'],
            ['228', 'CASHMERE STEEL'],
            ['229', 'CELESTIAL BLUE PEARL'],
            ['230', 'CHAMPAGNE'],
            ['232', 'CHAMPAGNE GOLD'],
            ['233', 'CHAMPAGNE GREY'],
            ['234', 'CHAMPAGNE METALLIC'],
            ['235', 'CHAMPAGNE MICA'],
            ['236', 'CHAMPAGNE PEARL'],
            ['237', 'CHAMPAGNE SILVER'],
            ['238', 'CHAMPAGNE/GOLDEN'],
            ['239', 'CHAR GOLD'],
            ['240', 'CHARCOAL GREY'],
            ['241', 'CHASTE WHITE'],
            ['242', 'CHAWTON WHITE'],
            ['243', 'CHERRY BROWN'],
            ['244', 'CHERRY RED'],
            ['245', 'CHERRY WHITE'],
            ['246', 'CHINA BLUE'],
            ['247', 'CINNAMON BROWN'],
            ['248', 'CINNAMON GLAZE'],
            ['249', 'CLOVER GREEN'],
            ['250', 'COBALT BLUE'],
            ['251', 'CONCORD PURPLE'],
            ['252', 'CONE SILVER'],
            ['253', 'COOL SILVER'],
            ['254', 'COOL SILVER METALLIC'],
            ['255', 'COOL WHITE'],
            ['256', 'COPPER'],
            ['257', 'COPPER BLACK'],
            ['258', 'CORAL'],
            ['259', 'CORN YELLOW'],
            ['260', 'CREAM'],
            ['261', 'CREAM BROWN'],
            ['262', 'CREAM WHITE'],
            ['263', 'CRIMSON RED'],
            ['264', 'CRYSTAL'],
            ['265', 'CRYSTAL ICE'],
            ['266', 'CRYSTAL ICE METALLIC'],
            ['267', 'CRYSTAL ICE WHITE'],
            ['268', 'CRYSTAL SILVER'],
            ['269', 'CUBANITE SILVER'],
            ['270', 'CYAN'],
            ['271', 'CYPRUS GREEN'],
            ['272', 'D B GREY'],
            ['273', 'DARD GREEN'],
            ['274', 'DARK BEIGE'],
            ['275', 'DARK BLUE'],
            ['276', 'DARK BLUE METALLIC'],
            ['277', 'DARK BLUE MICA METAL'],
            ['278', 'DARK BLUE WHITE'],
            ['279', 'DARK BLUISH GREY'],
            ['280', 'DARK BROWN'],
            ['281', 'DARK CANDY'],
            ['282', 'DARK CHERRY'],
            ['283', 'DARK CHESTNUT'],
            ['284', 'DARK DENIM GREY'],
            ['285', 'DARK EMERALD'],
            ['286', 'DARK GARNET RED'],
            ['287', 'DARK GREEN'],
            ['288', 'DARK GREY'],
            ['289', 'DARK GREY METALLIC'],
            ['290', 'DARK GREY MICA'],
            ['291', 'DARK KAKHI'],
            ['292', 'DARK MAROON'],
            ['293', 'DARK MICA GREEN'],
            ['294', 'DARK ORANGE'],
            ['295', 'DARK RED'],
            ['296', 'DARK RED METALLIC'],
            ['297', 'DARK RED MICA'],
            ['298', 'DARK SHADOW GREY'],
            ['299', 'DARK SILVER'],
            ['300', 'DARK STONE'],
            ['301', 'DARK TORQUOISE PEARL'],
            ['302', 'DARK WHITE'],
            ['303', 'DEEP BLUE'],
            ['304', 'DEEP BLUE METALLIC'],
            ['305', 'DEEP BLUE MICA'],
            ['306', 'DEEP BLUE MIST'],
            ['307', 'DEEP LAVA RED'],
            ['308', 'DEEP NAVY'],
            ['309', 'DEEP SEA BLUE METALLIC'],
            ['310', 'DESERT MIST METALLIC'],
            ['311', 'DESERT PLATINUM'],
            ['312', 'DESERT ROCK METALLIC'],
            ['313', 'DESERT VIOLET'],
            ['314', 'DIABLO RED'],
            ['315', 'DIAMOND GRAPHITE'],
            ['316', 'DIAMOND SILVER'],
            ['317', 'DIAMOND SILVER METALLIC'],
            ['318', 'DIAMOND WHITE'],
            ['319', 'DOVE SILVER'],
            ['320', 'DRIFTWOOD METALLIC'],
            ['321', 'DUSTY GOLD'],
            ['323', 'EBONY BEIGE'],
            ['324', 'ECLIPE GREY'],
            ['325', 'EISEN GREY'],
            ['326', 'ELECTRIC SILVER'],
            ['327', 'EMBER BLACK'],
            ['328', 'EMERALD GREEN'],
            ['329', 'ENABI'],
            ['330', 'ENABI RED'],
            ['331', 'ENABI(RASPBERRY)'],
            ['332', 'ENABI/SILVER'],
            ['333', 'EPSON GREEN'],
            ['334', 'ETERNAL BLUE'],
            ['335', 'EVO BEIGE'],
            ['336', 'EVOKE'],
            ['337', 'EXEC. BLACK'],
            ['338', 'F.BEIGE'],
            ['339', 'FAIRY WHITE'],
            ['340', 'FALAN RED'],
            ['341', 'FERN WHITE'],
            ['342', 'FIRE OPAL'],
            ['343', 'FIRE OPAL(RED)'],
            ['344', 'FIRE RED'],
            ['345', 'FLAME RED'],
            ['346', 'FLASH RED'],
            ['347', 'FR BEIGE'],
            ['348', 'FRASER BEIGE'],
            ['349', 'FRESCO GREEN'],
            ['350', 'FROST BLUE'],
            ['351', 'FROZEN WHITE'],
            ['352', 'GALAXY BEIGE'],
            ['353', 'GALAXY BLACK'],
            ['354', 'GALAXY BLUE'],
            ['355', 'GALAXY CAPTIVA'],
            ['356', 'GALAXY GREY'],
            ['357', 'GALAXY METALLIC'],
            ['358', 'GALAXY SILVER'],
            ['359', 'GALAXY WHITE'],
            ['360', 'GENESIS BLUE'],
            ['361', 'GLACIER GREEN'],
            ['362', 'GLACIER WHITE/BLUE'],
            ['363', 'GLARE BEIGE'],
            ['364', 'GLAZE'],
            ['365', 'GOLD ASH'],
            ['366', 'GOLD BLACK'],
            ['367', 'GOLD METALLIC'],
            ['368', 'GOLD MICA'],
            ['369', 'GOLD MICA METALLIC'],
            ['370', 'GOLD MIST'],
            ['371', 'GOLD MIST METALLIC'],
            ['372', 'GOLD WHITE'],
            ['373', 'GOLD/BROWN'],
            ['374', 'GOLD/GREY'],
            ['375', 'GOLD/SILVER'],
            ['376', 'GOLD/WHITE'],
            ['377', 'GOLDEN'],
            ['378', 'GOLDEN BROWN'],
            ['379', 'GOLDEN GREEN'],
            ['380', 'GOLDEN GREY'],
            ['381', 'GOLDEN METALLIC'],
            ['382', 'GOLDEN YELLOW'],
            ['383', 'GOLDEN/BLACK'],
            ['384', 'GOLDEN/BLUE'],
            ['385', 'GOLDEN/BROWN'],
            ['386', 'GOLDEN/FD'],
            ['387', 'GOLDEN/GREEN'],
            ['388', 'GOLDEN/GREY'],
            ['389', 'GOLDEN/RED'],
            ['390', 'GOLDEN/SILVER'],
            ['391', 'GOLDEN/WHITE'],
            ['392', 'GRACE GREEN'],
            ['393', 'GRANADA BLACK'],
            ['394', 'GRAPE'],
            ['395', 'GRAPHITE'],
            ['396', 'GRAPHITE GREY'],
            ['397', 'GRAPHITE METALLIC'],
            ['398', 'GRAPHITE PEARL'],
            ['399', 'GRAPHITE PEARL GREY'],
            ['401', 'GREEN BLACK'],
            ['402', 'GREEN BLACK METAL'],
            ['403', 'GREEN BROWN'],
            ['404', 'GREEN BROWN BLACK'],
            ['405', 'GREEN GOLD'],
            ['406', 'GREEN METALLIC'],
            ['407', 'GREEN MICA'],
            ['408', 'GREEN ORANGE'],
            ['409', 'GREEN ORANGE WHITE'],
            ['410', 'GREEN TEA METALLIC'],
            ['411', 'GREEN VIOLET'],
            ['412', 'GREEN/BEIGE'],
            ['413', 'GREEN/BLACK'],
            ['414', 'GREEN/BLUE'],
            ['415', 'GREEN/BLUE/CREAMY'],
            ['416', 'GREEN/BLUE/YELLOW'],
            ['417', 'GREEN/BROWN'],
            ['418', 'GREEN/GOLD'],
            ['419', 'GREEN/GOLDEN'],
            ['420', 'GREEN/GREY'],
            ['421', 'GREEN/GREY/SILVER'],
            ['422', 'GREEN/LIGHT GREY'],
            ['423', 'GREEN/RED'],
            ['424', 'GREEN/RED/GREY'],
            ['425', 'GREEN/RED/SILVER'],
            ['426', 'GREEN/RED/YELLOW'],
            ['427', 'GREEN/SILVER'],
            ['428', 'GREEN/WHITE'],
            ['429', 'GREEN/WHITE/ORANGE'],
            ['430', 'GREEN/WHITE/RED'],
            ['431', 'GREEN/YELLOW'],
            ['432', 'GREEN/YELLOW/WHITE'],
            ['433', 'GREENISH'],
            ['434', 'GREENISH GREY'],
            ['435', 'GREENISH YELLOW'],
            ['436', 'GREY'],
            ['437', 'GREY ALUMINIUM'],
            ['438', 'GREY BLUE'],
            ['439', 'GREY BONATTI'],
            ['440', 'GREY GOLDEN'],
            ['441', 'GREY GREEN'],
            ['442', 'GREY MEDIUM'],
            ['443', 'GREY METALLIC'],
            ['444', 'GREY MICA METAL'],
            ['445', 'GREY MICA METALLIC'],
            ['446', 'GREY SILER'],
            ['447', 'GREY SILVER'],
            ['448', 'GREY TITANIUM'],
            ['449', 'GREY/BLACK'],
            ['450', 'GREY/BLUE'],
            ['451', 'GREY/BLUE METALLIC'],
            ['452', 'GREY/BROWN'],
            ['453', 'GREY/GREEN'],
            ['454', 'GREY/GREEN/GREY'],
            ['455', 'GREY/GREEN/YELLOW'],
            ['456', 'GREY/GREY'],
            ['457', 'GREY/ORANGE'],
            ['458', 'GREY/PURPLE'],
            ['459', 'GREY/RED'],
            ['460', 'GREY/SILVER'],
            ['461', 'GREY/SILVER/BLUE'],
            ['462', 'GREY/WHITE'],
            ['463', 'GREY/YELLOW'],
            ['464', 'GREYISH BLACK'],
            ['465', 'GREYISH BLUE'],
            ['466', 'GREYISH BLUE METALLIC'],
            ['467', 'GREYISH BROWN'],
            ['468', 'GREYISH PURPLE'],
            ['469', 'GREYISH SILVER'],
            ['470', 'GREYSILVER'],
            ['471', 'GREYSTONE METALLIC'],
            ['472', 'GRIGIO/ALFIERI'],
            ['473', 'GRYSIL'],
            ['474', 'GULF BLUE'],
            ['475', 'GUN METALLIC'],
            ['476', 'GUNMETAL'],
            ['477', 'GUNMETAL GREY'],
            ['478', 'H WHITE'],
            ['479', 'HALIBI'],
            ['480', 'HARBOUR BLUE'],
            ['481', 'HARVEST GOLD'],
            ['482', 'HEATHER MIST'],
            ['483', 'HEATHER MIST METALLIC'],
            ['484', 'HERON WHITE'],
            ['485', 'HONEY'],
            ['486', 'HUNTER GREEN'],
            ['487', 'IBIS WHITE'],
            ['488', 'ICE BLUE'],
            ['489', 'ICE BLUE METALLIC'],
            ['490', 'ICE GREEN'],
            ['491', 'ICE LAND GREY'],
            ['492', 'ICELAND GREY'],
            ['493', 'ICELANDIC BLUE'],
            ['494', 'IGNITION'],
            ['495', 'ILLUSION BLUE'],
            ['496', 'IMOLA RED'],
            ['497', 'IMOLA RED METALLIC'],
            ['498', 'IMPALA BLUE'],
            ['499', 'IMPALA BROWN'],
            ['500', 'INCA BLUE'],
            ['501', 'INDIGO'],
            ['502', 'INDIGO BLUE'],
            ['503', 'INK'],
            ['504', 'INK BLUE'],
            ['505', 'INTENSE BLUE'],
            ['506', 'INZA RED'],
            ['507', 'IRIDIUM SILVER'],
            ['508', 'IRIDIUM/GREY'],
            ['509', 'IRON GREY'],
            ['510', 'IRONY GREY'],
            ['511', 'IVORY'],
            ['512', 'IVORY PEARL'],
            ['513', 'IVORY WHITE'],
            ['514', 'IVORY/PEACH'],
            ['515', 'JADE BLACK'],
            ['516', 'JADE BLUE'],
            ['517', 'JADE GREEN'],
            ['518', 'JADE SUNGLOW'],
            ['519', 'JASPER BLUE'],
            ['520', 'JAVA BLACK'],
            ['521', 'JUMPINGWHITE'],
            ['522', 'KALAHARI BEIGE'],
            ['523', 'KASHMIR'],
            ['524', 'KASHMIR BEIGE'],
            ['525', 'KASHMIR GREY'],
            ['526', 'KASHMIRY'],
            ['527', 'KH3 BLACK'],
            ['528', 'KHAKI'],
            ['529', 'KHAKI GREEN'],
            ['530', 'LAPIS BLUE METALLIC'],
            ['531', 'LAVA GREY'],
            ['532', 'LAVA RED'],
            ['533', 'LAVA SAND'],
            ['534', 'LAVA SAND METALLIC'],
            ['535', 'LAVENDER'],
            ['536', 'LE MANS BLUE METALLIC'],
            ['537', 'LE PEWTER METALLIC'],
            ['538', 'LEAD'],
            ['539', 'LEMON YELLOW'],
            ['540', 'LIGHT AQUA'],
            ['541', 'LIGHT AQUA BLUE'],
            ['542', 'LIGHT BEIGE'],
            ['543', 'LIGHT BLUE'],
            ['544', 'LIGHT BLUE METALLIC'],
            ['545', 'LIGHT BROWN'],
            ['546', 'LIGHT FRENCH'],
            ['547', 'LIGHT GOLD'],
            ['548', 'LIGHT GOLD/BROWN'],
            ['549', 'LIGHT GOLDEN'],
            ['550', 'LIGHT GREEN'],
            ['551', 'LIGHT GREEN/GREY'],
            ['552', 'LIGHT GREY'],
            ['553', 'LIGHT GREY/RED'],
            ['554', 'LIGHT KHAKI'],
            ['555', 'LIGHT KHAKI METALLIC'],
            ['556', 'LIGHT METALLIC BLUE'],
            ['557', 'LIGHT OLIVE'],
            ['558', 'LIGHT OLIVE METALLIC'],
            ['559', 'LIGHT PLATINUM'],
            ['560', 'LIGHT RED/DARK RED'],
            ['561', 'LIGHT ROSE'],
            ['562', 'LIGHT ROSE METALLIC'],
            ['563', 'LIGHT SILVER'],
            ['564', 'LIGHT YELLOW'],
            ['565', 'LIGHT/DARK BLUE'],
            ['566', 'LIGHTPURPLE/GREY'],
            ['567', 'LIME GREEN'],
            ['568', 'LIME YELLOW'],
            ['569', 'LINEN BEIGE METALLIC'],
            ['570', 'LIQUID COPPER'],
            ['571', 'LIQUID SILVER'],
            ['572', 'LIQUID YELLOW'],
            ['573', 'LUGANO TEAL'],
            ['574', 'LUNAR GOLD'],
            ['575', 'LUNAR GOLD PEARL'],
            ['576', 'LUXURY BLACK'],
            ['577', 'LUXURY BLUE'],
            ['578', 'MAGIC BLACK'],
            ['579', 'MAGIC BLUE'],
            ['580', 'MAGIC BLUE PEARL'],
            ['581', 'MAGNESIUM GREEN'],
            ['582', 'MAGNESIUM PEARL'],
            ['583', 'MAJESTIC RED METALLIC'],
            ['584', 'MALDIVES BLUE'],
            ['586', 'MAROON BURGUNDY'],
            ['587', 'MAROON GOLDEN'],
            ['588', 'MAROON RED'],
            ['589', 'MAROON/BEIGE'],
            ['590', 'MAROON/BLACK'],
            ['591', 'MAROON/GOLDEN'],
            ['592', 'MAROON/GREY'],
            ['593', 'MAROON/RED'],
            ['594', 'MAROON/SILVER'],
            ['595', 'MAROON/WHITE'],
            ['596', 'MAROON/YELLOW'],
            ['597', 'MEDIUM GOLD METALLIC'],
            ['598', 'MEDIUM PURPLISH GREY'],
            ['599', 'MELANGE M'],
            ['600', 'MERCURY'],
            ['601', 'MERCURY RED'],
            ['602', 'MERIDIAN METALLIC'],
            ['603', 'METAL BROWN'],
            ['604', 'METAL RED'],
            ['605', 'METALLIC'],
            ['606', 'METALLIC ASH'],
            ['607', 'METALLIC BEIGE'],
            ['608', 'METALLIC BLACK'],
            ['609', 'METALLIC BLUE'],
            ['610', 'METALLIC BLUE/GOLD'],
            ['611', 'METALLIC GOLD'],
            ['612', 'METALLIC GREEN'],
            ['613', 'METALLIC GREY'],
            ['614', 'METALLIC LIGHT GREEN'],
            ['615', 'METALLIC RED'],
            ['616', 'METALLIC SILVER'],
            ['617', 'METALLIC YELLOW'],
            ['618', 'METALLIC/RED(BURGUNDY)'],
            ['619', 'METEOR GREY'],
            ['620', 'MICA BROWN'],
            ['621', 'MICA GREEN'],
            ['622', 'MICA RED'],
            ['623', 'MID GREY'],
            ['624', 'MID NIGHT BLUE'],
            ['625', 'MID SILVER METALLIC'],
            ['626', 'MIDNIGHT'],
            ['627', 'MIDNIGHT BLACK'],
            ['628', 'MIDNIGHT BLUE'],
            ['629', 'MILANO RED'],
            ['630', 'MILKY'],
            ['631', 'MILKY WHITE'],
            ['632', 'MINERAL GREY'],
            ['633', 'MIRAGE METALLIC'],
            ['634', 'MISRY GREEN'],
            ['635', 'MOCHA BLACK'],
            ['636', 'MOCHA FROST'],
            ['637', 'MOCHA METALLIC'],
            ['638', 'MOJAVE MIST METALLIC'],
            ['639', 'MONACO BLUE'],
            ['640', 'MONACO BLUE METALLIC'],
            ['641', 'MONCO BLUE'],
            ['642', 'MONTE CARLO BLUE'],
            ['643', 'MONTECHRI METAL'],
            ['644', 'MOONSTONE'],
            ['645', 'MORNING DEW'],
            ['646', 'MOSS GREEN'],
            ['647', 'MYSTIC BLUE'],
            ['648', 'N BLUE/SILVER'],
            ['649', 'NAPLE GOLD'],
            ['650', 'NAPLE GOLD M'],
            ['651', 'NATURAL KHAKI'],
            ['652', 'NAUTIC BLUE'],
            ['653', 'NAVY'],
            ['654', 'NAVY BLUE'],
            ['655', 'NAVY/SILVER'],
            ['656', 'NERO'],
            ['657', 'NETTUNO BLUE'],
            ['658', 'NEUTRON BLUE'],
            ['659', 'NEW RED M M'],
            ['660', 'NICKEL'],
            ['661', 'NIGHT BLACK'],
            ['662', 'NIGHTHAWK BLACK'],
            ['663', 'NOBLE GREEN'],
            ['664', 'NOBLE WHITE'],
            ['665', 'NOIROBSI METAL'],
            ['666', 'NORSEA BLUE'],
            ['667', 'NULL'],
            ['668', 'OBSIDIAN BLACK'],
            ['669', 'ODYSSEY'],
            ['670', 'ODYSSEY (BLUE)'],
            ['671', 'OFF WHITE'],
            ['672', 'OLIVE'],
            ['673', 'OLIVE BEIGE'],
            ['674', 'OLIVE GREEN'],
            ['675', 'OLIVE SILVER'],
            ['676', 'OLIVE/BEIGE'],
            ['677', 'ONYX BLACK'],
            ['678', 'OPAL'],
            ['679', 'OPAL BLACK'],
            ['680', 'OPAL BROWN'],
            ['682', 'ORANGE BEIGE'],
            ['683', 'ORANGE BLACK'],
            ['684', 'ORANGE RED'],
            ['685', 'ORANGE SILVER'],
            ['686', 'ORANGE/BLACK'],
            ['687', 'ORANGE/BLUE'],
            ['688', 'ORANGE/CREAM'],
            ['689', 'ORANGE/GREEN'],
            ['690', 'ORANGE/GREEN/BLACK'],
            ['691', 'ORANGE/GREY'],
            ['692', 'ORANGE/GREY/BLUE'],
            ['693', 'ORANGE/LIGHT GREY'],
            ['694', 'ORANGE/RED'],
            ['695', 'ORANGE/SILVER'],
            ['696', 'ORANGE/WHITE'],
            ['697', 'ORANGE/WHITE/BLACK'],
            ['698', 'ORIANT BLUE'],
            ['699', 'ORINOCO'],
            ['700', 'ORION GREEN'],
            ['701', 'OSLO BLUE'],
            ['702', 'ZDONOTUSEOTHERS'],
            ['703', 'OXFORD BLUE'],
            ['704', 'OXFORD GREEN'],
            ['705', 'OXFORD WHITE'],
            ['706', 'OYSTER'],
            ['707', 'PACIFIC BLUE'],
            ['708', 'PALE YELLOW'],
            ['709', 'PANTHER BLACK'],
            ['710', 'PARCHMENT'],
            ['711', 'PARPEL'],
            ['712', 'PASTEL BLUE'],
            ['713', 'PATRIOT BLUE'],
            ['714', 'PEACH'],
            ['715', 'PEARL'],
            ['716', 'PEARL BEIGE'],
            ['717', 'PEARL BLACK'],
            ['718', 'PEARL BLUE'],
            ['719', 'PEARL GREY'],
            ['720', 'PEARL RED SILVER'],
            ['721', 'PEARL SILVER'],
            ['722', 'PEARL WHITE'],
            ['723', 'PEARL WHITE/BEIGE'],
            ['724', 'PEARL/WHITE'],
            ['725', 'PERLITE GREY'],
            ['726', 'PEWTER'],
            ['816', 'ROSSO CORSA/RED'],
            ['817', 'ROYAL BLUE'],
            ['818', 'ROYAL RED'],
            ['819', 'ROYAL RUBY RED'],
            ['820', 'RUBY BLACK METALLIC'],
            ['821', 'RUBY RED'],
            ['822', 'S BLUE/COOL SILVER'],
            ['823', 'S D F'],
            ['824', 'S GRAPHITE'],
            ['825', 'S. SILVER'],
            ['826', 'S.GREY'],
            ['827', 'S.SILVER'],
            ['828', 'S.WHITE'],
            ['829', 'S.WHITE/C.SILVER'],
            ['830', 'SABLE MICA METALLIC'],
            ['831', 'SAFFRON'],
            ['832', 'SAGE BRUSH PEARL'],
            ['833', 'SAHARA BEIGE'],
            ['834', 'SALOON'],
            ['835', 'SAMOA BLUE'],
            ['836', 'SAND'],
            ['837', 'SAND BEIGE'],
            ['838', 'SAND BROWN'],
            ['839', 'SAND GREY'],
            ['840', 'SAND METALLIC'],
            ['841', 'SAND WHITE'],
            ['842', 'SANDAL WOOD'],
            ['843', 'SANDSTONE'],
            ['844', 'SANDSTORM'],
            ['845', 'SANDY BEIGE'],
            ['846', 'SANIDINE BEIGE'],
            ['847', 'SAPPHIRE BLACK'],
            ['848', 'SARDSTONE'],
            ['849', 'SAT. SILVER'],
            ['850', 'SATELLITE SILVER'],
            ['851', 'SATIN GOLD'],
            ['852', 'SATIN MEISAI'],
            ['853', 'SATIN SILVER'],
            ['854', 'SCANDIUM GREY PEARL'],
            ['855', 'SCARABEE'],
            ['856', 'SCOTIA WHITE'],
            ['857', 'SEA GREEN'],
            ['858', 'SEA GREY'],
            ['859', 'SHADOW GREEN'],
            ['860', 'SHELL METALLIC'],
            ['861', 'SHINING RED'],
            ['862', 'SHORELINE MIST'],
            ['863', 'SHORELINE MIST METALLIC'],
            ['864', 'SIDOBRE GREY'],
            ['865', 'SIDOBRE GREY METALLIC'],
            ['866', 'SIENNA PEARL COAT'],
            ['868', 'SILVER BLUE'],
            ['869', 'SILVER ARCADIA'],
            ['870', 'SILVER BEIGE'],
            ['871', 'SILVER BIRCH'],
            ['873', 'SILVER BRICH'],
            ['874', 'SILVER BROWN'],
            ['875', 'SILVER BULLET GREY'],
            ['876', 'SILVER GRAPHITE'],
            ['877', 'SILVER GREY'],
            ['878', 'SILVER GREY METALLIC'],
            ['879', 'SILVER IVORY'],
            ['880', 'SILVER LEAF'],
            ['881', 'SILVER M.GR'],
            ['882', 'SILVER M.M'],
            ['883', 'SILVER MARBLE'],
            ['884', 'SILVER METALLIC'],
            ['885', 'SILVER METALLIC GRAPHITE'],
            ['886', 'SILVER METTALIC'],
            ['887', 'SILVER MICA METALLIC'],
            ['888', 'SILVER ORANGE'],
            ['889', 'SILVER SAND'],
            ['890', 'SILVER STEEL'],
            ['891', 'SILVER STONE'],
            ['892', 'SILVER/BEIGE'],
            ['893', 'SILVER/BLACK'],
            ['894', 'SILVER/BLUE'],
            ['895', 'SILVER/BLUE/YELLOW'],
            ['896', 'SILVER/BROWN'],
            ['897', 'SILVER/GOLDEN'],
            ['898', 'SILVER/GREEN'],
            ['899', 'SILVER/GREY'],
            ['900', 'SILVER/GREY/BLUE'],
            ['901', 'SILVER/MB TEX'],
            ['902', 'SILVER/ORANGE'],
            ['903', 'SILVER/PURPLE'],
            ['904', 'SILVER/RED'],
            ['905', 'SILVER/WHITE'],
            ['906', 'SILVER/WHITE/SILVER'],
            ['907', 'SILVER/YELLOW'],
            ['908', 'SILVERSTONE METALLIC'],
            ['909', 'SKY BLUE'],
            ['910', 'SMOKE'],
            ['911', 'SMOKE BEIGE'],
            ['912', 'SMOKE GREY'],
            ['913', 'SMOKE GREY METALLIC'],
            ['914', 'SMOKE SILVER'],
            ['915', 'SOLAR FLARE METALLIC'],
            ['916', 'SOLID WHITE'],
            ['917', 'SOPHIA WHITE'],
            ['918', 'SP GRAP'],
            ['919', 'SPACE GREY'],
            ['920', 'SPACE GREY METALLIC'],
            ['921', 'SPACE SILVER'],
            ['922', 'SPARKLE RED'],
            ['923', 'SPARKLG GRAPHITE'],
            ['924', 'SPARKLING GRAPHITE'],
            ['925', 'SPARKLING GRAPHITE METALLIC'],
            ['926', 'SPARKLING SILVER'],
            ['927', 'SPEED YELLOW'],
            ['928', 'SPORT RED'],
            ['929', 'STAHL GREY'],
            ['930', 'STANDARD RED'],
            ['931', 'STARDUST SILVER'],
            ['932', 'STEALTH GREY'],
            ['933', 'STEEL'],
            ['934', 'STEEL BLUE'],
            ['935', 'STEEL GREEN'],
            ['936', 'STEEL GREY'],
            ['937', 'STEEL GREY METALLIC'],
            ['938', 'STEEL/GREY'],
            ['939', 'STELLITE BRONZE'],
            ['940', 'STERLING GREY'],
            ['941', 'STONE GREEN'],
            ['942', 'STONE GREEN W/CAMEL'],
            ['943', 'STONE GREY METALLIC'],
            ['944', 'STONE WHITE'],
            ['945', 'STORM GREY'],
            ['946', 'STORNOWAY GREY'],
            ['947', 'STORNOWAY GREY METALLIC'],
            ['948', 'SUMMIT WHITE'],
            ['949', 'SUNNY YELLOW'],
            ['950', 'SUNSET BLUE'],
            ['951', 'SUNSET ORANGE'],
            ['952', 'SUPER RED'],
            ['953', 'SUPER SILVER'],
            ['954', 'SUPER WHITE'],
            ['955', 'SUPERIOR BLUE METALLIC'],
            ['956', 'T. BEIGE'],
            ['957', 'T. BLUE'],
            ['958', 'T. RED'],
            ['959', 'T.B.A.'],
            ['960', 'T.BLUE'],
            ['961', 'T/RED'],
            ['962', 'TAFFETA WHITE'],
            ['963', 'TAN'],
            ['964', 'TANGO ORANGE'],
            ['965', 'TANSANITE BLUE'],
            ['966', 'TAUPE FROS'],
            ['967', 'TBA'],
            ['968', 'TE. BLUE'],
            ['969', 'THUNDER GREY'],
            ['970', 'TIARA WHITE'],
            ['971', 'TIMBER GREEN'],
            ['972', 'TITANIUM'],
            ['973', 'TITANIUM (BEIGE)'],
            ['974', 'TITANIUM GREY'],
            ['975', 'TITANIUM GREY PEARL'],
            ['976', 'TITANIUM METALLIC'],
            ['977', 'TITANIUM PEARL'],
            ['978', 'TITANIUM RED'],
            ['979', 'TITANIUM SILVER'],
            ['980', 'TIVOLI BLUE'],
            ['981', 'TOLEDO BLUE'],
            ['982', 'TONGA GREEN'],
            ['983', 'TONIC'],
            ['984', 'TONIC LIGHT BLUE'],
            ['985', 'TOPAZ'],
            ['986', 'TOPAZ BLUE'],
            ['987', 'TOREADOR'],
            ['988', 'TR.BEIGE'],
            ['989', 'TRAVERTINE BEIGE'],
            ['990', 'TURQOISE GREEN'],
            ['991', 'TURQUOISE'],
            ['992', 'TURQUOISE METALLIC'],
            ['993', 'TUSCAN RED'],
            ['994', 'ULTRAVIOLET'],
            ['995', 'UNITED GREY'],
            ['996', 'URBAN GREY'],
            ['997', 'VELOCITY RED'],
            ['998', 'VELOCITY YELLOW TINT'],
            ['1000', 'VERDANT (GREEN)'],
            ['1001', 'VESPERS'],
            ['1002', 'VICTORY RED'],
            ['1003', 'VICTORY RED PRIMARY'],
            ['1004', 'VINTAGE GREEN'],
            ['1005', 'VIOLET'],
            ['1006', 'VIOLET/BLUE'],
            ['1007', 'VIOLET/SILVER'],
            ['1008', 'VISTA BLUE'],
            ['1009', 'VITRO'],
            ['1010', 'VIVID BLACK'],
            ['1011', 'WARM WHITE MICA'],
            ['1012', 'WARM WHITE PEARL'],
            ['1013', 'WARM WHITEPEARL/BEIGE'],
            ['1014', 'WHEAT BEIGE'],
            ['1016', 'WHITE ALU METALLIC'],
            ['1017', 'WHITE ALUMINIUM'],
            ['1018', 'WHITE CHAWTON'],
            ['1019', 'WHITE DIAMOND'],
            ['1020', 'WHITE GOLDEN'],
            ['1021', 'WHITE GREEN'],
            ['1022', 'WHITE GREY'],
            ['1023', 'WHITE METALLIC'],
            ['1024', 'WHITE MICA'],
            ['1025', 'WHITE PEARL'],
            ['1026', 'WHITE PEARL CRYSTAL'],
            ['1027', 'WHITE PEARL METALLIC'],
            ['1028', 'WHITE SILVER'],
            ['1029', 'WHITE SILVER METALLIC'],
            ['1030', 'WHITE SOLID'],
            ['1031', 'WHITE SUEDE'],
            ['1032', 'WHITE/ DARK GREY'],
            ['1033', 'WHITE/BEIGE'],
            ['1034', 'WHITE/BLACK'],
            ['1035', 'WHITE/BLACK/RED'],
            ['1036', 'WHITE/BLACK/SILVER'],
            ['1037', 'WHITE/BLUE'],
            ['1038', 'WHITE/BLUE/ORANGE'],
            ['1039', 'WHITE/BLUE/PINK'],
            ['1040', 'WHITE/BLUE/RED'],
            ['1041', 'WHITE/BLUE/YELLOW'],
            ['1042', 'WHITE/BLUISH SILVER'],
            ['1043', 'WHITE/BROWN'],
            ['1044', 'WHITE/DARK BLUE'],
            ['1045', 'WHITE/GOLD'],
            ['1046', 'WHITE/GOLDEN'],
            ['1047', 'WHITE/GREEN'],
            ['1048', 'WHITE/GREEN/BLUE'],
            ['1049', 'WHITE/GREEN/RED'],
            ['1050', 'WHITE/GREEN/YELLOW'],
            ['1051', 'WHITE/GREY'],
            ['1052', 'WHITE/L.TURQUOISE'],
            ['1053', 'WHITE/LEAD'],
            ['1054', 'WHITE/LIGHT GREEN'],
            ['1055', 'WHITE/LIGHT GREY'],
            ['1056', 'WHITE/LIGHTGREY'],
            ['1057', 'WHITE/MAROON'],
            ['1058', 'WHITE/MAROON/BLACK'],
            ['1059', 'WHITE/OGANGE/GREY'],
            ['1060', 'WHITE/ORANGE'],
            ['1061', 'WHITE/ORANGE/GREY'],
            ['1062', 'WHITE/ORANGE/SLVER'],
            ['1063', 'WHITE/PEARL'],
            ['1064', 'WHITE/RED'],
            ['1065', 'WHITE/RED/BEIGE'],
            ['1066', 'WHITE/RED/BLACK'],
            ['1067', 'WHITE/RED/BLUE'],
            ['1068', 'WHITE/RED/GREEN'],
            ['1069', 'WHITE/RED/GREY'],
            ['1070', 'WHITE/RED/SILVER'],
            ['1071', 'WHITE/RED/YELLOW'],
            ['1072', 'WHITE/SILVER'],
            ['1073', 'WHITE/SILVER/BLACK'],
            ['1074', 'WHITE/YELLOW'],
            ['1075', 'WHITE/YELLOW/BLUE'],
            ['1076', 'WHITE/YELLOW/PURPLE'],
            ['1077', 'WHITE/YELLOW/RED'],
            ['1078', 'WHITEPEARL'],
            ['1079', 'WHITESOLID SILVER'],
            ['1080', 'WHITESOLID/C SILVER'],
            ['1081', 'WHITISH GREY'],
            ['1082', 'WILLOW'],
            ['1083', 'WILLOW GREEN'],
            ['1084', 'WILLOW METALLIC'],
            ['1085', 'WINE'],
            ['1086', 'WINE RED'],
            ['1087', 'WINTER GOLD'],
            ['1089', 'YELLOW BLACK ORANGE'],
            ['1090', 'YELLOW BLUE GREEN'],
            ['1091', 'YELLOW BROWN'],
            ['1092', 'YELLOW GREEN'],
            ['1093', 'YELLOW MILKY'],
            ['1094', 'YELLOW PEARL'],
            ['1095', 'YELLOW SUGAR'],
            ['1096', 'YELLOW WHITE BLACK'],
            ['1097', 'YELLOW/BLACK'],
            ['1098', 'YELLOW/BLACK/BLUE'],
            ['1099', 'YELLOW/BLUE'],
            ['1100', 'YELLOW/BLUE/GREEN'],
            ['1101', 'YELLOW/BLUE/GREY'],
            ['1102', 'YELLOW/BLUE/SILVER'],
            ['1103', 'YELLOW/GOLD'],
            ['1104', 'YELLOW/GREEN'],
            ['1105', 'YELLOW/GREEN/BLUE'],
            ['1106', 'YELLOW/GREEN/GREY'],
            ['1107', 'YELLOW/GREY'],
            ['1108', 'YELLOW/GREY/BLUE'],
            ['1109', 'YELLOW/GREY/GREEN'],
            ['1110', 'YELLOW/LIGHT GREY'],
            ['1111', 'YELLOW/LIGHT SILVER'],
            ['1112', 'YELLOW/RED'],
            ['1113', 'YELLOW/RED/BLUE'],
            ['1114', 'YELLOW/RED/SILVER'],
            ['1115', 'YELLOW/RED/WHITE'],
            ['1116', 'YELLOW/SILVER'],
            ['1117', 'YELLOW/WHITE'],
            ['1118', 'YELLOWISH GREEN'],
            ['1119', 'Z SILVER'],
            ['1120', 'ZEST BROWN METALLIC'],
            ['1121', 'ZINC'],
            ['1122', 'ZIRCON BLUE'],
            ['1123', 'GREYISH BROWN METALLIC'],
            ['1124', 'BOURNVILLE'],
            ['1125', 'SMOKESTONE'],
            ['1126', 'DESERT STONE'],
            ['1127', 'DARK INDIGO'],
            ['1128', 'WHITE/BLACK/YELLOW'],
            ['1130', 'BLUE/SILVER/BLACK'],
            ['1132', 'METALLIC OYSTER GREY PEARL'],
            ['1133', 'CATTLEYA'],
            ['1134', 'BLACK CHERRY'],
            ['1135', 'IMPERIAL BLUE'],
            ['1136', 'PEARL GREEN'],
            ['1137', 'CASHMERE SILVER'],
            ['1138', 'SAHARA TAN CLEAR COAT'],
            ['1139', 'BRILLIANT BLACK'],
            ['1140', 'SILVER ALLOY'],
            ['1141', 'AMATHAYEST'],
            ['1142', 'YELLOW WHITE'],
            ['1143', 'Night Mist'],
            ['1144', 'Metalic Grey / Silver'],
            ['1145', 'Orange/Red/Black'],
            ['1146', 'Mocha Steel'],
            ['1147', 'Blackish Red'],
            ['1148', 'Dark Sapphire'],
            ['1149', 'Grey/Maroon'],
            ['1150', 'Ginger Ale Metallic'],
            ['1151', 'CAVIAR'],
            ['1152', 'Red/Black/Silver'],
            ['1153', 'SILVER/GREEN/BROWN'],
            ['1154', 'Black/Red/Grey'],
            ['1155', 'GRAY/BLACK/RED'],
            ['1156', 'Orkney Grey'],
            ['1157', 'MAGNESIUM BLACK'],
            ['1158', 'STERLING GREY / BLUE'],
            ['1159', 'ORANGE/BROWN'],
            ['1160', 'IPANEMA SAND'],
            ['1161', 'GLACIER'],
            ['1162', 'WHITE/BLUE/BLACK'],
            ['1163', 'BEIGE/MAROON/BLACK'],
            ['1165', 'AMBER'],
            ['1166', 'Yellow/Orange/Red'],
            ['1167', 'BAROSSA'],
            ['1168', 'SANDSTONE PEARL'],
            ['1169', 'Granite Crystal'],
            ['1170', 'Diamond Black Silver'],
            ['1171', 'Red Velvet/Silver Sand'],
            ['1172', 'Magnetic'],
            ['1173', 'SPARKLING STORM'],
            ['1174', 'Black/Blue/Grey'],
            ['1175', 'SMOKED TOPAZ'],
            ['1176', 'UMBER'],
            ['1177', 'ALABASTER SILVER'],
            ['1178', 'PALLADIUM'],
            ['1179', 'PALLADIUM METALLIC'],
            ['1180', 'SONIC QUARTZ'],
            ['1182', 'Salamanca blue/Silver'],
            ['1183', 'SONIC TITANIUM'],
            ['1184', 'MATTE BLACK'],
            ['1185', 'SATIN STEEL METALLIC'],
            ['1186', 'BLACK/YELLOW/SILVER'],
            ['1187', 'BLUE/GOLD'],
            ['1188', 'BEIGE/BROWN/ORANGE'],
            ['1189', 'CHROME/BLACK'],
            ['1190', 'White Pink'],
            ['1191', 'Green/Black/Beige'],
            ['1192', 'Gold Beige'],
            ['1193', 'SILVER/RED/GRAY'],
            ['1195', 'VIOLET/BLACK'],
            ['1196', 'BLUE/VIOLET/BLACK'],
            ['1197', 'MAGNETIC WITH BLACK/SILVER/RED'],
            ['1198', 'BIKINI PEARL COAT'],
            ['1199', 'MOCHA ALMOND'],
            ['1200', 'WHITE/BLACK/GREEN'],
            ['1202', 'Grey/Black/silver'],
            ['1203', 'Black Gray Yellow'],
            ['1204', 'GRAPHITE BLACK'],
            ['1205', 'Smokey Quartz metallic'],
            ['1206', 'Deep Crystal Blue'],
            ['1207', 'LAGOON BLUE'],
            ['1208', 'Lunar Silver'],
            ['1209', 'SOLID BLACK'],
            ['1211', 'Granite Crystal Metalic Clear'],
            ['1212', 'TWO TONE SMOKY BLUE 2LS'],
            ['1213', 'ESSENCE BROWN'],
            ['1215', 'GRAPHITE SHADOW'],
            ['1216', 'DARK KNIGHT'],
            ['1217', 'WHITE/CEMENT GREY'],
            ['1219', 'BLACK/BLUE/YELLOW'],
            ['1220', 'Gray/Violet'],
            ['1221', 'LEAD BLACK'],
            ['1222', 'Grey/white/black'],
            ['1223', 'Charente Grey'],
            ['1224', 'Manhattan Metallic Matt'],
            ['1225', 'ORANGE/YELLOW'],
            ['1226', 'ZIRCON SAND'],
            ['1227', 'FUJI WHITE'],
            ['1228', 'Diamond Black Crystal Pearl'],
            ['1229', 'CODE ORANGE'],
            ['1230', 'Orange/Black/Silver'],
            ['1231', 'Velvet Red Pearl'],
            ['1233', 'Magnesium Metallic'],
            ['1234', 'Gray Black'],
            ['1235', 'Yellow/Beige'],
            ['1236', 'Aluminum/Black/Grey/White/Silver'],
            ['1237', 'Crayon'],
            ['1238', 'Black/Green/Silver'],
            ['1239', 'Maroon Blue'],
            ['1240', 'Earthy Brass Metallic'],
            ['1241', 'Ultra Red Paint'],
            ['1242', 'Racing Red'],
            ['1243', 'Crystal White Pearl Metallic'],
            ['1244', 'CREAMY WHITE-BLACK'],
            ['1245', 'Midnight Cherry Red'],
            ['1246', 'Radiant White'],
            ['1248', 'Green/Black/Blue'],
            ['1249', 'Gondwana Stone'],
        ];

        foreach ($vehicleColorList as $color) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $color[0],
                'text' => $color[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function bankName()
    {
        $banks = [
            ['51155', 'gargash-enterprises', 'Gargash Enterprises'],
            ['51005', 'emirates-bank', 'Emirates Bank'],
            ['51006', 'citibank', 'Citibank'],
            ['51158', 'the-petroleum-institute-of-abu-dhabi', 'The Petroleum Institute Of Abu Dhabi'],
            ['51084', 'etisalat', 'Etisalat'],
            ['51152', 'al-khaliji-france', 'Al Khaliji France'],
            ['51022', 'arab-african-international-bank', 'Arab African International Bank'],
            ['51090', 'sharjah-islamic-bank', 'Sharjah Islamic Bank'],
            ['51093', 'liberty-automobiles-co-llc', 'Liberty Automobiles Co. Llc'],
            ['51107', 'abu-dhabi-investment-authority', 'Abu Dhabi Investment Authority'],
            ['51119', 'takreer-abu-dhabi-oil-refining-company', 'Takreer (Abu Dhabi Oil Refining Company)'],
            ['51124', 'emirates-airlines-or-hsbc-mefco', 'Emirates Airlines &/Or Hsbc Mefco'],
            ['51134', 'ajman-bank', 'Ajman Bank'],
            ['51145', 'adnoc', 'Adnoc'],
            ['51138', 'al-badr-islamic-finance-company', 'Al Badr Islamic Finance Company'],
            ['51163', 'emirates-motor-company', 'Emirates Motor Company'],
            ['51173', 'commercial-bank-international', 'Commercial Bank International'],
            ['51167', 'emirates-nuclear-energy-corporation', 'Emirates Nuclear Energy Corporation'],
            ['51169', 'al-futtaim-finance-company', 'Al Futtaim Finance Company'],
            ['99934', 'abu-dhabi-commercial-islamic-finance', 'Abu Dhabi Commercial Islamic Finance'],
            ['51185', 'ruby-diamond-investments-limited', 'Ruby Diamond Investments Limited'],
            ['51127', 'emirates-airlines-national-bank-of-dubai', 'Emirates Airlines / National Bank Of Dubai'],
            ['99910', 'bahrain-house-finance', 'Bahrain House Finance'],
            ['99946', 'al-futtaim-finance', 'AL FUTTAIM FINANCE'],
            ['99932', 'noor-islamic-bank', 'Noor Islamic Bank'],
            ['60092', 'inter-emirates-motors-sole-proprietorship-llc', 'INTER EMIRATES MOTORS SOLE PORPRIETORSHIP LLC'],
            ['99950', 'el-nilein-bank', 'EL NILEIN BANK'],
            ['51040', 'bnp-paribas', 'Bnp Paribas'],
            ['51099', 'doha-bank', 'Doha Bank'],
            ['51003', 'standard-chartered-bank', 'Standard Chartered Bank'],
            ['51009', 'habib-bank', 'Habib Bank'],
            ['51012', 'dubai-commercial-bank', 'Dubai Commercial Bank'],
            ['99908', 'emirates-money', 'Emirates Money'],
            ['51030', 'bank-of-sharjah', 'Bank Of Sharjah'],
            ['51038', 'banque-paribas', 'Banque Paribas'],
            ['51039', 'barclays-bank-plc', 'Barclays Bank Plc'],
            ['51075', 'deutsche-bank-ag', 'Deutsche Bank Ag'],
            ['51079', 'national-bank-of-sharjah', 'National Bank Of Sharjah'],
            ['51139', 'duniatrade', 'Duniatrade'],
            ['51095', 'hsbc-amanah', 'Hsbc Amanah'],
            ['51102', 'al-habtoor-motors-co-llc', 'Al Habtoor Motors Co Llc'],
            ['51116', 'maf-orix-finance-pjsc', 'Maf Orix Finance Pjsc'],
            ['51121', 'dynatrade', 'Dynatrade'],
            ['51141', 'emirates-airlines-or-emirates-islamic-bank', 'Emirates Airlines &/Or Emirates Islamic Bank'],
            ['51142', 'yaseer-car-rental', 'Yaseer Car Rental'],
            ['51143', 'gargash-motors', 'Gargash Motors'],
            ['51174', 'mashreq-al-islami', 'Mashreq Al Islami'],
            ['60068', 'oasis-enterprises-llc', 'Oasis Enterprises Llc'],
            ['51176', 'emirates-airlines-emirates-nbd', 'Emirates Airlines / Emirates Nbd'],
            ['60067', 'al-buhaira-national-insurance-co-abnic', 'Al Buhaira National Insurance Co (Abnic)'],
            ['51170', 'aafaq-islamic-finance-company', 'Aafaq Islamic Finance Company'],
            ['51182', 'bmw-albatha-finance', 'BMW Albatha Finance'],
            ['51187', 'tamweel', 'Tamweel'],
            ['51190', 'hsbc', 'HSBC'],
            ['51199', 'belhasa-motors', 'Belhasa Motors'],
            ['51135', 'al-khoory-automobile-llc', 'Al Khoory Automobile Llc'],
            ['51034', 'banque-banorabe', 'Banque Banorabe'],
            ['51037', 'banque-nationale-de-paris', 'Banque Nationale De Paris'],
            ['51047', 'emirates-national-bank', 'Emirates National Bank'],
            ['51073', 'core-states-bank', 'Core States Bank'],
            ['51120', 'trading-enterprises', 'Trading Enterprises'],
            ['99906', 'advanced-technology-investment-company-atic', 'Advanced Technology Investment Company (Atic)'],
            ['51010', 'habib-bank-ag-zurich', 'Habib Bank Ag Zurich'],
            ['51011', 'abu-dhabi-commercial-bank', 'Abu Dhabi Commercial Bank'],
            ['51013', 'national-bank-of-abu-dhabi', 'National Bank Of Abu Dhabi'],
            ['51018', 'alahli-bank-of-kuwait', 'Alahli Bank Of Kuwait'],
            ['51019', 'american-express', 'American Express'],
            ['51024', 'arab-bank', 'Arab Bank'],
            ['51060', 'rak-bank', 'RAK Bank'],
            ['51070', 'bank-of-bahrain-kuwait', 'Bank Of Bahrain & Kuwait'],
            ['51082', 'uae-central-bank', 'U.A.E. Central Bank'],
            ['51133', 'royal-bank-of-scotland', 'Royal Bank Of Scotland'],
            ['51137', 'al-ghandi-auto', 'Al Ghandi Auto'],
            ['51115', 'gulf-finance-corporation', 'Gulf Finance Corporation'],
            ['51122', 'emirates-dnata', 'Emirates / Dnata'],
            ['51125', 'emirates-airlines-or-lloyds-tsb-bank-plc', 'Emirates Airlines &/Or Lloyds Tsb Bank Plc'],
            ['51085', 'mawarid-finance', 'Mawarid Finance'],
            ['51153', 'emirates-money-consumer-finance-1', 'Emirates Money Consumer Finance'],
            ['51148', 'emirates-money-consumer-finance-2', 'Emirates Money Consumer Finance'],
            ['51179', 'commercial-bank-of-dubai-attijari-al-islami', 'Commercial Bank Of Dubai - Attijari Al Islami'],
            ['51180', 'al-hail-orix-finance', 'Al Hail Orix Finance'],
            ['51200', 'al-rostamani-trading-company-llc', 'Al Rostamani Trading Company LLC'],
            ['99937', 'mdc-business-management-services', 'MDC Business Management Services'],
            ['51184', 'national-auto', 'National Auto'],
            ['99935', 'first-abu-dhabi-bank', 'FIRST ABU DHABI BANK'],
            ['51194', 'blom-bank-france', 'Blom Bank France'],
            ['51149', 'ajman-bank-2', 'Ajman Bank'],
            ['51089', 'dnata', 'Dnata'],
            ['99947', 'al-futtaim-finance-pvjsc', 'AL FUTTAIM FINANCE PVJSC'],
            ['60091', 'mohamed-abdulrahman-al-bahar-llc', 'Mohamed Abdulrahman Al-Bahar LLC'],
            ['100002', 'nawah-energy', 'Nawah Energy'],
            ['60088', 'gb-equipment-solutions-llc-dubai', 'GB Equipment solutions LLC, Dubai'],
            ['60093', 'al-habtoor-royal-car-llc', 'Al Habtoor Royal Car LLC'],
            ['51026', 'banca-commerciale-italiana', 'Banca Commerciale Italiana'],
            ['51045', 'dubai-bank', 'Dubai Bank'],
            ['51052', 'invest-bank', 'Invest Bank'],
            ['51054', 'lloyds-tsb-bank', 'Lloyds TSB Bank'],
            ['51059', 'rafidain-bank', 'Rafidain Bank'],
            ['51071', 'banque-indosuez', 'Banque Indosuez'],
            ['51104', 'al-nabooda-automobiles-llc', 'Al Nabooda Automobiles Llc'],
            ['51014', 'sharjah-bank', 'Sharjah Bank'],
            ['51023', 'arab-bank-for-investment-foreign-trade', 'Arab Bank For Investment & Foreign Trade'],
            ['51028', 'bank-of-baroda', 'Bank Of Baroda'],
            ['51049', 'hamid-bank-limited', 'Hamid Bank Limited'],
            ['51055', 'middle-east-bank', 'Middle East Bank'],
            ['51056', 'natexis-banques-populaires', 'Natexis Banques Populaires'],
            ['51063', 'union-national-bank', 'Union National Bank'],
            ['51072', 'cedel-bank', 'Cedel Bank'],
            ['51140', 'dunia-finance', 'Dunia Finance'],
            ['51160', 'attijari-al-islami', 'Attijari Al Islami'],
            ['99911', 'abudhabi-future-energy-company', 'Abudhabi Future Energy Company'],
            ['51100', 'al-yousuf-llc', 'Al Yousuf Llc'],
            ['51105', 'adma-opco', 'Adma Opco'],
            ['51108', 'noor-bank-1', 'Noor Bank'],
            ['51112', 'blc-bank', 'Blc Bank'],
            ['51113', 'blom-bank', 'Blom Bank'],
            ['51147', 'gargash-enterprises-llc', 'Gargash Enterprises Llc'],
            ['51161', 'borouge-abu-dhabi-polymers-co-ltd', 'Borouge Abu Dhabi Polymers Co Ltd'],
            ['51131', 'al-hilal-bank', 'Al Hilal Bank'],
            ['99913', 'arabian-gulf-mechanical-centre', 'Arabian Gulf Mechanical Centre'],
            ['51171', 'mubadala-ge-capital-pjsc', 'Mubadala Ge Capital P.J.S.C'],
            ['99933', 'bmw-albatha-finance-2', 'BMW Albatha Finance'],
            ['51197', 'al-shirawi-enterprises-llc', 'AL SHIRAWI ENTERPRISES LLC'],
            ['99912', 'afge-money', 'Afge Money'],
            ['51130', 'al-noor-islamic-bank', 'Al Noor Islamic Bank'],
            ['51165', 'emirates-investment-authority', 'Emirates Investment Authority'],
            ['51177', 'al-majid-motors', 'Al Majid Motors'],
            ['51057', 'national-bank-of-bahrain', 'National Bank Of Bahrain'],
            ['51097', 'badr-al-islami', 'Badr Al Islami'],
            ['51101', 'al-tayer-motors-llc', 'Al Tayer Motors Llc'],
            ['51109', 'amlak-finance', 'Amlak Finance'],
            ['51111', 'arab-bank-for-investment-foreign-trade-2', 'Arab Bank For Investment & Foreign Trade'],
            ['51002', 'mashreq-bank', 'Mashreq Bank'],
            ['51015', 'national-bank-of-dubai', 'National Bank Of Dubai'],
            ['51017', 'abu-dhabi-islamic-bank', 'Abu Dhabi Islamic Bank'],
            ['51033', 'bank-saderat-iran', 'Bank Saderat Iran'],
            ['51044', 'credit-suisse', 'Credit Suisse'],
            ['51051', 'ing-asia-private-bank', 'Ing Asia Provate Bank'],
            ['51053', 'janata-bank', 'Janata Bank'],
            ['51058', 'national-bank-of-umm-al-qaiwain', 'National Bank of Umm Al-Qaiwain'],
            ['51069', 'bank-muscat-al-ahli-al-omani', 'Bank Muscat Al Ahli Al Omani'],
            ['51074', 'dresdner-bank', 'Dresdner Bank'],
            ['51080', 'philippine-national-bank', 'Philippine National Bank'],
            ['51092', 'juma-al-majid-est', 'Juma Al Majid Est'],
            ['51096', 'finance-house', 'Finance House'],
            ['51117', 'mubadala-development-company', 'Mubadala Development Company'],
            ['51128', 'national-bank-of-ras-al-khaimah', 'National Bank Of Ras Al Khaimah'],
            ['99909', 'galadari-automobiles-co-ltd-llc', 'Galadari Automobiles Co Ltd. - L.L.C.'],
            ['51178', 'mortgag-tto-al-ttigari-al-islami', 'Mortgag Tto ( Al Ttigari Al Islami)'],
            ['99915', 'others', 'Others'],
            ['51159', 'al-wifaq-finance-company', 'Al Wifaq Finance Company'],
            ['51168', 'al-masaood-automobiles', 'Al Masaood Automobiles'],
            ['60089', 'al-futtaim-auto-machinery-llc-famco', 'Al Futtaim Auto & Machinery LLC (FAMCO)'],
            ['51191', 'adcb-islamic-banking', 'ADCB ISLAMIC BANKING'],
            ['99948', 'deem-finance', 'Deem Finance'],
            ['51050', 'icici-bank', 'Icici Bank'],
            ['51062', 'union-bancaire-privee', 'Union Bancaire Privee'],
            ['51001', 'middle-east-finance-co', 'Middle East Finance Co'],
            ['51020', 'ansbacher-middle-east', 'Ansbacher Middle East'],
            ['51027', 'bank-melli-iran', 'Bank Melli Iran'],
            ['51043', 'commercial-bank-of-dubai', 'Commercial Bank Of Dubai'],
            ['51046', 'emirates-industrial-bank', 'Emirates Industrial Bank'],
            ['51048', 'first-gulf-bank', 'First Gulf Bank'],
            ['51151', 'abu-dhabi-investment-council', 'Abu Dhabi Investment Council'],
            ['51154', 'abu-dhabi-national-islamic-finance', 'Abu Dhabi National Islamic Finance'],
            ['51150', 'emirates-nbd', 'Emirates NBD'],
            ['51162', 'khalifa-fund-for-enterprise-development', 'Khalifa Fund For Enterprise Development'],
            ['51098', 'dubai-petroleum-company', 'Dubai Petroleum Company'],
            ['51144', 'emirates-investment-authority-2', 'Emirates Investment Authority'],
            ['51156', 'reem-finance', 'Reem Finance'],
            ['51088', 'emirates-airlines-abu-dhabi-commercial-bank', 'Emirates Airlines / Abu Dhabi Commercial Bank'],
            ['51183', 'miral-asset-management-llc', 'Miral Asset Management LLC'],
            ['51186', 'united-diesel-llc', 'United Diesel LLC'],
            ['99928', 'habib-bank-limited', 'Habib bank Limited'],
            ['99938', 'refrigerated-transport-systems-llc', 'Refrigerated Transport Systems (LLC)'],
            ['51198', 'al-futtaim-auto-machinery-company-llc', 'Al Futtaim Auto & Machinery Company (L.L.C)'],
            ['51189', 'emirates-investment-bank', 'Emirates Investment Bank'],
            ['999512', 'emirates-steel-industries-co-pjs', 'Emirates Steel Industries Co PJS'],
            ['51146', 'emirates-airline-duniya-finance-llc', 'Emirates Airline / Duniya Finance Llc'],
            ['51172', 'ek-airlines-and-al-hilal-bank', 'Ek Airlines And Al Hilal Bank'],
            ['99914', 'etihad-rail', 'Etihad Rail'],
            ['99931', 'gasco', 'GASCO'],
            ['51195', 'bmw-albatha-finance-psc', 'BMW Albatha Finance PSC'],
            ['56007', 'al-futtaim-motors-company-llc', 'AL FUTTAIM MOTORS COMPANY LLC'],
            ['51042', 'commercial-bank-international-plc', 'Commercial Bank International Plc'],
            ['51066', 'emirates-islamic', 'Emirates Islamic'],
            ['51068', 'bank-brussels-lambert', 'Bank Brussels Lambert'],
            ['51078', 'merrill-lynch-bank-suisse', 'Merrill Lynch Bank Suisse'],
            ['51081', 'societe-generali', 'Societe Generali'],
            ['51118', 'utmost-building-materials-llc', 'Utmost Building Materials Llc'],
            ['51123', 'emirates-airlines-or-emirates-bank-international-pjsc', 'Emirates Airlines &/Or Emirates Bank International Pjsc'],
            ['51004', 'osool-finance-company', 'Osool Finance Company'],
            ['51008', 'dubai-islamic-bank', 'Dubai Islamic Bank'],
            ['51016', 'abn-amro', 'Abn Amro'],
            ['51021', 'anz-grindlays-bank', 'Anz Grindlays Bank'],
            ['51025', 'arab-emirates-investment-bank', 'Arab Emirates Investment Bank'],
            ['51031', 'bank-of-the-arab-coast', 'Bank Of The Arab Coast'],
            ['51035', 'banque-du-caire', 'Banque Du Caire'],
            ['51041', 'calyon-bank', 'Calyon Bank'],
            ['51065', 'united-bank', 'United Bank'],
            ['51077', 'investment-bank-for-trade-finance', 'Investment Bank For Trade & Finance'],
            ['51103', 'al-masraf-bank', 'Al Masraf Bank'],
            ['51110', 'arabian-automobiles-company', 'Arabian Automobiles Company'],
            ['51126', 'emirates-airlines-or-mashreq-bank', 'Emirates Airlines &/Or Mashreq Bank'],
            ['51164', 'swaidan-trading-co-llc', 'Swaidan Trading Co. Llc'],
            ['51129', 'emirates-bank-or-lloyds-tsb-bank-plc', 'Emirates Bank &/Or Lloyds Tsb Bank Plc'],
            ['51136', 'omeir-bin-youssef-and-sons-llc', 'Omeir Bin Youssef And Sons Llc'],
            ['99930', 'hsbc-middle-east-finance-company', 'HSBC Middle East Finance Company'],
            ['51188', 'hsbc-bank-middle-east-ltd', 'HSBC Bank Middle East Ltd'],
            ['51166', 'samba-bank', 'Samba Bank'],
            ['51192', 'abu-dhabi-finance', 'Abu Dhabi Finance'],
            ['100000', 'union-bank-of-india', 'Union Bank of India'],
            ['100003', 'juma-al-majid-co-llc', 'JUMA AL MAJID Co LLC'],
            ['51201', 'kanoo-machinery-llc', 'Kanoo Machinery LLC'],
            ['99949', 'banque-banorient-france', 'Banque Banorient France'],
            ['51076', 'hsbc-financial-services', 'Hsbc Financial Services'],
            ['51091', 'national-bank-of-fujairah', 'National Bank Of Fujairah'],
            ['51094', 'knowledge-management-intl', 'Knowledge Management Int\'L'],
            ['51202', 'al-fahim-motors', 'Al Fahim Motors'],
            ['51157', 'higher-corporation-for-specialized-economic-zone', 'Higher Corporation For Specialized Economic Zone'],
            ['51036', 'banque-libanaise-pour-le-commerce', 'Banque Libanaise Pour Le Commerce'],
            ['51061', 'royal-bank-of-canada', 'Royal Bank Of Canada'],
            ['51067', 'ubs-ag', 'Ubs Ag'],
            ['51083', 'emirates-airlines-2', 'Emirates Airlines'],
            ['99907', 'islamic-finance-company', 'Islamic Finance Company'],
            ['51087', 'badr-al-islami-2', 'Badr Al Islami'],
            ['51175', 'rak-bank-islamic-division', 'Rak Bank - Islamic Division'],
            ['51181', 'banque-misr', 'Banque Misr'],
            ['99929', 'national-bank-of-abudhabi', 'National Bank of Abudhabi'],
            ['51196', 'dalma-motors-llc', 'Dalma Motors LLC'],
            ['51193', 'emirates-islamic-bank', 'Emirates Islamic Bank'],
            ['51132', 'hilal-bank', 'Hilal Bank'],
            ['51086', 'noor-bank-2', 'Noor Bank'],
            ['56004', 'united-motor-heavy-equipment-co-llc', 'United Motor & Heavy Equipment CO. LLC'],
            ['51029', 'bank-of-credit-commerce-international', 'Bank Of Credit & Commerce International'],
            ['51032', 'bank-of-tokyo', 'Bank Of Tokyo'],
            ['60094', 'ali-sons-holdings-llc', 'Ali & Sons Holdings LLC'],
            ['51064', 'united-arab-bank', 'United Arab Bank'],
            ['51106', 'al-futtaim-motors', 'Al Futtaim Motors'],
            ['51114', 'general-navigation-and-commerce-company-llc', 'General Navigation And Commerce Company Llc'],
        ];

        foreach ($banks as $bank) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::BANK_NAME,
                'code' => $bank[0],
                'text' => $bank[2],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function annualMileageEstimate()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '1',
            'text' => 'Less than 8,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '2',
            'text' => '8,000- 20,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '3',
            'text' => '20,000- 40,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '4',
            'text' => '40,000- 60,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '5',
            'text' => '60,000 -100,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '6',
            'text' => '> 100,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function nationalityList()
    {
        $nationalities = [
            ['id' => 87, 'text' => 'Afghan'],
            ['id' => 88, 'text' => 'Albanian'],
            ['id' => 86, 'text' => 'Algerian'],
            ['id' => 2, 'text' => 'American'],
            ['id' => 89, 'text' => 'Andorran'],
            ['id' => 90, 'text' => 'Angolan'],
            ['id' => 200, 'text' => 'Antiguan and Barbudan'],
            ['id' => 61, 'text' => 'Argentinian'],
            ['id' => 91, 'text' => 'Armenian'],
            ['id' => 18, 'text' => 'Australian'],
            ['id' => 17, 'text' => 'Austrian'],
            ['id' => 92, 'text' => 'Azerbaijani'],
            ['id' => 201, 'text' => 'Azores'],
            ['id' => 93, 'text' => 'Bahamian'],
            ['id' => 5, 'text' => 'Bahraini'],
            ['id' => 202, 'text' => 'Balearic Islands'],
            ['id' => 62, 'text' => 'Bangladeshi'],
            ['id' => 94, 'text' => 'Barbadian'],
            ['id' => 19, 'text' => 'Belgian'],
            ['id' => 96, 'text' => 'Belizean'],
            ['id' => 95, 'text' => 'Belorussian'],
            ['id' => 97, 'text' => 'Beninese'],
            ['id' => 203, 'text' => 'Bermuda'],
            ['id' => 98, 'text' => 'Bhutanese'],
            ['id' => 99, 'text' => 'Bolivian'],
            ['id' => 100, 'text' => 'Herzegovinian'],
            ['id' => 100, 'text' => 'Bosnian'],
            ['id' => 101, 'text' => 'Botswanan'],
            ['id' => 39, 'text' => 'Brazilian'],
            ['id' => 3, 'text' => 'British'],
            ['id' => 52, 'text' => 'Bruneian'],
            ['id' => 102, 'text' => 'Bulgarian'],
            ['id' => 103, 'text' => 'Burkinese'],
            ['id' => 104, 'text' => 'Burmese'],
            ['id' => 105, 'text' => 'Burundian'],
            ['id' => 107, 'text' => 'Cabo Verdean'],
            ['id' => 63, 'text' => 'Cambodian'],
            ['id' => 106, 'text' => 'Cameroonian'],
            ['id' => 12, 'text' => 'Canadian'],
            ['id' => 204, 'text' => 'Canary Islands'],
            ['id' => 225, 'text' => 'Central African'],
            ['id' => 108, 'text' => 'Chadian'],
            ['id' => 109, 'text' => 'Chilean'],
            ['id' => 27, 'text' => 'Chinese'],
            ['id' => 50, 'text' => 'Colombian'],
            ['id' => 198, 'text' => 'Comorian'],
            ['id' => 242, 'text' => 'Comoros Islands'],
            ['id' => 110, 'text' => 'Congolese'],
            ['id' => 111, 'text' => 'Costa Rican'],
            ['id' => 221, 'text' => "Cote d'Ivoire"],
            ['id' => 112, 'text' => 'Croatian'],
            ['id' => 113, 'text' => 'Cuban'],
            ['id' => 26, 'text' => 'Cypriot'],
            ['id' => 64, 'text' => 'Czech'],
            ['id' => 23, 'text' => 'Danish'],
            ['id' => 114, 'text' => 'Djiboutian'],
            ['id' => 115, 'text' => 'Dominican'],
            ['id' => 132, 'text' => 'Dutch'],
            ['id' => 227, 'text' => 'East Timorese'],
            ['id' => 117, 'text' => 'Ecuadorean'],
            ['id' => 43, 'text' => 'Egyptian'],
            ['id' => 223, 'text' => 'Emarat'],
            ['id' => 4, 'text' => 'Emirati'],
            ['id' => 228, 'text' => 'Equatoguinean'],
            ['id' => 119, 'text' => 'Eritrean'],
            ['id' => 120, 'text' => 'Estonian'],
            ['id' => 121, 'text' => 'Ethiopian'],
            ['id' => 205, 'text' => 'Faroe Islands'],
            ['id' => 122, 'text' => 'Fijian'],
            ['id' => 74, 'text' => 'Filipino'],
            ['id' => 84, 'text' => 'Finnish'],
            ['id' => 14, 'text' => 'French'],
            ['id' => 123, 'text' => 'Gabonese'],
            ['id' => 124, 'text' => 'Gambian'],
            ['id' => 125, 'text' => 'Georgian'],
            ['id' => 10, 'text' => 'German'],
            ['id' => 126, 'text' => 'Ghanaian'],
            ['id' => 206, 'text' => 'Gibraltar'],
            ['id' => 65, 'text' => 'Greek'],
            ['id' => 127, 'text' => 'Grenadian'],
            ['id' => 207, 'text' => 'Guadeloupe'],
            ['id' => 208, 'text' => 'Guam'],
            ['id' => 128, 'text' => 'Guatemalan'],
            ['id' => 220, 'text' => 'Guinea Bissau'],
            ['id' => 129, 'text' => 'Guinean'],
            ['id' => 130, 'text' => 'Guyanese'],
            ['id' => 131, 'text' => 'Haitian'],
            ['id' => 133, 'text' => 'Honduran'],
            ['id' => 51, 'text' => 'Hungarian'],
            ['id' => 134, 'text' => 'Icelandic'],
            ['id' => 13, 'text' => 'Indian'],
            ['id' => 38, 'text' => 'Indonesian'],
            ['id' => 66, 'text' => 'Iranian'],
            ['id' => 67, 'text' => 'Iraqi'],
            ['id' => 68, 'text' => 'Irish'],
            ['id' => 209, 'text' => 'Islas Canaria'],
            ['id' => 135, 'text' => 'Israeli'],
            ['id' => 15, 'text' => 'Italian'],
            ['id' => 241, 'text' => 'Ivory Coast'],
            ['id' => 136, 'text' => 'Jamaican'],
            ['id' => 21, 'text' => 'Japanese'],
            ['id' => 7, 'text' => 'Jordanian'],
            ['id' => 137, 'text' => 'Kazakh'],
            ['id' => 138, 'text' => 'Kenyan'],
            ['id' => 229, 'text' => 'Kiribatian'],
            ['id' => 34, 'text' => 'Korean'],
            ['id' => 230, 'text' => 'Kosovar'],
            ['id' => 6, 'text' => 'Kuwaiti'],
            ['id' => 197, 'text' => 'Kyrgyz'],
            ['id' => 140, 'text' => 'Laotian'],
            ['id' => 141, 'text' => 'Latvian'],
            ['id' => 28, 'text' => 'Lebanese'],
            ['id' => 142, 'text' => 'Liberian'],
            ['id' => 143, 'text' => 'Libyan'],
            ['id' => 144, 'text' => 'Liechtensteinian'],
            ['id' => 145, 'text' => 'Lithuanian'],
            ['id' => 146, 'text' => 'Luxembourgian'],
            ['id' => 147, 'text' => 'Macedonian'],
            ['id' => 148, 'text' => 'Madagascan'],
            ['id' => 210, 'text' => 'Madeira'],
            ['id' => 149, 'text' => 'Malawian'],
            ['id' => 36, 'text' => 'Malaysian'],
            ['id' => 150, 'text' => 'Maldivian'],
            ['id' => 151, 'text' => 'Malian'],
            ['id' => 152, 'text' => 'Maltese'],
            ['id' => 231, 'text' => 'Marshallese'],
            ['id' => 211, 'text' => 'Martinique'],
            ['id' => 153, 'text' => 'Mauritanian'],
            ['id' => 154, 'text' => 'Mauritian'],
            ['id' => 69, 'text' => 'Mexican'],
            ['id' => 232, 'text' => 'Micronesian'],
            ['id' => 155, 'text' => 'Moldovan'],
            ['id' => 156, 'text' => 'Monegasque'],
            ['id' => 157, 'text' => 'Mongolian'],
            ['id' => 158, 'text' => 'Montenegrin'],
            ['id' => 70, 'text' => 'Moroccan'],
            ['id' => 159, 'text' => 'Mozambican'],
            ['id' => 160, 'text' => 'Namibian'],
            ['id' => 233, 'text' => 'Nauruan'],
            ['id' => 71, 'text' => 'Nepalese'],
            ['id' => 25, 'text' => 'New Zealander'],
            ['id' => 161, 'text' => 'Nicaraguan'],
            ['id' => 57, 'text' => 'Nigerian'],
            ['id' => 162, 'text' => 'Nigerien'],
            ['id' => 163, 'text' => 'North Korean'],
            ['id' => 49, 'text' => 'Norwegian'],
            ['id' => 9, 'text' => 'Omani'],
            ['id' => 29, 'text' => 'Pakistani'],
            ['id' => 234, 'text' => 'Palauan'],
            ['id' => 72, 'text' => 'Palestinian'],
            ['id' => 164, 'text' => 'Panamanian'],
            ['id' => 165, 'text' => 'Papua New Guinean'],
            ['id' => 166, 'text' => 'Paraguayan'],
            ['id' => 73, 'text' => 'Peruvian'],
            ['id' => 75, 'text' => 'Polish'],
            ['id' => 46, 'text' => 'Portuguese'],
            ['id' => 212, 'text' => 'Puerto Rico'],
            ['id' => 8, 'text' => 'Qatari'],
            ['id' => 213, 'text' => 'Reunion'],
            ['id' => 167, 'text' => 'Romanian'],
            ['id' => 76, 'text' => 'Russian'],
            ['id' => 168, 'text' => 'Rwandan'],
            ['id' => 214, 'text' => 'Saint Kitts and Nevis'],
            ['id' => 215, 'text' => 'Saint Lucians'],
            ['id' => 216, 'text' => 'Saint Vincent and the Grenadines'],
            ['id' => 118, 'text' => 'Salvadorean'],
            ['id' => 235, 'text' => 'Sammarinese'],
            ['id' => 194, 'text' => 'Samoan'],
            ['id' => 236, 'text' => 'Sao Tome and Principe'],
            ['id' => 77, 'text' => 'Saudi'],
            ['id' => 169, 'text' => 'Senegalese'],
            ['id' => 170, 'text' => 'Serbian'],
            ['id' => 171, 'text' => 'Seychellois'],
            ['id' => 172, 'text' => 'Sierra Leonian'],
            ['id' => 24, 'text' => 'Singaporean'],
            ['id' => 173, 'text' => 'Slovak'],
            ['id' => 174, 'text' => 'Slovenian'],
            ['id' => 175, 'text' => 'Solomon Islands'],
            ['id' => 176, 'text' => 'Somali'],
            ['id' => 35, 'text' => 'South African'],
            ['id' => 237, 'text' => 'South Korea'],
            ['id' => 139, 'text' => 'South Korean'],
            ['id' => 16, 'text' => 'Spanish'],
            ['id' => 40, 'text' => 'Sri Lankan'],
            ['id' => 238, 'text' => 'St.Kitts'],
            ['id' => 239, 'text' => 'St.Vincent'],
            ['id' => 44, 'text' => 'Sudanese'],
            ['id' => 178, 'text' => 'Surinamese'],
            ['id' => 179, 'text' => 'Swazi'],
            ['id' => 22, 'text' => 'Swedish'],
            ['id' => 20, 'text' => 'Swiss'],
            ['id' => 31, 'text' => 'Syrian'],
            ['id' => 226, 'text' => 'TONGAN'],
            ['id' => 217, 'text' => 'Tahiti'],
            ['id' => 33, 'text' => 'Taiwanese'],
            ['id' => 180, 'text' => 'Tajik'],
            ['id' => 181, 'text' => 'Tanzanian'],
            ['id' => 37, 'text' => 'Thai'],
            ['id' => 182, 'text' => 'Togolese'],
            ['id' => 183, 'text' => 'Trinidadian And Toboggan'],
            ['id' => 85, 'text' => 'Tunisian'],
            ['id' => 80, 'text' => 'Turkish'],
            ['id' => 184, 'text' => 'Turkmen'],
            ['id' => 185, 'text' => 'Tuvaluan'],
            ['id' => 186, 'text' => 'Ugandan'],
            ['id' => 187, 'text' => 'Ukrainian'],
            ['id' => 188, 'text' => 'Uruguayan'],
            ['id' => 189, 'text' => 'Uzbek'],
            ['id' => 190, 'text' => 'Vanuatuan'],
            ['id' => 191, 'text' => 'Vatican City'],
            ['id' => 192, 'text' => 'Venezuelan'],
            ['id' => 81, 'text' => 'Vietnamese'],
            ['id' => 218, 'text' => 'Virgin Islands ( British)'],
            ['id' => 219, 'text' => 'Virgin Islands (Usa)'],
            ['id' => 222, 'text' => 'West Indian'],
            ['id' => 240, 'text' => 'Western Samoa'],
            ['id' => 83, 'text' => 'Yemeni'],
            ['id' => 195, 'text' => 'Zairean'],
            ['id' => 196, 'text' => 'Zambian'],
            ['id' => 53, 'text' => 'Zimbabwean'],
        ];

        foreach ($nationalities as $nationality) {
            $this->syncNationalityWithLiva($nationality['text'], $nationality['id']);
        }
    }

    private function drivingExperience()
    {
        for ($i = 0; $i <= 51; $i++) {
            $text = match (true) {
                $i === 0 => 'No Experience',
                $i === 1 => '1 Year',
                default => $i.' Years',
            };

            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::DRIVING_EXPERIENCE,
                'code' => $i,
                'text' => $text,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * Sync nationality with LIVA nationality ID
     * Searches for matching nationality by text and updates liva_nationality_id
     * If no match found, creates a new nationality record
     *
     * @param string $livaText The nationality text from LIVA
     * @param int $livaId The LIVA nationality ID
     * @return void
     */
    private function syncNationalityWithLiva(string $livaText, int $livaId): void
    {
        $normalizedText = trim($livaText);

        $nationality = Nationality::updateOrCreate(
            ['text' => $normalizedText],
            [
                'code' => $normalizedText,
                'text' => $normalizedText,
                'liva_nationality_id' => $livaId,
                'is_active' => 1,
            ]
        );

        LoggerService::info($livaText.' - '.($nationality->wasRecentlyCreated ? 'Created new' : 'Updated existing').' nationality');
    }
}
