<?php

namespace Database\Seeders;

use App\Enums\InsuranceProvidersEnum;
use App\Enums\LookupsEnum;
use App\Enums\QuoteTypeId;
use App\Models\InsuranceProvider;
use App\Models\Lookup;
use App\Services\Logger\LoggerService;
use Illuminate\Database\Seeder;

class CarAdditionalDetailsForLivaSeeder extends Seeder
{
    private $insuranceProviderId;

    public function __construct()
    {
        $this->insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::RSA)
            ->select(['id', 'code'])
            ->first()->id;

        LoggerService::info(self::class.' fn: '.__FUNCTION__, extra: [
            'insurance_provider_id' => $this->insuranceProviderId,
            'insurance_provider_code' => InsuranceProvidersEnum::RSA,
        ]);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->plateCode();
        $this->rtaTransactionType();
        $this->rtaPlateCategory();
        $this->vehicleColor();
        $this->bankName();
        $this->annualMileageEstimate();
        $this->nationalityList();
        $this->drivingExperience();
    }

    private function plateCode()
    {
        $plateCodes = [
            'A', 'AA', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'WHITE', 'X', 'Y', 'Z', 'BB', 'CC', 'DD', 'EE', 'HH', 'MM', 'NN',
        ];

        foreach ($plateCodes as $plateCode) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::PLATE_CODE,
                'code' => $plateCode,
                'text' => $plateCode,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function rtaTransactionType()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '10',
            'text' => 'Registration of new vehicle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '20',
            'text' => 'Changing vehicle ownership (current registration valid)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '30',
            'text' => 'Changing vehicle ownership (current registration to expire)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '40',
            'text' => 'Renewal of vehicle (with current number plate)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => '50',
            'text' => 'Renewal of vehicle (with new number plate)',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function rtaPlateCategory()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '14',
            'text' => 'Private',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '18',
            'text' => 'Motorcycle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '39',
            'text' => 'Delegate',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '42',
            'text' => 'Consulate Authority',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '45',
            'text' => 'Classical',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => '36',
            'text' => 'Dubai Flag',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function vehicleColor()
    {
        $vehicleColorList = [
            ['1', 'WHITE'],
            ['3', 'RED'],
            ['5', 'YELLOW'],
            ['6', 'GREEN'],
            ['8', 'SILVER'],
            ['20', 'ADRIATIC'],
            ['21', 'ADRIATIC BLUE'],
            ['22', 'AEGEAN BLUE'],
            ['23', 'ALABASTER BLACK'],
            ['24', 'ALABASTER GREY'],
            ['1177', 'ALABASTER SILVER'],
            ['25', 'ALABASTER WHITE'],
            ['26', 'ALASKAN WHITE'],
            ['27', 'ALFA RED'],
            ['28', 'ALLOY'],
            ['29', 'ALPINE WHITE'],
            ['30', 'ALPINE WHITE METALLIC'],
            ['31', 'ALVESTON RED'],
            ['32', 'AM PURPLE/Q.SILVER'],
            ['1141', 'AMATHAYEST'],
            ['1165', 'AMBER'],
            ['33', 'AMBER BRONZE METALLIC'],
            ['34', 'AMBER RED'],
            ['35', 'AMETHYST GREY'],
            ['36', 'ANTIQUE GREEN'],
            ['37', 'APPLE GREEN'],
            ['38', 'AQUA'],
            ['39', 'AQUA BLUE'],
            ['40', 'AQUA METALLIC'],
            ['41', 'AQUA SILVER'],
            ['42', 'ARCTIC'],
            ['43', 'ARCTIC BLUE'],
            ['44', 'ARCTIC FROST'],
            ['45', 'ARCTIC SILVER'],
            ['46', 'ARENA RED'],
            ['47', 'AROMA RED'],
            ['48', 'ARTIC WHITE'],
            ['49', 'ASCOT GREEN'],
            ['50', 'ASH GOLD'],
            ['51', 'ASH GOLD METALLIC'],
            ['52', 'ASTLER BLUE'],
            ['53', 'ATACAMA SAND'],
            ['54', 'ATLAS GREY'],
            ['55', 'AUBERGINE'],
            ['56', 'AUTUMN BLAZE'],
            ['57', 'AUTUMN COPPER'],
            ['58', 'AZURE BLUE'],
            ['1236', 'Aluminum/Black/Grey/White/Silver'],
            ['59', 'BAHIA BEIGE'],
            ['60', 'BARENTS BLUE METALLIC'],
            ['1167', 'BAROSSA'],
            ['61', 'BASALT BLACK'],
            ['62', 'BASALT BLACK METALLIC'],
            ['63', 'BEIGE BLACK'],
            ['64', 'BEIGE GREY'],
            ['65', 'BEIGE METALLIC'],
            ['66', 'BEIGE MICA METALLIC'],
            ['67', 'BEIGE PEARL'],
            ['68', 'BEIGE/BLUE'],
            ['69', 'BEIGE/BROWN'],
            ['1188', 'BEIGE/BROWN/ORANGE'],
            ['70', 'BEIGE/CASHMERE'],
            ['71', 'BEIGE/GREEN'],
            ['72', 'BEIGE/GREEN/RED'],
            ['73', 'BEIGE/GREY'],
            ['74', 'BEIGE/MAROON'],
            ['1163', 'BEIGE/MAROON/BLACK'],
            ['75', 'BEIGE/OLIVE GREEN'],
            ['76', 'BEIGE/RED'],
            ['77', 'BEIGE/SILVER'],
            ['78', 'BEIGE/WHITE'],
            ['79', 'BELUGA'],
            ['80', 'BIANCA WHITE'],
            ['81', 'BIARRITZ BLUE'],
            ['1198', 'BIKINI PEARL COAT'],
            ['82', 'BILLET SILVER METALLIC'],
            ['83', 'BIZZARD'],
            ['2', 'BLACK'],
            ['84', 'BLACK'],
            ['85', 'BLACK BEIGE'],
            ['1134', 'BLACK CHERRY'],
            ['86', 'BLACK CLEARCOAT'],
            ['87', 'BLACK GREEN'],
            ['88', 'BLACK II'],
            ['89', 'BLACK JAVA'],
            ['90', 'BLACK MAROON'],
            ['119', 'BLACK METALLIC'],
            ['91', 'BLACK MICA'],
            ['92', 'BLACK OBSIMET'],
            ['93', 'BLACK PEARL'],
            ['94', 'BLACK RAVEN'],
            ['95', 'BLACK SAPPHIRE'],
            ['96', 'BLACK SPARKLING METALLIC'],
            ['97', 'BLACK WHITE MAROON'],
            ['98', 'BLACK/BEIGE'],
            ['99', 'BLACK/BLACK'],
            ['100', 'BLACK/BLUE'],
            ['1219', 'BLACK/BLUE/YELLOW'],
            ['101', 'BLACK/BROWN'],
            ['102', 'BLACK/COPPER'],
            ['103', 'BLACK/EBONY'],
            ['104', 'BLACK/GOLD'],
            ['105', 'BLACK/GOLDEN'],
            ['106', 'BLACK/GREEN'],
            ['107', 'BLACK/GREY'],
            ['108', 'BLACK/IVORY'],
            ['109', 'BLACK/LEATHER TRIM'],
            ['110', 'BLACK/LIGHT BLUE'],
            ['111', 'BLACK/ORANGE'],
            ['112', 'BLACK/ORANGE/GREEN'],
            ['113', 'BLACK/RED'],
            ['114', 'BLACK/SILVER'],
            ['115', 'BLACK/WHITE'],
            ['116', 'BLACK/WHITE/BLUE'],
            ['117', 'BLACK/WHITE/ORANGE'],
            ['118', 'BLACK/YELLOW'],
            ['1186', 'BLACK/YELLOW/SILVER'],
            ['4', 'BLUE'],
            ['120', 'BLUE'],
            ['121', 'BLUE CHIP'],
            ['122', 'BLUE COOLSILVER'],
            ['123', 'BLUE GRAPHITE'],
            ['124', 'BLUE GREEN SILVER'],
            ['125', 'BLUE GREY'],
            ['126', 'BLUE GREY SILVER'],
            ['127', 'BLUE JADE'],
            ['128', 'BLUE METALLIC'],
            ['129', 'BLUE MICA'],
            ['130', 'BLUE MYSTIC'],
            ['131', 'BLUE ORANGE'],
            ['132', 'BLUE OVER SILVER'],
            ['133', 'BLUE PEARL'],
            ['134', 'BLUE PURPLE'],
            ['135', 'BLUE RED GREY'],
            ['136', 'BLUE SILVER'],
            ['137', 'BLUE WATER'],
            ['138', 'BLUE/BEIGE'],
            ['139', 'BLUE/BEIGE/ORANGE'],
            ['140', 'BLUE/BROWN'],
            ['1187', 'BLUE/GOLD'],
            ['141', 'BLUE/GREEN'],
            ['142', 'BLUE/GREEN/WHITE'],
            ['143', 'BLUE/GREEN/YELLOW'],
            ['144', 'BLUE/GREY'],
            ['145', 'BLUE/GREY/LEAD'],
            ['146', 'BLUE/GREY/SILVER'],
            ['147', 'BLUE/GREY/YELLOW'],
            ['148', 'BLUE/LIGHT GREY'],
            ['149', 'BLUE/MILKY'],
            ['150', 'BLUE/ORANGE'],
            ['151', 'BLUE/RED'],
            ['152', 'BLUE/RED/BLACK'],
            ['153', 'BLUE/RED/GREY'],
            ['154', 'BLUE/RED/WHITE'],
            ['155', 'BLUE/SILVER'],
            ['1130', 'BLUE/SILVER/BLACK'],
            ['156', 'BLUE/SILVER/GREY'],
            ['157', 'BLUE/SLATE'],
            ['1196', 'BLUE/VIOLET/BLACK'],
            ['158', 'BLUE/WHITE'],
            ['159', 'BLUE/YELLOW'],
            ['160', 'BLUEGREEN CRYSTAL'],
            ['161', 'BLUEISH BLACK'],
            ['162', 'BLUEISH PEARL'],
            ['163', 'BLUEISH SILVER METALLIC'],
            ['164', 'BLUISH GREEN'],
            ['165', 'BLUISH GREY'],
            ['166', 'BLUISH PEARL'],
            ['167', 'BLUISH RED'],
            ['168', 'BLUISH SILVER'],
            ['169', 'BOLD BEIGE METALLIC'],
            ['170', 'BONATTI GREY'],
            ['171', 'BORDEAUX PONTEVECCHI'],
            ['172', 'BORNITE (PURPLE)'],
            ['173', 'BORREGO BEIGE'],
            ['174', 'BOTANY BLUE'],
            ['175', 'BOTTLE GREEN'],
            ['176', 'BOULDER GREY'],
            ['1124', 'BOURNVILLE'],
            ['177', 'BRICK RED'],
            ['178', 'BRIGHT GOLDEN'],
            ['179', 'BRIGHT GREEN'],
            ['180', 'BRIGHT PLATINUM'],
            ['181', 'BRIGHT SILVER'],
            ['182', 'BRIGHT WHITE'],
            ['1139', 'BRILLIANT BLACK'],
            ['183', 'BRILLIANT SILVER'],
            ['184', 'BRONZE'],
            ['185', 'BRONZE METALLIC'],
            ['186', 'BROWN'],
            ['187', 'BROWN GREEN BLACK'],
            ['188', 'BROWN GREY'],
            ['189', 'BROWN SILVER'],
            ['190', 'BROWN/BEIGE'],
            ['191', 'BROWN/BLUE'],
            ['192', 'BROWN/GOLD'],
            ['193', 'BROWN/GOLDEN'],
            ['194', 'BROWN/GREEN'],
            ['195', 'BROWN/GREY'],
            ['196', 'BROWN/SILVER'],
            ['197', 'BROWN/WHITE'],
            ['198', 'BROWNISH'],
            ['199', 'BROWNISH GREY'],
            ['200', 'BUCKINGHAM BLUE'],
            ['201', 'BURGUNDY'],
            ['202', 'BURGUNDY SILVER'],
            ['203', 'BURNING RED'],
            ['204', 'BVO BEIGE'],
            ['13', 'Beige'],
            ['1203', 'Black Gray Yellow'],
            ['1174', 'Black/Blue/Grey'],
            ['1238', 'Black/Green/Silver'],
            ['1154', 'Black/Red/Grey'],
            ['1147', 'Blackish Red'],
            ['9', 'Bronze'],
            ['7', 'Brown'],
            ['205', 'C. GREEN'],
            ['206', 'C. GREEN PEARL'],
            ['207', 'C. RED'],
            ['208', 'C.BLUE'],
            ['209', 'C.GREY'],
            ['210', 'C.SILVER'],
            ['211', 'C.SILVER/GREY'],
            ['212', 'CAIRNS BLUE'],
            ['213', 'CALCITE WHITE'],
            ['214', 'CALYPSO RED'],
            ['215', 'CANAL BLUE'],
            ['216', 'CANARY YELLOW'],
            ['217', 'CANDY RUBY RED'],
            ['218', 'CANDY SWORD BLUE'],
            ['219', 'CANDY WHITE'],
            ['220', 'CANYON RED'],
            ['221', 'CARBON'],
            ['222', 'CARBON BLACK'],
            ['223', 'CARBON GREY'],
            ['224', 'CASABLANCA'],
            ['225', 'CASHMERE'],
            ['226', 'CASHMERE (BEIGE)'],
            ['227', 'CASHMERE METALLIC'],
            ['1137', 'CASHMERE SILVER'],
            ['228', 'CASHMERE STEEL'],
            ['1133', 'CATTLEYA'],
            ['1151', 'CAVIAR'],
            ['229', 'CELESTIAL BLUE PEARL'],
            ['230', 'CHAMPAGNE'],
            ['231', 'CHAMPAGNE'],
            ['232', 'CHAMPAGNE GOLD'],
            ['233', 'CHAMPAGNE GREY'],
            ['234', 'CHAMPAGNE METALLIC'],
            ['235', 'CHAMPAGNE MICA'],
            ['236', 'CHAMPAGNE PEARL'],
            ['237', 'CHAMPAGNE SILVER'],
            ['238', 'CHAMPAGNE/GOLDEN'],
            ['239', 'CHAR GOLD'],
            ['240', 'CHARCOAL GREY'],
            ['241', 'CHASTE WHITE'],
            ['242', 'CHAWTON WHITE'],
            ['243', 'CHERRY BROWN'],
            ['244', 'CHERRY RED'],
            ['245', 'CHERRY WHITE'],
            ['246', 'CHINA BLUE'],
            ['1189', 'CHROME/BLACK'],
            ['247', 'CINNAMON BROWN'],
            ['248', 'CINNAMON GLAZE'],
            ['249', 'CLOVER GREEN'],
            ['250', 'COBALT BLUE'],
            ['1229', 'CODE ORANGE'],
            ['251', 'CONCORD PURPLE'],
            ['252', 'CONE SILVER'],
            ['253', 'COOL SILVER'],
            ['254', 'COOL SILVER METALLIC'],
            ['255', 'COOL WHITE'],
            ['256', 'COPPER'],
            ['257', 'COPPER BLACK'],
            ['258', 'CORAL'],
            ['259', 'CORN YELLOW'],
            ['260', 'CREAM'],
            ['261', 'CREAM BROWN'],
            ['262', 'CREAM WHITE'],
            ['1244', 'CREAMY WHITE-BLACK'],
            ['263', 'CRIMSON RED'],
            ['264', 'CRYSTAL'],
            ['265', 'CRYSTAL ICE'],
            ['266', 'CRYSTAL ICE METALLIC'],
            ['267', 'CRYSTAL ICE WHITE'],
            ['268', 'CRYSTAL SILVER'],
            ['269', 'CUBANITE SILVER'],
            ['270', 'CYAN'],
            ['271', 'CYPRUS GREEN'],
            ['1223', 'Charente Grey'],
            ['1237', 'Crayon'],
            ['1243', 'Crystal White Pearl Metallic'],
            ['272', 'D B GREY'],
            ['273', 'DARD GREEN'],
            ['274', 'DARK BEIGE'],
            ['275', 'DARK BLUE'],
            ['276', 'DARK BLUE METALLIC'],
            ['277', 'DARK BLUE MICA METAL'],
            ['278', 'DARK BLUE WHITE'],
            ['279', 'DARK BLUISH GREY'],
            ['280', 'DARK BROWN'],
            ['281', 'DARK CANDY'],
            ['282', 'DARK CHERRY'],
            ['283', 'DARK CHESTNUT'],
            ['284', 'DARK DENIM GREY'],
            ['285', 'DARK EMERALD'],
            ['286', 'DARK GARNET RED'],
            ['287', 'DARK GREEN'],
            ['288', 'DARK GREY'],
            ['289', 'DARK GREY METALLIC'],
            ['290', 'DARK GREY MICA'],
            ['1127', 'DARK INDIGO'],
            ['291', 'DARK KAKHI'],
            ['1216', 'DARK KNIGHT'],
            ['292', 'DARK MAROON'],
            ['293', 'DARK MICA GREEN'],
            ['294', 'DARK ORANGE'],
            ['295', 'DARK RED'],
            ['296', 'DARK RED METALLIC'],
            ['297', 'DARK RED MICA'],
            ['298', 'DARK SHADOW GREY'],
            ['299', 'DARK SILVER'],
            ['300', 'DARK STONE'],
            ['301', 'DARK TORQUOISE PEARL'],
            ['302', 'DARK WHITE'],
            ['303', 'DEEP BLUE'],
            ['304', 'DEEP BLUE METALLIC'],
            ['305', 'DEEP BLUE MICA'],
            ['306', 'DEEP BLUE MIST'],
            ['307', 'DEEP LAVA RED'],
            ['308', 'DEEP NAVY'],
            ['309', 'DEEP SEA BLUE METALLIC'],
            ['310', 'DESERT MIST METALLIC'],
            ['311', 'DESERT PLATINUM'],
            ['312', 'DESERT ROCK METALLIC'],
            ['1126', 'DESERT STONE'],
            ['313', 'DESERT VIOLET'],
            ['314', 'DIABLO RED'],
            ['315', 'DIAMOND GRAPHITE'],
            ['316', 'DIAMOND SILVER'],
            ['317', 'DIAMOND SILVER METALLIC'],
            ['318', 'DIAMOND WHITE'],
            ['319', 'DOVE SILVER'],
            ['320', 'DRIFTWOOD METALLIC'],
            ['321', 'DUSTY GOLD'],
            ['1148', 'Dark Sapphire'],
            ['1206', 'Deep Crystal Blue'],
            ['1228', 'Diamond Black Crystal Pearl'],
            ['1170', 'Diamond Black Silver'],
            ['16', 'EBONY'],
            ['322', 'EBONY'],
            ['323', 'EBONY BEIGE'],
            ['324', 'ECLIPE GREY'],
            ['325', 'EISEN GREY'],
            ['326', 'ELECTRIC SILVER'],
            ['327', 'EMBER BLACK'],
            ['328', 'EMERALD GREEN'],
            ['329', 'ENABI'],
            ['330', 'ENABI RED'],
            ['331', 'ENABI(RASPBERRY)'],
            ['332', 'ENABI/SILVER'],
            ['333', 'EPSON GREEN'],
            ['1213', 'ESSENCE BROWN'],
            ['334', 'ETERNAL BLUE'],
            ['335', 'EVO BEIGE'],
            ['336', 'EVOKE'],
            ['337', 'EXEC. BLACK'],
            ['1240', 'Earthy Brass Metallic'],
            ['338', 'F.BEIGE'],
            ['339', 'FAIRY WHITE'],
            ['340', 'FALAN RED'],
            ['341', 'FERN WHITE'],
            ['342', 'FIRE OPAL'],
            ['343', 'FIRE OPAL(RED)'],
            ['344', 'FIRE RED'],
            ['345', 'FLAME RED'],
            ['346', 'FLASH RED'],
            ['347', 'FR BEIGE'],
            ['348', 'FRASER BEIGE'],
            ['349', 'FRESCO GREEN'],
            ['350', 'FROST BLUE'],
            ['351', 'FROZEN WHITE'],
            ['1227', 'FUJI WHITE'],
            ['352', 'GALAXY BEIGE'],
            ['353', 'GALAXY BLACK'],
            ['354', 'GALAXY BLUE'],
            ['355', 'GALAXY CAPTIVA'],
            ['356', 'GALAXY GREY'],
            ['357', 'GALAXY METALLIC'],
            ['358', 'GALAXY SILVER'],
            ['359', 'GALAXY WHITE'],
            ['360', 'GENESIS BLUE'],
            ['1161', 'GLACIER'],
            ['361', 'GLACIER GREEN'],
            ['362', 'GLACIER WHITE/BLUE'],
        ];

        foreach ($vehicleColorList as $color) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $color[0],
                'text' => $color[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function bankName()
    {
        $banks = [
            ['51155', 'gargash-enterprises', 'Gargash Enterprises'],
            ['51005', 'emirates-bank', 'Emirates Bank'],
            ['51006', 'citibank', 'Citibank'],
            ['51158', 'the-petroleum-institute-of-abu-dhabi', 'The Petroleum Institute Of Abu Dhabi'],
            ['51084', 'etisalat', 'Etisalat'],
            ['51152', 'al-khaliji-france', 'Al Khaliji France'],
            ['51022', 'arab-african-international-bank', 'Arab African International Bank'],
            ['51090', 'sharjah-islamic-bank', 'Sharjah Islamic Bank'],
            ['51093', 'liberty-automobiles-co-llc', 'Liberty Automobiles Co. Llc'],
            ['51107', 'abu-dhabi-investment-authority', 'Abu Dhabi Investment Authority'],
            ['51119', 'takreer-abu-dhabi-oil-refining-company', 'Takreer (Abu Dhabi Oil Refining Company)'],
            ['51124', 'emirates-airlines-or-hsbc-mefco', 'Emirates Airlines &/Or Hsbc Mefco'],
            ['51134', 'ajman-bank', 'Ajman Bank'],
            ['51145', 'adnoc', 'Adnoc'],
            ['51138', 'al-badr-islamic-finance-company', 'Al Badr Islamic Finance Company'],
            ['51163', 'emirates-motor-company', 'Emirates Motor Company'],
            ['51173', 'commercial-bank-international', 'Commercial Bank International'],
            ['51167', 'emirates-nuclear-energy-corporation', 'Emirates Nuclear Energy Corporation'],
            ['51169', 'al-futtaim-finance-company', 'Al Futtaim Finance Company'],
            ['99934', 'abu-dhabi-commercial-islamic-finance', 'Abu Dhabi Commercial Islamic Finance'],
            ['51185', 'ruby-diamond-investments-limited', 'Ruby Diamond Investments Limited'],
            ['51127', 'emirates-airlines-national-bank-of-dubai', 'Emirates Airlines / National Bank Of Dubai'],
            ['99910', 'bahrain-house-finance', 'Bahrain House Finance'],
            ['99946', 'al-futtaim-finance', 'AL FUTTAIM FINANCE'],
            ['99932', 'noor-islamic-bank', 'Noor Islamic Bank'],
            ['60092', 'inter-emirates-motors-sole-proprietorship-llc', 'INTER EMIRATES MOTORS SOLE PORPRIETORSHIP LLC'],
            ['99950', 'el-nilein-bank', 'EL NILEIN BANK'],
            ['51040', 'bnp-paribas', 'Bnp Paribas'],
            ['51099', 'doha-bank', 'Doha Bank'],
            ['51003', 'standard-chartered-bank', 'Standard Chartered Bank'],
            ['51009', 'habib-bank', 'Habib Bank'],
            ['51012', 'dubai-commercial-bank', 'Dubai Commercial Bank'],
            ['99908', 'emirates-money', 'Emirates Money'],
            ['51030', 'bank-of-sharjah', 'Bank Of Sharjah'],
            ['51038', 'banque-paribas', 'Banque Paribas'],
            ['51039', 'barclays-bank-plc', 'Barclays Bank Plc'],
            ['51075', 'deutsche-bank-ag', 'Deutsche Bank Ag'],
            ['51079', 'national-bank-of-sharjah', 'National Bank Of Sharjah'],
            ['51139', 'duniatrade', 'Duniatrade'],
            ['51095', 'hsbc-amanah', 'Hsbc Amanah'],
            ['51102', 'al-habtoor-motors-co-llc', 'Al Habtoor Motors Co Llc'],
            ['51116', 'maf-orix-finance-pjsc', 'Maf Orix Finance Pjsc'],
            ['51121', 'dynatrade', 'Dynatrade'],
            ['51141', 'emirates-airlines-or-emirates-islamic-bank', 'Emirates Airlines &/Or Emirates Islamic Bank'],
            ['51142', 'yaseer-car-rental', 'Yaseer Car Rental'],
            ['51143', 'gargash-motors', 'Gargash Motors'],
            ['51174', 'mashreq-al-islami', 'Mashreq Al Islami'],
            ['60068', 'oasis-enterprises-llc', 'Oasis Enterprises Llc'],
            ['51176', 'emirates-airlines-emirates-nbd', 'Emirates Airlines / Emirates Nbd'],
            ['60067', 'al-buhaira-national-insurance-co-abnic', 'Al Buhaira National Insurance Co (Abnic)'],
            ['51170', 'aafaq-islamic-finance-company', 'Aafaq Islamic Finance Company'],
            ['51182', 'bmw-albatha-finance', 'BMW Albatha Finance'],
            ['51187', 'tamweel', 'Tamweel'],
            ['51190', 'hsbc', 'HSBC'],
            ['51199', 'belhasa-motors', 'Belhasa Motors'],
            ['51135', 'al-khoory-automobile-llc', 'Al Khoory Automobile Llc'],
            ['51034', 'banque-banorabe', 'Banque Banorabe'],
            ['51037', 'banque-nationale-de-paris', 'Banque Nationale De Paris'],
            ['51047', 'emirates-national-bank', 'Emirates National Bank'],
            ['51073', 'core-states-bank', 'Core States Bank'],
            ['51120', 'trading-enterprises', 'Trading Enterprises'],
            ['99906', 'advanced-technology-investment-company-atic', 'Advanced Technology Investment Company (Atic)'],
            ['51010', 'habib-bank-ag-zurich', 'Habib Bank Ag Zurich'],
            ['51011', 'abu-dhabi-commercial-bank', 'Abu Dhabi Commercial Bank'],
            ['51013', 'national-bank-of-abu-dhabi', 'National Bank Of Abu Dhabi'],
            ['51018', 'alahli-bank-of-kuwait', 'Alahli Bank Of Kuwait'],
            ['51019', 'american-express', 'American Express'],
            ['51024', 'arab-bank', 'Arab Bank'],
            ['51060', 'rak-bank', 'RAK Bank'],
            ['51070', 'bank-of-bahrain-kuwait', 'Bank Of Bahrain & Kuwait'],
            ['51082', 'uae-central-bank', 'U.A.E. Central Bank'],
            ['51133', 'royal-bank-of-scotland', 'Royal Bank Of Scotland'],
            ['51137', 'al-ghandi-auto', 'Al Ghandi Auto'],
            ['51115', 'gulf-finance-corporation', 'Gulf Finance Corporation'],
            ['51122', 'emirates-dnata', 'Emirates / Dnata'],
            ['51125', 'emirates-airlines-or-lloyds-tsb-bank-plc', 'Emirates Airlines &/Or Lloyds Tsb Bank Plc'],
            ['51085', 'mawarid-finance', 'Mawarid Finance'],
            ['51153', 'emirates-money-consumer-finance-1', 'Emirates Money Consumer Finance'],
            ['51148', 'emirates-money-consumer-finance-2', 'Emirates Money Consumer Finance'],
            ['51179', 'commercial-bank-of-dubai-attijari-al-islami', 'Commercial Bank Of Dubai - Attijari Al Islami'],
            ['51180', 'al-hail-orix-finance', 'Al Hail Orix Finance'],
            ['51200', 'al-rostamani-trading-company-llc', 'Al Rostamani Trading Company LLC'],
            ['99937', 'mdc-business-management-services', 'MDC Business Management Services'],
            ['51184', 'national-auto', 'National Auto'],
            ['99935', 'first-abu-dhabi-bank', 'FIRST ABU DHABI BANK'],
            ['51194', 'blom-bank-france', 'Blom Bank France'],
            ['51149', 'ajman-bank-2', 'Ajman Bank'],
            ['51089', 'dnata', 'Dnata'],
            ['99947', 'al-futtaim-finance-pvjsc', 'AL FUTTAIM FINANCE PVJSC'],
            ['60091', 'mohamed-abdulrahman-al-bahar-llc', 'Mohamed Abdulrahman Al-Bahar LLC'],
            ['100002', 'nawah-energy', 'Nawah Energy'],
            ['60088', 'gb-equipment-solutions-llc-dubai', 'GB Equipment solutions LLC, Dubai'],
            ['60093', 'al-habtoor-royal-car-llc', 'Al Habtoor Royal Car LLC'],
            ['51026', 'banca-commerciale-italiana', 'Banca Commerciale Italiana'],
            ['51045', 'dubai-bank', 'Dubai Bank'],
            ['51052', 'invest-bank', 'Invest Bank'],
            ['51054', 'lloyds-tsb-bank', 'Lloyds TSB Bank'],
            ['51059', 'rafidain-bank', 'Rafidain Bank'],
            ['51071', 'banque-indosuez', 'Banque Indosuez'],
            ['51104', 'al-nabooda-automobiles-llc', 'Al Nabooda Automobiles Llc'],
            ['51014', 'sharjah-bank', 'Sharjah Bank'],
            ['51023', 'arab-bank-for-investment-foreign-trade', 'Arab Bank For Investment & Foreign Trade'],
            ['51028', 'bank-of-baroda', 'Bank Of Baroda'],
            ['51049', 'hamid-bank-limited', 'Hamid Bank Limited'],
            ['51055', 'middle-east-bank', 'Middle East Bank'],
            ['51056', 'natexis-banques-populaires', 'Natexis Banques Populaires'],
            ['51063', 'union-national-bank', 'Union National Bank'],
            ['51072', 'cedel-bank', 'Cedel Bank'],
            ['51140', 'dunia-finance', 'Dunia Finance'],
            ['51160', 'attijari-al-islami', 'Attijari Al Islami'],
            ['99911', 'abudhabi-future-energy-company', 'Abudhabi Future Energy Company'],
            ['51100', 'al-yousuf-llc', 'Al Yousuf Llc'],
            ['51105', 'adma-opco', 'Adma Opco'],
            ['51108', 'noor-bank-1', 'Noor Bank'],
            ['51112', 'blc-bank', 'Blc Bank'],
            ['51113', 'blom-bank', 'Blom Bank'],
            ['51147', 'gargash-enterprises-llc', 'Gargash Enterprises Llc'],
            ['51161', 'borouge-abu-dhabi-polymers-co-ltd', 'Borouge Abu Dhabi Polymers Co Ltd'],
            ['51131', 'al-hilal-bank', 'Al Hilal Bank'],
            ['99913', 'arabian-gulf-mechanical-centre', 'Arabian Gulf Mechanical Centre'],
            ['51171', 'mubadala-ge-capital-pjsc', 'Mubadala Ge Capital P.J.S.C'],
            ['99933', 'bmw-albatha-finance-2', 'BMW Albatha Finance'],
            ['51197', 'al-shirawi-enterprises-llc', 'AL SHIRAWI ENTERPRISES LLC'],
            ['99912', 'afge-money', 'Afge Money'],
            ['51130', 'al-noor-islamic-bank', 'Al Noor Islamic Bank'],
            ['51165', 'emirates-investment-authority', 'Emirates Investment Authority'],
            ['51177', 'al-majid-motors', 'Al Majid Motors'],
            ['51057', 'national-bank-of-bahrain', 'National Bank Of Bahrain'],
            ['51097', 'badr-al-islami', 'Badr Al Islami'],
            ['51101', 'al-tayer-motors-llc', 'Al Tayer Motors Llc'],
            ['51109', 'amlak-finance', 'Amlak Finance'],
            ['51111', 'arab-bank-for-investment-foreign-trade-2', 'Arab Bank For Investment & Foreign Trade'],
            ['51002', 'mashreq-bank', 'Mashreq Bank'],
            ['51015', 'national-bank-of-dubai', 'National Bank Of Dubai'],
            ['51017', 'abu-dhabi-islamic-bank', 'Abu Dhabi Islamic Bank'],
            ['51033', 'bank-saderat-iran', 'Bank Saderat Iran'],
            ['51044', 'credit-suisse', 'Credit Suisse'],
            ['51051', 'ing-asia-private-bank', 'Ing Asia Provate Bank'],
            ['51053', 'janata-bank', 'Janata Bank'],
            ['51058', 'national-bank-of-umm-al-qaiwain', 'National Bank of Umm Al-Qaiwain'],
            ['51069', 'bank-muscat-al-ahli-al-omani', 'Bank Muscat Al Ahli Al Omani'],
            ['51074', 'dresdner-bank', 'Dresdner Bank'],
            ['51080', 'philippine-national-bank', 'Philippine National Bank'],
            ['51092', 'juma-al-majid-est', 'Juma Al Majid Est'],
            ['51096', 'finance-house', 'Finance House'],
            ['51117', 'mubadala-development-company', 'Mubadala Development Company'],
            ['51128', 'national-bank-of-ras-al-khaimah', 'National Bank Of Ras Al Khaimah'],
            ['99909', 'galadari-automobiles-co-ltd-llc', 'Galadari Automobiles Co Ltd. - L.L.C.'],
            ['51178', 'mortgag-tto-al-ttigari-al-islami', 'Mortgag Tto ( Al Ttigari Al Islami)'],
            ['99915', 'others', 'Others'],
            ['51159', 'al-wifaq-finance-company', 'Al Wifaq Finance Company'],
            ['51168', 'al-masaood-automobiles', 'Al Masaood Automobiles'],
            ['60089', 'al-futtaim-auto-machinery-llc-famco', 'Al Futtaim Auto & Machinery LLC (FAMCO)'],
            ['51191', 'adcb-islamic-banking', 'ADCB ISLAMIC BANKING'],
            ['99948', 'deem-finance', 'Deem Finance'],
            ['51050', 'icici-bank', 'Icici Bank'],
            ['51062', 'union-bancaire-privee', 'Union Bancaire Privee'],
            ['51001', 'middle-east-finance-co', 'Middle East Finance Co'],
            ['51020', 'ansbacher-middle-east', 'Ansbacher Middle East'],
            ['51027', 'bank-melli-iran', 'Bank Melli Iran'],
            ['51043', 'commercial-bank-of-dubai', 'Commercial Bank Of Dubai'],
            ['51046', 'emirates-industrial-bank', 'Emirates Industrial Bank'],
            ['51048', 'first-gulf-bank', 'First Gulf Bank'],
            ['51151', 'abu-dhabi-investment-council', 'Abu Dhabi Investment Council'],
            ['51154', 'abu-dhabi-national-islamic-finance', 'Abu Dhabi National Islamic Finance'],
            ['51150', 'emirates-nbd', 'Emirates NBD'],
            ['51162', 'khalifa-fund-for-enterprise-development', 'Khalifa Fund For Enterprise Development'],
            ['51098', 'dubai-petroleum-company', 'Dubai Petroleum Company'],
            ['51144', 'emirates-investment-authority-2', 'Emirates Investment Authority'],
            ['51156', 'reem-finance', 'Reem Finance'],
            ['51088', 'emirates-airlines-abu-dhabi-commercial-bank', 'Emirates Airlines / Abu Dhabi Commercial Bank'],
            ['51183', 'miral-asset-management-llc', 'Miral Asset Management LLC'],
            ['51186', 'united-diesel-llc', 'United Diesel LLC'],
            ['99928', 'habib-bank-limited', 'Habib bank Limited'],
            ['99938', 'refrigerated-transport-systems-llc', 'Refrigerated Transport Systems (LLC)'],
            ['51198', 'al-futtaim-auto-machinery-company-llc', 'Al Futtaim Auto & Machinery Company (L.L.C)'],
            ['51189', 'emirates-investment-bank', 'Emirates Investment Bank'],
            ['999512', 'emirates-steel-industries-co-pjs', 'Emirates Steel Industries Co PJS'],
            ['51146', 'emirates-airline-duniya-finance-llc', 'Emirates Airline / Duniya Finance Llc'],
            ['51172', 'ek-airlines-and-al-hilal-bank', 'Ek Airlines And Al Hilal Bank'],
            ['99914', 'etihad-rail', 'Etihad Rail'],
            ['99931', 'gasco', 'GASCO'],
            ['51195', 'bmw-albatha-finance-psc', 'BMW Albatha Finance PSC'],
            ['56007', 'al-futtaim-motors-company-llc', 'AL FUTTAIM MOTORS COMPANY LLC'],
            ['51042', 'commercial-bank-international-plc', 'Commercial Bank International Plc'],
            ['51066', 'emirates-islamic', 'Emirates Islamic'],
            ['51068', 'bank-brussels-lambert', 'Bank Brussels Lambert'],
            ['51078', 'merrill-lynch-bank-suisse', 'Merrill Lynch Bank Suisse'],
            ['51081', 'societe-generali', 'Societe Generali'],
            ['51118', 'utmost-building-materials-llc', 'Utmost Building Materials Llc'],
            ['51123', 'emirates-airlines-or-emirates-bank-international-pjsc', 'Emirates Airlines &/Or Emirates Bank International Pjsc'],
            ['51004', 'osool-finance-company', 'Osool Finance Company'],
            ['51008', 'dubai-islamic-bank', 'Dubai Islamic Bank'],
            ['51016', 'abn-amro', 'Abn Amro'],
            ['51021', 'anz-grindlays-bank', 'Anz Grindlays Bank'],
            ['51025', 'arab-emirates-investment-bank', 'Arab Emirates Investment Bank'],
            ['51031', 'bank-of-the-arab-coast', 'Bank Of The Arab Coast'],
            ['51035', 'banque-du-caire', 'Banque Du Caire'],
            ['51041', 'calyon-bank', 'Calyon Bank'],
            ['51065', 'united-bank', 'United Bank'],
            ['51077', 'investment-bank-for-trade-finance', 'Investment Bank For Trade & Finance'],
            ['51103', 'al-masraf-bank', 'Al Masraf Bank'],
            ['51110', 'arabian-automobiles-company', 'Arabian Automobiles Company'],
            ['51126', 'emirates-airlines-or-mashreq-bank', 'Emirates Airlines &/Or Mashreq Bank'],
            ['51164', 'swaidan-trading-co-llc', 'Swaidan Trading Co. Llc'],
            ['51129', 'emirates-bank-or-lloyds-tsb-bank-plc', 'Emirates Bank &/Or Lloyds Tsb Bank Plc'],
            ['51136', 'omeir-bin-youssef-and-sons-llc', 'Omeir Bin Youssef And Sons Llc'],
            ['99930', 'hsbc-middle-east-finance-company', 'HSBC Middle East Finance Company'],
            ['51188', 'hsbc-bank-middle-east-ltd', 'HSBC Bank Middle East Ltd'],
            ['51166', 'samba-bank', 'Samba Bank'],
            ['51192', 'abu-dhabi-finance', 'Abu Dhabi Finance'],
            ['100000', 'union-bank-of-india', 'Union Bank of India'],
            ['100003', 'juma-al-majid-co-llc', 'JUMA AL MAJID Co LLC'],
            ['51201', 'kanoo-machinery-llc', 'Kanoo Machinery LLC'],
            ['99949', 'banque-banorient-france', 'Banque Banorient France'],
            ['51076', 'hsbc-financial-services', 'Hsbc Financial Services'],
            ['51091', 'national-bank-of-fujairah', 'National Bank Of Fujairah'],
            ['51094', 'knowledge-management-intl', 'Knowledge Management Int\'L'],
            ['51202', 'al-fahim-motors', 'Al Fahim Motors'],
            ['51157', 'higher-corporation-for-specialized-economic-zone', 'Higher Corporation For Specialized Economic Zone'],
            ['51036', 'banque-libanaise-pour-le-commerce', 'Banque Libanaise Pour Le Commerce'],
            ['51061', 'royal-bank-of-canada', 'Royal Bank Of Canada'],
            ['51067', 'ubs-ag', 'Ubs Ag'],
            ['51083', 'emirates-airlines-2', 'Emirates Airlines'],
            ['99907', 'islamic-finance-company', 'Islamic Finance Company'],
            ['51087', 'badr-al-islami-2', 'Badr Al Islami'],
            ['51175', 'rak-bank-islamic-division', 'Rak Bank - Islamic Division'],
            ['51181', 'banque-misr', 'Banque Misr'],
            ['99929', 'national-bank-of-abudhabi', 'National Bank of Abudhabi'],
            ['51196', 'dalma-motors-llc', 'Dalma Motors LLC'],
            ['51193', 'emirates-islamic-bank', 'Emirates Islamic Bank'],
            ['51132', 'hilal-bank', 'Hilal Bank'],
            ['51086', 'noor-bank-2', 'Noor Bank'],
            ['56004', 'united-motor-heavy-equipment-co-llc', 'United Motor & Heavy Equipment CO. LLC'],
            ['51029', 'bank-of-credit-commerce-international', 'Bank Of Credit & Commerce International'],
            ['51032', 'bank-of-tokyo', 'Bank Of Tokyo'],
            ['60094', 'ali-sons-holdings-llc', 'Ali & Sons Holdings LLC'],
            ['51064', 'united-arab-bank', 'United Arab Bank'],
            ['51106', 'al-futtaim-motors', 'Al Futtaim Motors'],
            ['51114', 'general-navigation-and-commerce-company-llc', 'General Navigation And Commerce Company Llc'],
        ];

        foreach ($banks as $bank) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::BANK_NAME,
                'code' => $bank[0],
                'text' => $bank[2],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function annualMileageEstimate()
    {
        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '1',
            'text' => 'Less than 8,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '2',
            'text' => '8,000- 20,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '3',
            'text' => '20,000- 40,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '4',
            'text' => '40,000- 60,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '5',
            'text' => '60,000 -100,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::updateOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::ANNUAL_MILEAGE_ESTIMATE,
            'code' => '6',
            'text' => '> 100,000 KM',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function nationalityList()
    {
        $nationalities = [
            ['id' => 87, 'text' => 'Afghan'],
            ['id' => 88, 'text' => 'Albanian'],
            ['id' => 86, 'text' => 'Algerian'],
            ['id' => 2, 'text' => 'American'],
            ['id' => 89, 'text' => 'Andorran'],
            ['id' => 90, 'text' => 'Angolan'],
            ['id' => 200, 'text' => 'Antiguan and Barbudan'],
            ['id' => 61, 'text' => 'Argentinian'],
            ['id' => 91, 'text' => 'Armenian'],
            ['id' => 18, 'text' => 'Australian'],
            ['id' => 17, 'text' => 'Austrian'],
            ['id' => 92, 'text' => 'Azerbaijani'],
            ['id' => 201, 'text' => 'Azores'],
            ['id' => 93, 'text' => 'Bahamian'],
            ['id' => 5, 'text' => 'Bahraini'],
            ['id' => 202, 'text' => 'Balearic Islands'],
            ['id' => 62, 'text' => 'Bangladeshi'],
            ['id' => 94, 'text' => 'Barbadian'],
            ['id' => 19, 'text' => 'Belgian'],
            ['id' => 96, 'text' => 'Belizean'],
            ['id' => 95, 'text' => 'Belorussian'],
            ['id' => 97, 'text' => 'Beninese'],
            ['id' => 203, 'text' => 'Bermuda'],
            ['id' => 98, 'text' => 'Bhutanese'],
            ['id' => 99, 'text' => 'Bolivian'],
            ['id' => 100, 'text' => 'Herzegovinian'],
            ['id' => 100, 'text' => 'Bosnian'],
            ['id' => 101, 'text' => 'Botswanan'],
            ['id' => 39, 'text' => 'Brazilian'],
            ['id' => 3, 'text' => 'British'],
            ['id' => 52, 'text' => 'Bruneian'],
            ['id' => 102, 'text' => 'Bulgarian'],
            ['id' => 103, 'text' => 'Burkinese'],
            ['id' => 104, 'text' => 'Burmese'],
            ['id' => 105, 'text' => 'Burundian'],
            ['id' => 107, 'text' => 'Cabo Verdean'],
            ['id' => 63, 'text' => 'Cambodian'],
            ['id' => 106, 'text' => 'Cameroonian'],
            ['id' => 12, 'text' => 'Canadian'],
            ['id' => 204, 'text' => 'Canary Islands'],
            ['id' => 225, 'text' => 'Central African'],
            ['id' => 108, 'text' => 'Chadian'],
            ['id' => 109, 'text' => 'Chilean'],
            ['id' => 27, 'text' => 'Chinese'],
            ['id' => 50, 'text' => 'Colombian'],
            ['id' => 198, 'text' => 'Comorian'],
            ['id' => 242, 'text' => 'Comoros Islands'],
            ['id' => 110, 'text' => 'Congolese'],
            ['id' => 111, 'text' => 'Costa Rican'],
            ['id' => 221, 'text' => "Cote d'Ivoire"],
            ['id' => 112, 'text' => 'Croatian'],
            ['id' => 113, 'text' => 'Cuban'],
            ['id' => 26, 'text' => 'Cypriot'],
            ['id' => 64, 'text' => 'Czech'],
            ['id' => 23, 'text' => 'Danish'],
            ['id' => 114, 'text' => 'Djiboutian'],
            ['id' => 115, 'text' => 'Dominican'],
            ['id' => 132, 'text' => 'Dutch'],
            ['id' => 227, 'text' => 'East Timorese'],
            ['id' => 117, 'text' => 'Ecuadorean'],
            ['id' => 43, 'text' => 'Egyptian'],
            ['id' => 223, 'text' => 'Emarat'],
            ['id' => 4, 'text' => 'Emirati'],
            ['id' => 228, 'text' => 'Equatoguinean'],
            ['id' => 119, 'text' => 'Eritrean'],
            ['id' => 120, 'text' => 'Estonian'],
            ['id' => 121, 'text' => 'Ethiopian'],
            ['id' => 205, 'text' => 'Faroe Islands'],
            ['id' => 122, 'text' => 'Fijian'],
            ['id' => 74, 'text' => 'Filipino'],
            ['id' => 84, 'text' => 'Finnish'],
            ['id' => 14, 'text' => 'French'],
            ['id' => 123, 'text' => 'Gabonese'],
            ['id' => 124, 'text' => 'Gambian'],
            ['id' => 125, 'text' => 'Georgian'],
            ['id' => 10, 'text' => 'German'],
            ['id' => 126, 'text' => 'Ghanaian'],
            ['id' => 206, 'text' => 'Gibraltar'],
            ['id' => 65, 'text' => 'Greek'],
            ['id' => 127, 'text' => 'Grenadian'],
            ['id' => 207, 'text' => 'Guadeloupe'],
            ['id' => 208, 'text' => 'Guam'],
            ['id' => 128, 'text' => 'Guatemalan'],
            ['id' => 220, 'text' => 'Guinea Bissau'],
            ['id' => 129, 'text' => 'Guinean'],
            ['id' => 130, 'text' => 'Guyanese'],
            ['id' => 131, 'text' => 'Haitian'],
            ['id' => 133, 'text' => 'Honduran'],
            ['id' => 51, 'text' => 'Hungarian'],
            ['id' => 134, 'text' => 'Icelandic'],
            ['id' => 13, 'text' => 'Indian'],
            ['id' => 38, 'text' => 'Indonesian'],
            ['id' => 66, 'text' => 'Iranian'],
            ['id' => 67, 'text' => 'Iraqi'],
            ['id' => 68, 'text' => 'Irish'],
            ['id' => 209, 'text' => 'Islas Canaria'],
            ['id' => 135, 'text' => 'Israeli'],
            ['id' => 15, 'text' => 'Italian'],
            ['id' => 241, 'text' => 'Ivory Coast'],
            ['id' => 136, 'text' => 'Jamaican'],
            ['id' => 21, 'text' => 'Japanese'],
            ['id' => 7, 'text' => 'Jordanian'],
            ['id' => 137, 'text' => 'Kazakh'],
            ['id' => 138, 'text' => 'Kenyan'],
            ['id' => 229, 'text' => 'Kiribatian'],
            ['id' => 34, 'text' => 'Korean'],
            ['id' => 230, 'text' => 'Kosovar'],
            ['id' => 6, 'text' => 'Kuwaiti'],
            ['id' => 197, 'text' => 'Kyrgyz'],
            ['id' => 140, 'text' => 'Laotian'],
            ['id' => 141, 'text' => 'Latvian'],
            ['id' => 28, 'text' => 'Lebanese'],
            ['id' => 142, 'text' => 'Liberian'],
            ['id' => 143, 'text' => 'Libyan'],
            ['id' => 144, 'text' => 'Liechtensteinian'],
            ['id' => 145, 'text' => 'Lithuanian'],
            ['id' => 146, 'text' => 'Luxembourgian'],
            ['id' => 147, 'text' => 'Macedonian'],
            ['id' => 148, 'text' => 'Madagascan'],
            ['id' => 210, 'text' => 'Madeira'],
            ['id' => 149, 'text' => 'Malawian'],
            ['id' => 36, 'text' => 'Malaysian'],
            ['id' => 150, 'text' => 'Maldivian'],
            ['id' => 151, 'text' => 'Malian'],
            ['id' => 152, 'text' => 'Maltese'],
            ['id' => 231, 'text' => 'Marshallese'],
            ['id' => 211, 'text' => 'Martinique'],
            ['id' => 153, 'text' => 'Mauritanian'],
            ['id' => 154, 'text' => 'Mauritian'],
            ['id' => 69, 'text' => 'Mexican'],
            ['id' => 232, 'text' => 'Micronesian'],
            ['id' => 155, 'text' => 'Moldovan'],
            ['id' => 156, 'text' => 'Monegasque'],
            ['id' => 157, 'text' => 'Mongolian'],
            ['id' => 158, 'text' => 'Montenegrin'],
            ['id' => 70, 'text' => 'Moroccan'],
            ['id' => 159, 'text' => 'Mozambican'],
            ['id' => 160, 'text' => 'Namibian'],
            ['id' => 233, 'text' => 'Nauruan'],
            ['id' => 71, 'text' => 'Nepalese'],
            ['id' => 25, 'text' => 'New Zealander'],
            ['id' => 161, 'text' => 'Nicaraguan'],
            ['id' => 57, 'text' => 'Nigerian'],
            ['id' => 162, 'text' => 'Nigerien'],
            ['id' => 163, 'text' => 'North Korean'],
            ['id' => 49, 'text' => 'Norwegian'],
            ['id' => 9, 'text' => 'Omani'],
            ['id' => 29, 'text' => 'Pakistani'],
            ['id' => 234, 'text' => 'Palauan'],
            ['id' => 72, 'text' => 'Palestinian'],
            ['id' => 164, 'text' => 'Panamanian'],
            ['id' => 165, 'text' => 'Papua New Guinean'],
            ['id' => 166, 'text' => 'Paraguayan'],
            ['id' => 73, 'text' => 'Peruvian'],
            ['id' => 75, 'text' => 'Polish'],
            ['id' => 46, 'text' => 'Portuguese'],
            ['id' => 212, 'text' => 'Puerto Rico'],
            ['id' => 8, 'text' => 'Qatari'],
            ['id' => 213, 'text' => 'Reunion'],
            ['id' => 167, 'text' => 'Romanian'],
            ['id' => 76, 'text' => 'Russian'],
            ['id' => 168, 'text' => 'Rwandan'],
            ['id' => 214, 'text' => 'Saint Kitts and Nevis'],
            ['id' => 215, 'text' => 'Saint Lucians'],
            ['id' => 216, 'text' => 'Saint Vincent and the Grenadines'],
            ['id' => 118, 'text' => 'Salvadorean'],
            ['id' => 235, 'text' => 'Sammarinese'],
            ['id' => 194, 'text' => 'Samoan'],
            ['id' => 236, 'text' => 'Sao Tome and Principe'],
            ['id' => 77, 'text' => 'Saudi'],
            ['id' => 169, 'text' => 'Senegalese'],
            ['id' => 170, 'text' => 'Serbian'],
            ['id' => 171, 'text' => 'Seychellois'],
            ['id' => 172, 'text' => 'Sierra Leonian'],
            ['id' => 24, 'text' => 'Singaporean'],
            ['id' => 173, 'text' => 'Slovak'],
            ['id' => 174, 'text' => 'Slovenian'],
            ['id' => 175, 'text' => 'Solomon Islands'],
            ['id' => 176, 'text' => 'Somali'],
            ['id' => 35, 'text' => 'South African'],
            ['id' => 237, 'text' => 'South Korea'],
            ['id' => 139, 'text' => 'South Korean'],
            ['id' => 16, 'text' => 'Spanish'],
            ['id' => 40, 'text' => 'Sri Lankan'],
            ['id' => 238, 'text' => 'St.Kitts'],
            ['id' => 239, 'text' => 'St.Vincent'],
            ['id' => 44, 'text' => 'Sudanese'],
            ['id' => 178, 'text' => 'Surinamese'],
            ['id' => 179, 'text' => 'Swazi'],
            ['id' => 22, 'text' => 'Swedish'],
            ['id' => 20, 'text' => 'Swiss'],
            ['id' => 31, 'text' => 'Syrian'],
            ['id' => 226, 'text' => 'TONGAN'],
            ['id' => 217, 'text' => 'Tahiti'],
            ['id' => 33, 'text' => 'Taiwanese'],
            ['id' => 180, 'text' => 'Tajik'],
            ['id' => 181, 'text' => 'Tanzanian'],
            ['id' => 37, 'text' => 'Thai'],
            ['id' => 182, 'text' => 'Togolese'],
            ['id' => 183, 'text' => 'Trinidadian And Toboggan'],
            ['id' => 85, 'text' => 'Tunisian'],
            ['id' => 80, 'text' => 'Turkish'],
            ['id' => 184, 'text' => 'Turkmen'],
            ['id' => 185, 'text' => 'Tuvaluan'],
            ['id' => 186, 'text' => 'Ugandan'],
            ['id' => 187, 'text' => 'Ukrainian'],
            ['id' => 188, 'text' => 'Uruguayan'],
            ['id' => 189, 'text' => 'Uzbek'],
            ['id' => 190, 'text' => 'Vanuatuan'],
            ['id' => 191, 'text' => 'Vatican City'],
            ['id' => 192, 'text' => 'Venezuelan'],
            ['id' => 81, 'text' => 'Vietnamese'],
            ['id' => 218, 'text' => 'Virgin Islands ( British)'],
            ['id' => 219, 'text' => 'Virgin Islands (Usa)'],
            ['id' => 222, 'text' => 'West Indian'],
            ['id' => 240, 'text' => 'Western Samoa'],
            ['id' => 83, 'text' => 'Yemeni'],
            ['id' => 195, 'text' => 'Zairean'],
            ['id' => 196, 'text' => 'Zambian'],
            ['id' => 53, 'text' => 'Zimbabwean'],
        ];

        foreach ($nationalities as $nationality) {
            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::NATIONALITY_LIST,
                'code' => $nationality['id'],
                'text' => $nationality['text'],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function drivingExperience()
    {
        for ($i = 0; $i <= 51; $i++) {
            $text = match (true) {
                $i === 0 => 'No Experience',
                $i === 1 => '1 Year',
                default => $i.' Years',
            };

            Lookup::updateOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::DRIVING_EXPERIENCE,
                'code' => $i,
                'text' => $text,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
