<?php

namespace Database\Seeders;

use App\Enums\InsuranceProvidersEnum;
use App\Enums\LookupsEnum;
use App\Enums\QuoteTypeId;
use App\Models\InsuranceProvider;
use App\Models\Lookup;
use App\Services\Logger\LoggerService;
use Illuminate\Database\Seeder;

class CarAdditionalDetailsForSukoonSeeder extends Seeder
{
    private $insuranceProviderId;

    public function __construct()
    {
        $this->insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::OIC)
            ->select(['id', 'code'])
            ->first()->id;

        LoggerService::info(self::class.' fn: '.__FUNCTION__, extra: [
            'insurance_provider_id' => $this->insuranceProviderId,
            'insurance_provider_code' => InsuranceProvidersEnum::OIC,
        ]);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->rtaTransactionType();
        $this->plateCode();
        $this->rtaPlateCategory();
        $this->vehicleColor();
        $this->bankName();
    }

    private function plateCode()
    {
        $plateCodes = [
            '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '50', 'A', 'AA', 'AB', 'AD', 'AK', 'AM', 'AR', 'AS', 'AW', 'AY', 'B', 'BA', 'BB', 'BD', 'BH', 'BK', 'Blue', 'BM', 'BR', 'Brown', 'BS', 'BW', 'BY', 'C', 'Ceremonies', 'Classic', 'COMMERCIAL', 'CONSULATE', 'Consulate association', 'Consulate Authority', 'D', 'DA', 'DD', 'Diplomatic', 'Diplomatic association', 'DK', 'DR', 'DS', 'Dubai Flag', 'Dubai Police', 'DW', 'DY', 'E', 'Entertainment Motorcycle', 'EXPO 1', 'Export', 'F', 'Fifty Category', 'G', 'Government Vehicle', 'Green', 'Grey', 'H', 'HA', 'HD', 'HH', 'HK', 'HM', 'Hospitality', 'Hospitality Blue', 'Hospitality Yallow', 'HR', 'HS', 'HW', 'HY', 'I', 'Import', 'Intl. Organization', 'INTLORG', 'J', 'K', 'KA', 'KB', 'KH', 'KK', 'L', 'LEARNING', 'LK', 'M', 'MA', 'MB', 'MD', 'MH', 'MK', 'ML', 'MM', 'Motorcycle', 'Motorcycle2', 'Motorcycle3', 'MR', 'MS', 'MW', 'MY', 'N', 'O', 'Orange', 'P', 'Police', 'Political association', 'Political Authority', 'PRIVATETRANSPORTATIO', 'PUBLICTRANSPORTATION', 'Q', 'R', 'RA', 'Red', 'RH', 'RK', 'RM', 'RR', 'RS', 'RW', 'RY', 'S', 'Second Category', 'Sixty Category', 'SS', 'T', 'TA', 'TAXI', 'TB', 'TBA', 'Tenth Category', 'The Tower', 'TRADE', 'Trade Plate', 'Trade Plate white', 'Trailer', 'TT', 'U', 'V', 'W', 'WA', 'WB', 'White', 'WK', 'WW', 'X', 'Y', 'YA', 'YB', 'YD', 'Yellow', 'YM', 'YR', 'YS', 'YW', 'YY', 'Z', '20', 'CC',
        ];

        foreach ($plateCodes as $plateCode) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::PLATE_CODE,
                'code' => $plateCode,
                'text' => $plateCode,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function rtaTransactionType()
    {
        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'NVR',
            'text' => 'New Vehicle Registration',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'VRCRN',
            'text' => 'Vehicle Renewal With Change In Registration Number',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'VR',
            'text' => 'Vehicle Renewal',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'CVO',
            'text' => 'Change Vehicle Ownership',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'EC',
            'text' => 'Export Certificate',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'IV',
            'text' => 'Import Vehicle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function rtaPlateCategory()
    {
        $categories = [
            ['6', 'AGRICULTURE PURPOSE'],
            ['18', 'BUS'],
            ['2', 'COMMERCIAL'],
            ['19', 'HEAVY VEHICLE'],
            ['LEARNING', 'LEARNING'],
            ['25', 'LIMOUSINE'],
            ['23', 'MOBIKE'],
            ['999', 'OTHERS'],
            ['22', 'P/UP'],
            ['Private', 'PRIVATE'],
            ['20', 'PRIVATE1'],
            ['21', 'PRIVATE2'],
            ['10', 'PUBLIC'],
            ['9', 'PUBLIC CARRIER'],
            ['24', 'PUBLIC TRANSPORT'],
            ['4', 'RENTACAR'],
            ['5', 'TAXIS'],
            ['8', 'TRAILER'],
            ['16', 'WATER CARRIERS'],
            ['CLASSICAL', 'CLASSICAL'],
            ['CONSULATE', 'CONSULATE'],
            ['ENTMOTCYCLE', 'ENTERTAINMENT MOTORCYCLE'],
            ['POLATRTY', 'POLITICAL AUTHORITY'],
            ['IMPORT', 'IMPORT'],
            ['EXPORT', 'EXPORT'],
            ['HSPITALITY', 'Hospitality'],
            ['PVTTRSPRT', 'PrivateTransportation'],
            ['TRADE', 'TRADE'],
        ];

        foreach ($categories as $category) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::RTA_PLATE_CATEGORY,
                'code' => $category[0],
                'text' => $category[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function vehicleColor()
    {
        $colors = [
            ['1', 'White'],
            ['8', 'Silver'],
            ['9', 'Bronze'],
            ['12', 'Purple'],
            ['20', 'White/Green Line'],
            ['24', 'Blue/Silver'],
            ['31', 'Red/Silver'],
            ['39', 'Beige/Grey'],
            ['41', 'Silver/Grey'],
            ['44', 'Yellow / White'],
            ['47', 'Yellow / Red / Cream '],
            ['50', 'Lead / Grey'],
            ['55', 'Green / Silver '],
            ['57', 'Black / Orange'],
            ['68', 'Pink'],
            ['81', 'Yellow / Silver / Black'],
            ['85', 'Platinum'],
            ['89', 'Dark Grey'],
            ['99', 'Blue/Green/Yellow'],
            ['102', 'White/Red/Blue'],
            ['103', 'Red/Grey'],
            ['106', 'Grey/Blue'],
            ['117', 'White / Pearl'],
            ['118', 'White/Yellow/Brown'],
            ['120', 'White/Yellow/Green'],
            ['122', 'Yellow/Grey'],
            ['126', 'Light Rose'],
            ['130', 'Yellow / Lead'],
            ['151', 'Maroon/Yellow/Red'],
            ['163', 'Red/Yellow'],
            ['168', 'Yellow / Green '],
            ['172', 'White/Red/Green'],
            ['173', 'Blue/Green/Grey'],
            ['175', 'Grey/Purple'],
            ['186', 'White,Beige,Black'],
            ['189', 'Blue / Gold'],
            ['201', 'Gold/Orange'],
            ['209', 'Beige - Orange'],
            ['210', 'Beige/Gold'],
            ['212', 'White / Pink'],
            ['215', 'Black/Yellow/Red/Silver'],
            ['217', 'Sandy'],
            ['233', 'Silver/Pink/Blue'],
            ['237', 'Champagne'],
            ['239', 'Beige/Purpule'],
            ['240', 'Red/Silver/Green'],
            ['4', 'Blue'],
            ['6', 'Green'],
            ['15', 'White/Black'],
            ['21', 'White/Black/Green'],
            ['28', 'White/Red/Orange'],
            ['29', 'White/Blue'],
            ['35', 'Violet'],
            ['43', 'Yellow/Blue/Green'],
            ['46', 'Grey / Red'],
            ['48', 'Maroon/Gold'],
            ['53', 'Red / Beige'],
            ['56', 'Blue / White'],
            ['59', 'Green / Grey'],
            ['62', 'Cream / Green'],
            ['65', 'Grey / Orange'],
            ['67', 'Red / Cream'],
            ['70', 'Turquoise'],
            ['71', 'Red/Black'],
            ['72', 'Pearl White'],
            ['74', 'Blue/Green'],
            ['75', 'White/Cream'],
            ['77', 'White/Black/Red'],
            ['79', 'Beige Metalic'],
            ['80', 'Green / Yellow'],
            ['83', 'White / Brown'],
            ['87', 'Red / Gold'],
            ['88', 'Dark Rose'],
            ['92', 'Gold/Cream '],
            ['101', 'Silver / White'],
            ['107', 'Orange/Grey '],
            ['109', 'Ivory'],
            ['110', 'Rose Mica'],
            ['111', 'Rose Mica Metallic'],
            ['113', 'Orange/Red'],
            ['114', 'Metallic Grey'],
            ['116', 'Yellow/Blue/Black'],
            ['123', 'White / Yellow'],
            ['124', 'White/Brown/Red'],
            ['125', 'Sky Blue'],
            ['129', 'Silver / Black'],
            ['133', 'Black/Lead'],
            ['135', 'Gold/White'],
            ['137', 'Vilot/Lead'],
            ['145', 'Silver/Red '],
            ['165', 'Light Olive'],
            ['174', 'Orange/Lead'],
            ['191', 'White / Black'],
            ['195', 'Red/White/Yellew'],
            ['198', 'White/Green/Yellow'],
            ['206', 'White/Yellow/Red/Blue'],
            ['211', 'Light Blue'],
            ['216', 'Pearl Black'],
            ['218', 'Black/Red/Yellow'],
            ['244', 'Granite Crystal'],
            ['247', 'Maroon/Brown'],
            ['249', 'Black/Beige'],
            ['5', 'Yellow'],
            ['13', 'Beige'],
            ['25', 'White/Silver'],
            ['27', 'Black/Yellow'],
            ['38', 'White/Cream/Beige'],
            ['45', 'White / Lead'],
            ['54', 'Blue / Red'],
            ['58', 'Blue/ Black'],
            ['64', 'Dark Blue'],
            ['82', 'Black / Grey'],
            ['84', 'Dark Green'],
            ['91', 'Beige / White '],
            ['93', 'Blue/Orange'],
            ['96', 'Golden/Sliver'],
            ['100', 'Violet/Silver '],
            ['104', 'Blue/Green/Silver'],
            ['105', 'White/Orange/Black'],
            ['121', 'Red/Brown'],
            ['127', 'Red/Lead'],
            ['131', 'Orange/Yellow'],
            ['139', 'White/Red/Yellow'],
            ['140', 'Green / Red'],
            ['149', 'Black/Gold'],
            ['150', 'Blue/Beige'],
            ['156', 'Green/Blue/White'],
            ['157', 'Gold/Grey'],
            ['161', 'White/Blue/Yellow'],
            ['162', 'White / Gold'],
            ['164', 'Black/Orange/Grey'],
            ['180', 'Brown/Orange'],
            ['190', 'Yellow/Silver'],
            ['204', 'Pearl Blue'],
            ['205', 'White/Green/Yellow / Blue'],
            ['208', 'Green/Silver/Orange'],
            ['214', 'Silver / Red / Yellow'],
            ['220', 'White Blue Purple'],
            ['221', 'Green Blue Silver'],
            ['223', 'Purple Black'],
            ['226', 'Green/Blue'],
            ['234', 'Beige / Grey / Green'],
            ['235', 'Silver/Gold/Black'],
            ['243', 'White/Blue/Brown'],
            ['248', 'Beige/Maroon'],
            ['2', 'Black'],
            ['3', 'Red'],
            ['7', 'Brown'],
            ['10', 'Gold'],
            ['11', 'Orange'],
            ['16', 'Black/Red'],
            ['17', 'Green / Beige'],
            ['19', 'Maroon'],
            ['22', 'White/Green'],
            ['30', 'Green/Yellow/Black'],
            ['32', 'White/Red'],
            ['40', 'Yellow/White/Blue'],
            ['42', 'Yellow / White / Black'],
            ['49', 'Beige / Green'],
            ['52', 'Blue / Grey'],
            ['61', 'White / Grey'],
            ['63', 'White / Maroon'],
            ['66', 'Green / White'],
            ['73', 'Green/Lead'],
            ['86', 'Lead/Silver'],
            ['90', 'White / Violet'],
            ['95', 'Brown/Sliver'],
            ['97', 'Yellow/Red'],
            ['119', 'Silver / Orange'],
            ['134', 'Green/Gold'],
            ['136', 'Maroon/Grey'],
            ['138', 'Yellow / Black / Blue'],
            ['147', 'Carbon'],
            ['155', 'Red/Yellow/Orange'],
            ['159', 'Red/Blue'],
            ['176', 'Blue/Red/Silver'],
            ['177', 'White/Blue/Black'],
            ['178', 'White/Yellow/Blue'],
            ['182', 'Red/Green/Blue/White'],
            ['184', 'Silver/Blue/Maroon'],
            ['185', 'Silver/Grey/Maroon'],
            ['187', 'Unknown'],
            ['188', 'Pearl'],
            ['193', 'Gold/Green/Red'],
            ['196', 'Red/Maroon'],
            ['197', 'White/Orange/Green'],
            ['200', 'Light Green'],
            ['203', 'Grey/Brown'],
            ['219', 'Blue/White/Black'],
            ['222', 'Black/Yellow/Lead'],
            ['225', 'Blue Silver Orange'],
            ['228', 'Dark Steel Metallic'],
            ['229', 'Black Gry Red'],
            ['238', 'Orange/Black'],
            ['245', 'Mahogany'],
            ['246', 'Dark Amber'],
            ['14', 'Grey'],
            ['18', 'Lead'],
            ['23', 'Green/Black'],
            ['26', 'Black/Silver'],
            ['33', 'White/Orange'],
            ['34', 'White/Beige'],
            ['36', 'Yellow/Blue'],
            ['37', 'Cream'],
            ['51', 'Blue / Lead'],
            ['60', 'Grey / Silver'],
            ['69', 'Red / White'],
            ['76', 'Black/Green'],
            ['78', 'Beige /Brown '],
            ['94', 'Gold/Beige'],
            ['98', 'Gold / Brown '],
            ['108', 'Blue /White/Grey '],
            ['112', 'White/Yellow/Red'],
            ['115', 'Orange/Yellow/Black '],
            ['128', 'Brown/Grey'],
            ['132', 'Yellow/Red/White'],
            ['141', 'Maroon / Silver'],
            ['142', 'Silver/Green/Blue'],
            ['143', 'Green/Orange'],
            ['144', 'Maroon/Black'],
            ['146', 'Orange/White'],
            ['148', 'Brown/Black'],
            ['152', 'Green/Brown '],
            ['153', 'White/Blue/Green'],
            ['154', 'Beige / Blue'],
            ['158', 'Artic Frost'],
            ['160', 'Silver/White/Blue'],
            ['166', 'Sticker'],
            ['167', 'Pearl Light Blue'],
            ['169', 'White/Yellow'],
            ['170', 'Blue/Red/White'],
            ['171', 'Yellow/Green/Grey'],
            ['179', 'Red/Blue/White'],
            ['181', 'Orange/Green/Yellow/Red'],
            ['183', 'Grey/Maroon'],
            ['192', 'Black/Pink'],
            ['194', 'Blue/Green/Red'],
            ['199', 'Brown/Cream'],
            ['202', 'Pearl/White/Red'],
            ['207', 'Purple/Silver'],
            ['213', 'Blue / Pink '],
            ['224', 'White/Orange/Blue'],
            ['227', 'White Gry Orange'],
            ['230', 'Black/Red/Silver'],
            ['231', 'Black/Silver/Violet'],
            ['232', 'Black/Yellow/Gry'],
            ['236', 'White Pearl'],
            ['241', 'Blue/Rose'],
            ['242', 'White/Blue/Rose'],
        ];

        foreach ($colors as $color) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $color[0],
                'text' => $color[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function bankName()
    {
        $banks = [
            ['H-6008H', 'ABU DHABI INVESTMENT COUNCIL'],
            ['H-5441H', 'ABU DHABI NATIONAL ISLAMIC FINANCE'],
            ['PT268019', 'AL FUTTAIM CO LLC'],
            ['H-5014H', 'AL MULLA AUTOMOBILE'],
            ['H-5363T', 'ALRAYYAN BANK'],
            ['H-3033H', 'COMMERCIAL BANK INTL'],
            ['H-5387T', 'DOHA MARKETING SERVICE'],
            ['H-5437H', 'EMIRATES NBD'],
            ['H-4461H', 'ETISALAT'],
            ['H-5328H', 'AJMAN BANK PJSC'],
            ['H-4783H', 'ALI & SONS COMPANY'],
            ['H-5951H', 'ALWASIT MACHINERY EST'],
            ['H-4798H', 'ARABIAN AUTOMOBILES'],
            ['H-5390H', 'AUTO STAR TRADING'],
            ['H-4727H', 'COMMERCIAL BANK OF DUBAI'],
            ['H-5395T', 'IBIN AJAYAN AUTOMOBILES'],
            ['PT235174', 'MASRAF AL RAYAN'],
            ['H-5252H', 'MAWARID FINANCE'],
            ['H-5010H', 'NDC ADNOC'],
            ['TPQ00021T', 'QATAR AUTOMOBILES'],
            ['H-5570T', 'QATAR GAS TRANSPORT COMPANY LTD.(NAKILAT) (Q.S.C.)'],
            ['H-3034H', 'ABU DHABI COMMERCIAL BANK'],
            ['H-5988H', 'ARABIAN GULF MECHANICAL CENTRE'],
            ['H-5607H', 'BROUGE ABU DHABI'],
            ['H-4953H', 'EMIRATES INDUSTRIAL BANK'],
            ['H-4794H', 'FINANCE DEPARTMENT'],
            ['H-6186M', 'OMAN GULF ENTERPRISES'],
            ['H-4992H', 'SHARJAH ISLAMIC BANK'],
            ['H-5242H', 'THE PETROLEUM INSTITUTE'],
            ['H-5177H', 'ABU DHABI FOOD CONTROL AUTH.'],
            ['H-5171H', 'ABU DHABI RETIREMENT PENSIONS & BENEFITS FUNDS'],
            ['H-5313H', 'AL HILAL BANK'],
            ['H-5436T', 'AL JAZEERA ISLAMIC CO.'],
            ['H-4799H', 'BANK BANORABE'],
            ['H-6287M', 'BANK OF BEIRUT'],
            ['H-5040H', 'BOODAI TRADING COMPANY'],
            ['H-5474H', 'EMIRATES N.B.D'],
            ['H-4837H', 'JEBEL ALI  HOTEL & GOFL RESORT'],
            ['H-5379T', 'NASSER BIN KHALED & SONS'],
            ['H-4818H', 'NATIONAL AUTO'],
            ['H-4772H', 'NATIONAL BANK OF U.A.Q'],
            ['H-5186H', 'NATIONAL DRILLING CO.'],
            ['H-6115M', 'SATA LLC'],
            ['H-4913H', 'ABU DHABI AUDIT AUTHORITY'],
            ['H-5089H', 'AL HAI MOTORS'],
            ['H-5483H', 'AL KHALIJI FRANCE S.A.'],
            ['H-6423H', 'ALHAIL ORIX FINANCE PSC'],
            ['H-4749H', 'ARAB BANK'],
            ['H-5067H', 'DARWISH BIN AHMED & SONS'],
            ['H-5381T', 'GULF AUTOMOBILES'],
            ['H-5055H', 'RAFIDAIN BANK'],
            ['H-5355H', 'SHARJAH BANK'],
            ['H-5056H', 'SPANISH TRADING'],
            ['H-4752H', 'WESTERN MOTORS'],
            ['PT410372', 'FIRST ABU DHABI BANK'],
            ['H-5766H', 'AL HABTOOR  ROYAL CAR LLC'],
            ['H-5554T', 'ALLJARAH-NATIONAL LEASING HOLDING'],
            ['H-4830H', 'BANK MELLI IRAN'],
            ['H-4937H', 'BANK SADERAT IRAN'],
            ['H-5440T', 'DOHA ISLAMIC BANK'],
            ['H-5086H', 'ELITE MOTORS'],
            ['H-5364H', 'ESNAAD'],
            ['H-5394H', 'EXECUTIVE AFFAIRS AUTHORITY'],
            ['H-4893H', 'GALADARI AUTOMOBILES'],
            ['H-4770H', 'NATIONAL BANK OF SHARJAH'],
            ['H-6104M', 'NATIONAL FINANCE COMPANY SAOG'],
            ['H-5595H', 'PRESTIGE SHOW ROOM'],
            ['H-5254H', 'SAEED MOHAMED AL GHANDI & SONS'],
            ['H-5777H', 'AL MAZAYAH AL AULAH GEN. TRAD.(LLC)'],
            ['H-5404T', 'AL-KHALIJ COMMERCIAL BANK (AL KHALIJI) Q.S.C'],
            ['H-5364T', 'ARAB BANK LIMITED'],
            ['H-4784H', 'BEL HASA TRADING AND DEV CO., L.L.C'],
            ['H-4891H', 'BIN BROOKE MOTORS & EQUIPMENTS (LLC)'],
            ['H-5616H', 'EMIRATES NUCLEAR ENERGY CORPORATION'],
            ['H-5154H', 'FINANCE HOUSE'],
            ['H-5385T', 'JAIDAH MOTORS CO.'],
            ['H-4971H', 'MOTOR AGENCIES CENTRE'],
            ['H-4693H', 'NATIONAL BANK OF ABU DHABI'],
            ['H-5843H', 'ADCB / ISLAMIC  BANKING DIVISION'],
            ['PT168648', 'AL KHALIJ INVESTMENT'],
            ['H-5952H', 'AL MAZAYAH AL AULAH GENERAL TRADING LLC'],
            ['H-5230H', 'BEL HASA MOTORS'],
            ['H-3012H', 'DUBAI ISLAMIC BANK'],
            ['H-5550H', 'DUBAI PETROLEUM'],
            ['H-4771H', 'FIRST ABU DHABI ISLAMIC FINANCE COMPANY'],
            ['H-4813H', 'GENAVCO L.L.C'],
            ['H-4777H', 'JUMA AL MAJID EST.'],
            ['H-6347H', 'MIRAL ASSET MANAGEMENT LLC'],
            ['H-5272H', 'NOOR ISLAMIC BANK'],
            ['H-5604H', 'OFFSET PROGRAM BUREAU'],
            ['H-5466T', 'QATAR GAS'],
            ['H-5374T', 'QATAR ISLAMIC BANK'],
            ['H-3023H', 'R.A.K. BANK'],
            ['H-6371H', 'RAK BANK ISLAMIC'],
            ['H-5492T', 'SAAD BUZWAIR AUTOMOTIVE'],
            ['H-5383T', 'SALEH AL-HAMAD AL-MANA'],
            ['H-4995H', 'ABU DHABI IVESTMENT COMPANY'],
            ['H-5326H', 'ADMA OPCO'],
            ['H-5503H', 'ARAB BANK FOR INVESTMENT & FOREIGN TRADE'],
            ['H-5091H', 'B.N.P. PARIBAS'],
            ['H-4829H', 'BANK OF BARODA'],
            ['H-5475T', 'BARWA BANK  QATAR'],
            ['H-5368T', 'COMMERCIAL BANK OF QATAR'],
            ['H-5399T', 'DOHA AUTOMOBILE COMPANY'],
            ['PT164604', 'ENERGY DOLPHEN LTD'],
            ['H-5287H', 'GALADARI TRUCKS AND HEAVY EQUIPMENT CO. LTD.'],
            ['H-5573T', 'GULF DRILLING INTERNATIONAL LTD (Q.S.C)'],
            ['H-4914H', 'LLOYDS TSB BANK PLC'],
            ['H-3010H', 'MEFCO'],
            ['H-5406T', 'NASSER BIN KHALED AL- THANI &SONS'],
            ['H-5441T', 'QATAR PETROLEUM'],
            ['H-6341H', 'SCB'],
            ['H-6105M', 'TAAGEER FINANCE COMPANY SAOG'],
            ['H-6485H', 'TAWAZUN ECONOMIC COUNCIL'],
            ['H-6090H', 'ABU DHABI CO. FOR ONSHORE OIL OPOERATIION (ADCO)'],
            ['H-5046H', 'AL FUTTAIM AUTOMALL'],
            ['H-5453T', 'AL SAFA ISLAMIC BANK'],
            ['H-4792H', 'BANQUE LIBANAISE POUR LE COMMERCE (FRANCE)'],
            ['H-4803H', 'NATIONAL BANK OF DUBAI'],
            ['H-5391T', 'NATIONAL CAR CO.'],
            ['H-6106M', 'OMAN ORIX LEASING COMPANY SAOG'],
            ['H-5375T', 'QATAR NATIONAL BANK'],
            ['PT246548', 'S D E EQUIPMENT TRADING LLC'],
            ['H-5152H', 'TAKREER'],
            ['H-5265H', 'TAMWEEL'],
            ['H-5476T', 'UNITED CARS AL MANA'],
            ['H-6102M', 'AL OMANIYA FINANCIAL SERVICES SAOG'],
            ['H-5103H', 'AL YOUSUF LLC'],
            ['H-5393T', 'AL-HAMAD AUTOMOBILES CO.'],
            ['H-5759H', 'ETIHAD RAIL CO. PJSC'],
            ['H-5312H', 'HILAL BANK'],
            ['H-5033H', 'HSBC'],
            ['H-4807H', 'SWAIDAN TRADING CO.'],
            ['H-5347H', 'ABU DAHBI NATIONAL ISLAMIC FINANCE'],
            ['PT237462', 'ABU DHABI NATIONAL TANKER COMPANY'],
            ['H-5397H', 'AL DUNIA FINANCE LLC'],
            ['H-5749G', 'EMIRATES STEEL INDUSTRIES'],
            ['PT276915', 'FERTIL'],
            ['H-4793H', 'LIBERTY AUTOMOBILES'],
            ['H-6235H', 'MUBADALA G.E CAPITAL (PJSC)'],
            ['H-5058H', 'PREMIER MOTORS'],
            ['H-5178H', 'ABU DHABI NATIONAL OIL CO.'],
            ['H-4922H', 'AL GHANDI AUTO'],
            ['H-5386T', 'AL-MANA MOTORS'],
            ['H-5244H', 'BOROUGE'],
            ['H-5053H', 'DALMA MOTORS'],
            ['H-5129H', 'MUSCAT BANK'],
            ['H-6109M', 'OMAN MARKETING & SERVICES CO. (OMASCO)'],
            ['H-5443T', 'QATAR FINANCE HOUSE'],
            ['H-5407T', 'QATAR INTERNATIONAL BANK'],
            ['H-5983H', 'RAK MOTORS'],
            ['H-6108M', 'ZUBAIR AUTOMOTIVE LLC'],
            ['H-4460H', 'AL FUTTAIM MOTORS'],
            ['H-4490H', 'AL MAJID MOTORS'],
            ['H-5017H', 'AL WAHDA CAR SHOWROOM'],
            ['H-4968H', 'ARAB AFRICAN BANK INTERNATIONAL'],
            ['H-6112M', 'BANK MUSCAT AUTO LOAN'],
            ['H-3015D', 'BANK OF ABUDHABI'],
            ['H-5400T', 'DOHA SERVICES MARKETING COMPANY'],
            ['H-5402H', 'DUNIA FINANCE L L C'],
            ['H-5416H', 'EMIRATES CENTRAL BANK'],
            ['H-5401H', 'EMIRATESMONEY'],
            ['H-4478H', 'HSBC-MEFCO'],
            ['H-5370T', 'INTERNATIONAL BANK OF QATAR'],
            ['H-5461H', 'ISLAMIC FINANCE HOUSE - PVT - JSC'],
            ['H-4892H', 'MAF ORIX FINANCE PJSC'],
            ['H-5389H', 'OMER BIN YOUSSEF & SONS'],
            ['H-5473H', 'PETROLEUM INSTITUTE'],
            ['H-6239H', 'RAK BANK ISLAMIC DIVISION (AMAL)'],
            ['H-4747H', 'ABU DHABI ISLAMIC BANK'],
            ['H-5380T', 'AL FARDAN AUTOMOBILES'],
            ['H-5478T', 'AL TADAMON MOTORS & TRADING'],
            ['H-5948H', 'BIN HAMOODAH TRADING AND GENERAL SERVICES'],
            ['H-5338H', 'CATERPILLAR FINANCIAL SERVICES'],
            ['H-5294H', 'DUBAI FIRST'],
            ['H-4952H', 'EL NILEIN BANK'],
            ['H-5581H', 'ISLAMIC FINANCE COMPANY'],
            ['H-5557T', 'OBAIKAN EQUIPMENT & SERVICES W.L.L'],
            ['H-5410T', 'QATAR NAVIGATION'],
            ['H-5284H', 'REEM FINANCE'],
            ['H-5468H', 'ABU DHABI FUTURE ENERGY COMPANY (MASDAR)'],
            ['H-6068H', 'AL KHALIJI'],
            ['H-4820H', 'AL MASOOD MOTORS'],
            ['H-5011H', 'AL SHIRAWI ENTERPRISES'],
            ['H-5403T', 'FIRST FINANCE'],
            ['H-5299T', 'HSBC MIDDLE EAST LIMITED - QATAR'],
            ['H-5346H', 'JANATA BANK'],
            ['H-3013H', 'MASHREQ BANK'],
            ['H-4713H', 'NATIONAL BANK OF RAS AL KHAIMAH'],
            ['H-6151M', 'OMAN ARAB BANK (SAOC)'],
            ['H-5539T', 'Q-AUTO'],
            ['H-6110M', 'SUHAIL BAHWAN AUTOMOBILES LLC'],
            ['H-5866H', 'AL FUTTAIM FINANCE'],
            ['H-5341H', 'AL MASARAF'],
            ['H-4934H', 'AL ROSTMANI TRADING'],
            ['H-4909H', 'AL RUMAISI ESTABLISHMENT'],
            ['H-4814H', 'DUBAI BANK'],
            ['H-5009H', 'EMIRATES ISLAMIC BANK'],
            ['H-5215H', 'FIRST LEASING BANK BSCC'],
            ['H-5022H', 'GARGASH ENTERPRESIS'],
            ['H-4700H', 'INVEST BANK'],
            ['H-3011H', 'OSOOL FINANCE COMPANY'],
            ['H-5382T', 'ABDULLAH BBDULGHANI & BROTHERS'],
            ['H-5362T', 'ALAHLI BANK OF QATAR'],
            ['H-5141H', 'ARAB BANK OF FOREIGN INVESTMENT & TRADE'],
            ['H-5570H', 'DOLPHIN ENERGY COMPANY'],
            ['H-5789H', 'HEIDELBERG GULF EST.'],
            ['H-4811H', 'NATIONAL BANK OF FUJAIRAH'],
            ['H-6116M', 'OMAR ZAWAWI ESTABLISHMENT LLC (OMZEST)'],
            ['H-5536T', 'RAS GAS'],
            ['H-6111M', 'SAUD BAHWAN AUTOMOTIVE'],
            ['H-5390T', 'TALEB TRADING CO.'],
            ['H-5179H', 'ABU DHABI NATIONAL OIL COMPANY'],
            ['H-5255H', 'AL AHLI BANK OF KUWAIT'],
            ['H-5233H', 'AL BADR ISLAMIC FINANCE COMPANY'],
            ['H-4791H', 'BIN DHAHER TRADING ENTERPRISES'],
            ['H-4459H', 'HABIB BANK AG ZURICH'],
            ['H-5888H', 'MASHREQ AL ISLAMI'],
            ['H-6148M', 'MUSCAT FINANCE COMPANY LTD. (SAOG)'],
            ['H-5125H', 'NATIONAL BANK OF OMAN'],
            ['H-5376T', 'SHAMIL BANK OF BAHRAIN'],
            ['H-4786H', 'SOC. CARE & MINOR AFFAIRS - AUH'],
            ['H-4819H', 'TRADING ENTERPRISES'],
            ['H-5378T', 'UNITED BANK LTD.'],
            ['H-5210H', 'UNITED MOTORS & HEAVY EQUIPMENT CO.'],
            ['H-5259H', 'ABU DHABI MOTORS CO'],
            ['H-4828H', 'AL FUTTAIM AUTO &  MACHINERY CO.'],
            ['H-6117M', 'AL JENAIBI INTERNATIONAL AUTOMOBILES LLC'],
            ['H-4781H', 'AL MASRAFARAB BANK FOR INVESTMENT& FOREIGN. TR'],
            ['H-4480H', 'AL YOUSUF MOTORS'],
            ['H-5392T', 'AL-ATTIYA MOTORS AND TRADING CO.'],
            ['H-5180H', 'BADR AL ISLAMI'],
            ['H-5590H', 'GASCO'],
            ['H-5304H', 'KHALIFA FUND'],
            ['H-5372T', 'QATAR INDUSTRIAL DEVELOPMENT BANK'],
            ['PT164681', 'RAK BANK'],
            ['H-4750H', 'ABU DHABI INVESTMENT AUTHORITY'],
            ['H-5403H', 'ABU DHABI PORTS COMPANY'],
            ['H-5477H', 'ADIA'],
            ['H-5565T', 'AL TASHILAT ISLAMIC CO-ARAB BANKING FINANCE'],
            ['H-4458H', 'AL TAYER MOTORS'],
            ['H-4496H', 'GULF FINANCE CORPORATION'],
            ['H-5281H', 'HSBC(AMANAH)'],
            ['H-5594H', 'ISLAMIC FINANCE COMANY - AAFAQ'],
            ['H-4766H', 'ME BANK'],
            ['H-5166H', 'MUBADALA DEVELOPMENT'],
            ['H-5360H', 'NATIONAL BANK OF BAHRAIN'],
            ['H-5148H', 'UNITED BANK LIMITED'],
            ['H-6113M', 'UNITED FINANCE COMPANY SAOG'],
            ['H-5743H', 'ADGAS'],
            ['H-5195H', 'B. L. C. BANK (FRANCE)'],
            ['H-5159H', 'BLOM BANK FRANCE'],
            ['H-6375H', 'BMW ALBATHA FINANCE P.S.C.'],
            ['H-4505H', 'CENTRAL BANK'],
            ['H-5042H', 'EMIRATES AIR LINES'],
            ['H-4975H', 'EMIRATES BANK'],
            ['H-5864H', 'EMIRATES MOTOR COMPANY /ALFAHIM GROUP'],
            ['H-4716H', 'FUJAIRAH TRADING COMPANY'],
            ['H-4738H', 'LLOYDS BANK'],
            ['H-5838H', 'MEDIA ZONE AUTHORITY'],
            ['H-5521T', 'NASSER BIN KHALED AUTOMOBILES'],
            ['H-5373T', 'QATAR INTERNATIONAL ISLAMIC BANK'],
            ['H-4723H', 'UNION NATIONAL BANK'],
            ['H-4912H', 'UNITED DIESEL'],
            ['H-5187H', 'WESTERN AUTO LLC'],
            ['H-4493H', 'ABN AMRO BANK'],
            ['H-4494H', 'AL HABTOOR MOTORS'],
            ['H-4742H', 'BANK OF SHARJAH'],
            ['H-5301H', 'FALCON MOTORS'],
            ['H-3018H', 'MIDDLE EAST BANK'],
            ['H-6114M', 'OMAN TRADING EST.'],
            ['H-5384T', 'QATAR AUTOMOBILES COMPANY'],
            ['H-5253H', 'ZADCO'],
            ['H-4985H', 'AMLAK FINANCE'],
            ['H-5446H', 'ARAB BANK FOR INVESTMENT'],
            ['H-5003H', 'BNP PARIBAS'],
            ['H-4866H', 'EMIRATES FINANCE COMPANY'],
            ['H-5307H', 'MOHAMED ABDUL RAHMAN AL BAHAR'],
            ['H-4760H', 'UNITED MOTOR COMPANY'],
            ['PT204559', 'AL AHLI BANK OF QATAR'],
            ['H-4761H', 'AL NABOODA MOTORS'],
            ['H-5388T', 'AL-MANAI TRADING CO.'],
            ['H-3017H', 'CITIBANK'],
            ['H-4964H', 'DYNA TRADE'],
            ['H-5366H', 'EMIRATES MONEY CONSUMER FINANCE LLC'],
            ['H-5978H', 'HABIB BANK LTD'],
            ['H-4502H', 'JUMAL AL MAJID MOTOR'],
            ['H-5389T', 'TAYSEER MOTORS'],
            ['H-3014H', 'UNITED ARAB BANK'],
            ['PT662547', 'DEEM FINANCE L.L.C'],
            ['PT779704', 'Banque Banorient France'],
            ['PT716635', 'INTER EMIRATES MOTORS LLC'],
            ['PT482135', 'ABU DHABI FINANCE PJSC'],
            ['PT426939', 'M/S. ABU DHABI COMMERCIAL BANK PJSC'],
            ['PT424265', 'KANOO MACHINERY LLC'],
            ['PT421989', 'KHALEEJI COMMERCIAL BANK BSC'],
            ['PT407740', 'AL HAIL ORIX FINANCE PSC'],
            ['PT360641', 'ARAB BANK '],
            ['PT342311', 'AAFAQ ISLAMIC FINANCE P.S.C'],
            ['PT337024', 'Emirates Investment Authority (EIA)'],
            ['PT332202', 'UNION MOTORS LLC'],
            ['PT318449', 'TEYSEER GROUP'],
            ['PT302692', 'QATAR TRACTOR & EQUIPMENT CO. W.L.L'],
            ['PT298022', 'ABU DHABI COMMERCIAL ISLAMIC FINANCE'],
            ['PT204525', 'BANK MISR'],
            ['BK6539H', 'HSBC BANK MIDDLE EAST LIMITED'],
            ['PT180395', 'NOOR BANK'],
            ['H-6309H', 'BANQUE MISR'],
            ['H-6292H', 'NOOR BANK'],
            ['QCT99992Q', 'THE NATIONAL BANK OF RAS AL KHAIMAH -BM'],
            ['I1291745H', 'COMMERCIAL BANK INTERNATIONAL P.J.S.C'],
            ['H-5561H', 'AL WIFAQ FINANCE COMPANY'],
            ['I753387H', 'AL TAYER MOTORS LLC'],
            ['I721741H', 'ARAB BANK'],
            ['H-5469H', 'AL WIFAQ FINANCE COMPANY'],
            ['H-5406H', 'HSBC BANK MIDDLE EAST LIMITED'],
            ['H-5377T', 'STANDARD CHARTERED BANK'],
            ['H-5361T', 'DOHA BANK'],
            ['I58002H', 'AJMAN BANK'],
            ['I301540H', 'COMMERCIAL BANK OF DUBAI'],
            ['H-5243H', 'DOHA BANK'],
            ['H-5124H', 'AUTO PLUS'],
            ['H-4970H', 'BLC BANK (FRANCE)'],
            ['H-4969H', 'BLC BANK (FRANCE)'],
            ['APA02180A', 'AL ROSTAMANI TRADING COMPANY'],
            ['I370967D', 'HSBC  BANK MIDLE EAST,DUBAI'],
            ['BPA02114B', 'AL ROSTAMANI TRADING COMPANY'],
            ['H-6103M', 'AUTO PLUS'],
            ['H9G0042H', 'GENERAL NAVIGATION & COMMERCE CO. LLC'],
            ['A9A0026A', 'AL MASOOD AUTOMOBILES'],
            ['H-3008H', 'STANDARD CHARTERED BANK'],
        ];

        foreach ($banks as $bank) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::BANK_NAME,
                'code' => $bank[0],
                'text' => $bank[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
