<?php

namespace Database\Seeders;

use App\Enums\InsuranceProvidersEnum;
use App\Enums\LookupsEnum;
use App\Enums\QuoteTypeId;
use App\Models\InsuranceProvider;
use App\Models\Lookup;
use Illuminate\Database\Seeder;

class CarGIGVehicleTransactionDriverDetailsForAMLSeeder extends Seeder
{
    private $insuranceProviderId;

    public function __construct()
    {
        $this->insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::AXA)
            ->select(['id', 'code'])
            ->first()->id;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $this->rtaTransactionType();
        // $this->rtaPlateCategory();
        // $this->vehicleColor();
        // $this->bankName();

        // Add extra vehicle colors requested by Business
        $this->extraVehicleColors();
    }

    private function rtaTransactionType()
    {
        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'RTT01',
            'text' => 'New Vehicle Registration',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'RTT03',
            'text' => 'Change Vehicle Ownership',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'RTT04',
            'text' => 'Vehicle Renewal',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_TRANSACTION_TYPE,
            'code' => 'RTT10',
            'text' => 'Vehicle Renewal with Change Number',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function rtaPlateCategory()
    {
        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => 'RPC01',
            'text' => 'Classical',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => 'RPC02',
            'text' => 'Consulate',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => 'RPC03',
            'text' => 'Delegate',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => 'RPC04',
            'text' => 'Private',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Lookup::firstOrCreate([
            'quote_type_id' => QuoteTypeId::Car,
            'key' => LookupsEnum::RTA_PLATE_CATEGORY,
            'code' => 'RPC05',
            'text' => 'Motorcycle',
            'insurance_provider_id' => $this->insuranceProviderId,
        ], [
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function vehicleColor()
    {
        $colors = [
            '0' => 'Black',
            '1' => 'Blue',
            '2' => 'White',
            '4' => 'Red',
            '6' => 'Brown',
            '8' => 'Green',
            '9' => 'Silver',
            '11' => 'Arctic',
            '13' => 'Maroon',
            '16' => 'Turquoise',
            '18' => 'Olive',
            '19' => 'Ivory',
            '20' => 'Bronze',
            '21' => 'Brown+Silver',
            '23' => 'Beige+Blue',
            '24' => 'Beige+Green',
            '27' => 'Beige+Silver',
            '28' => 'Beige+Silver+Grey',
            '29' => 'Black+Beige',
            '31' => 'Copper',
            '32' => 'Black Cherry',
            '33' => 'Black+Gold',
            '37' => 'Khaki',
            '38' => 'Light Brown',
            '39' => 'Light Grey',
            '40' => 'Black+Grey',
            '42' => 'Black+Yellow',
            '43' => 'Blue+Green',
            '45' => 'Blue+Black',
            '46' => 'Blue+Brown',
            '49' => 'Blue+White',
            '50' => 'Blue+Yellow',
            '51' => 'Brown+Grey',
            '52' => 'Brown+Beige',
            '54' => 'Light Yellow',
            '55' => '-',
            '56' => 'Blue+Beige',
            '59' => 'Dark Blue',
            '60' => 'Dark Blue+Light Blue',
            '61' => 'Dark Bluish Grey',
            '63' => 'Dark Grey',
            '65' => 'Gold+Dark Green',
            '66' => 'Gold+Silver',
            '67' => 'Green+Bronze',
            '70' => 'Green+Black',
            '71' => 'Green+White',
            '72' => 'Green+Yellow',
            '73' => 'Silver+Beige+Green',
            '74' => 'Light Olive',
            '75' => 'Maroon+Black',
            '76' => 'Maroon+Gold',
            '79' => 'Violet+White+Black',
            '80' => 'Green+Gold',
            '82' => 'Navy Blue',
            '83' => 'White+Beige',
            '84' => 'White+Blue',
            '85' => 'White+Gold',
            '86' => 'White+Grey',
            '87' => 'White+Silver',
            '88' => 'White+Yellow',
            '91' => 'Purple+Grey',
            '92' => 'Purple+Silver',
            '94' => 'Red+Brown',
            '96' => 'Red+Black',
            '98' => 'Red+Silver',
            '99' => 'Red+Gold',
            '100' => 'Silver+Brown',
            '102' => 'Silver+Red',
            '103' => 'White+Blue+Orange',
            '104' => 'White+Blue+Purple',
            '105' => 'White+Brown',
            '108' => 'White+Red',
            '110' => 'Yellow+Grey',
            '112' => 'Silver+Gray',
            '113' => 'Light Green',
            '114' => 'Beige+White',
            '115' => 'Titanium Silver',
            '116' => 'Ring Silver',
            '117' => 'Orange+Grey',
            '119' => 'Orange+Black',
            '121' => 'Beige+Gold',
            '122' => 'Grey+Green',
            '123' => 'Black+Red',
            '124' => 'White+Blue+Grey',
            '127' => 'Yellow+Blue+Green',
            '128' => 'Orange+Blue',
            '129' => 'Maroon+Beige',
            '130' => 'Light Gold',
            '131' => 'Green+Beige',
            '132' => 'White+Red+Blue',
            '133' => 'Yellow+Black+White',
            '134' => 'Grey+Violet',
            '135' => 'Blue+White+Red',
            '136' => 'Blue+Red+White',
            '138' => 'Orange+Grey+Red',
            '140' => 'Grey+Purple',
            '141' => 'Orange+White',
            '142' => 'White+Chocolate+Graphics',
            '143' => 'White+Graphics',
            '144' => 'Grayish Purple',
            '145' => 'Blue+White+Yellow',
            '146' => 'White+Yellow+Graphics',
            '147' => 'White+Green+Graphics',
            '148' => 'White+Graphics+Green',
            '149' => 'Brown+Green',
            '150' => 'Pearl Grey',
            '152' => 'Metallic Grey',
            '153' => 'White+Orange+Graphics',
            '156' => 'Gold+Maroon',
            '157' => 'Shining Green',
            '158' => 'White+Red+Graphics',
            '159' => 'White+Blue+Graphics',
            '161' => 'Red+White+Graphics',
            '162' => 'Orange+Green',
            '164' => 'Chocolate',
            '165' => 'Green+Silver+White',
            '172' => 'Grey+Silver',
            '173' => 'Grey+White',
            '174' => 'Maroon+White+Graphics',
            '177' => 'Silver+Grey',
            '178' => 'Silver+Beige',
            '181' => 'White+Milky+Graphics',
            '182' => 'Orange+Yellow',
            '184' => 'Orange+Grey+Green',
            '185' => 'Black+White+Graphics',
            '186' => 'Red+White',
            '187' => 'Orange+Red+Grey',
            '188' => 'White+Blue+Green',
            '190' => 'Yellow+Red+Graphics',
            '192' => 'Orange+Graphics',
            '193' => 'Beige+Green+Silver',
            '194' => 'Sparkling Graphite',
            '196' => 'Golden+White',
            '200' => 'Champagne',
            '201' => 'Oak',
            '203' => 'Red+Yellow',
            '204' => 'Black+Red+White',
            '206' => 'Olive Green',
            '210' => 'Red+Yellow',
            '211' => 'Sliver',
            '212' => 'Silver+Yellow',
            '213' => 'White+Yellow Line',
            '214' => 'White+Blue+Yellow',
            '215' => 'White+Red+Black',
            '216' => 'Yellow+Blue+White',
            '218' => 'Black+Navy Blue',
            '219' => 'Pink+Red',
            '220' => 'Dark Red',
            '221' => 'White+Orange',
            '222' => 'White+Black',
            '223' => 'Blue+Grey+Orange',
            '227' => 'White+Blue+Brown',
            '230' => 'Pink+White',
            '231' => 'Red+Blue',
            '232' => 'Beige+Yellow+Green+Brown',
            '233' => 'Blue+Cream',
            '236' => 'Silver+Blue',
            '237' => 'Blue+Red',
            '240' => 'Green+Blue',
            '241' => 'Grey+Orange',
            '242' => 'Grey+Yellow',
            '243' => 'Yellow+Green',
            '245' => 'Gold+Brown',
            '247' => 'Yellow+White+Advertising Sticker',
            '248' => 'Yellow+White+Graphics',
            '249' => 'Green+Advertising Sticker',
            '250' => 'Metallic Silver',
            '251' => 'Pearl White+Beige',
            '253' => 'Yellow+Green+Grey',
            '254' => 'Yellow+Blue',
            '255' => 'Yellow+Green+White',
            '256' => 'White+Orange+Blue',
            '257' => 'Yellow+Orange+Blue',
            '258' => 'Brown+White',
            '260' => 'Silver+Purple',
            '262' => 'Violet+Red+Beige+White',
            '263' => 'Black+Orange',
            '265' => 'Orange+Silver',
            '267' => 'Sky Blue',
            '269' => 'White+Maroon',
            '270' => 'Yellow+Red+White',
            '271' => 'White+Red+Yellow',
            '272' => 'Grey+Blue+Orange',
            '273' => 'White+Black+Green',
            '275' => 'Dark Copper',
            '276' => 'Aluminum',
            '277' => 'Red+Orange',
            '279' => 'Blue+Orange',
            '280' => 'Graphics+Red+Grey',
            '282' => 'Graphics',
            '283' => 'Graphics+Yellow+White',
            '284' => 'White+Graphics+Red',
            '286' => 'Blue+Green+Graphics',
            '287' => 'Blue+Graphics',
            '289' => 'Red+Graphics',
            '290' => 'Graphics+White+Red',
            '292' => 'White+Grey+Graphics',
            '295' => 'Grey+Brown',
            '296' => 'White+Advertising Sticker',
            '297' => 'Brown+Cream',
            '299' => 'White+Graphics+Yellow',
            '300' => 'Green+Brown+Beige+Yellow',
            '302' => 'Grey+Graphics+Black',
            '304' => 'Lead+Blue',
            '305' => 'Yellow+Graphics',
            '306' => 'Maroon+Yellow',
            '308' => 'Black+Red+Graphics',
            '310' => 'White+Rose+Graphics',
            '311' => 'Black+Orange+Yellow',
            '313' => 'Leady',
            '314' => 'Silver+Graphics',
            '315' => 'Red+Blue+Graphics',
            '317' => 'White+Graphics+Brown',
            '319' => 'Orange+Advertisement',
            '320' => 'White+Green+Brown',
            '321' => 'White+Blue+Graphics',
            '323' => 'Brown & Purple',
            '324' => 'MAROON+GREY+GRAPHIC',
            '325' => 'Grey+Red+Graphics',
            '326' => 'Pearl Beige',
            '327' => 'Yellow+Beige',
            '328' => 'Light Green+Grey+Black',
            '330' => 'Brown+Black',
            '331' => 'Red+Blue+Yellow',
            '332' => 'Maroon+Grey+Graphics',
            '341' => 'Black+Silver+Graphics',
            '342' => 'Yellow+Purple+Graphics',
            '350' => 'Red+Grey+Graphics',
            '351' => 'Orange+Grey+Black',
            '360' => 'Orange+Graphics+Blue',
            '388' => 'Blue+White+Graphics',
            '390' => 'Black+Milk',
            '400' => 'Brown+Orange',
            '401' => 'White+Yellow+Red',
            '402' => 'Grey+Orange+Green',
            '403' => 'Black+Maroon',
            '410' => 'White+Purple+Graphics',
            '411' => 'Grey+Beige',
            '412' => 'Green+Blue+Grey',
            '413' => 'Blue+Green+Yellow',
            '414' => 'Black+Grey+Graphics',
            '418' => 'Graphics+White',
            '422' => 'Red+Grey+Advertising',
            '424' => 'Silver+Aluminium',
            '426' => 'Purple+Gold+Graphics',
            '428' => 'White+Black+Orange',
            '429' => 'White+Graphics+Red',
            '430' => 'White+Maroon+Graphics',
            '432' => 'Black+White+Orange',
            '433' => 'Red+Yellow+Orange',
            '434' => 'Lead+Yellow',
            '435' => 'Orange+Beige',
            '436' => 'Grey+Orange+White',
            '438' => 'Grayish Brown',
            '440' => 'Pearl',
            '441' => 'Black Pearl',
            '442' => 'Blue+Yellow+Graphics',
            '443' => 'Blue+Orange+Graphics',
            '444' => 'White+Red+Silver',
            '445' => 'Beige+Brown',
            '446' => 'White+Lead',
            '447' => 'Deep Cherry Red',
            '448' => 'Silver+Black+Graphics',
            '449' => 'Black+Blue+Advertising Sticker',
            '451' => 'Dark Brown',
            '452' => 'Orange+Red+Graphics',
            '453' => 'Yellow+Blue+Graphics',
            '455' => 'Silver+Black',
            '456' => 'Grey+Graphics',
            '457' => 'White+Brown+Graphics',
            '458' => 'Red+Led',
            '459' => 'White+Orange+Grey',
            '460' => 'Gold+Silver+Advertising Sticker',
            '461' => 'Black+Orange+Graphics',
            '462' => 'Black+Orange+Graphics',
            '464' => 'Pearl White+Graphics',
            '465' => 'Black+Blue',
            '467' => 'Pearl+Blue',
            '468' => 'Silver+Maroon+Graphics',
            '471' => 'Lemony',
            '472' => 'Graphics+Blue+Black',
            '475' => 'Blue+Black+Graphics',
            '479' => 'Black+White+Red',
            '480' => 'Black+White+Purple',
            '481' => 'Blue+Red+Graphics',
            '485' => 'Orange+White+Graphics',
            '489' => 'Gold+Red+Graphics',
            '491' => 'Yellow+Green+Blue',
            '495' => 'White+Trade Name',
            '496' => 'White+Graphics+Blue',
            '497' => 'White+Black+Blue',
            '499' => 'Purple+White+Graphics',
            '500' => 'Green+Blue+Yellow',
            '501' => 'Black+Yellow+Graphics',
            '502' => 'Red+White+Trade name',
            '505' => 'Red+Yellow+Graphics',
            '506' => 'Brown+Red',
            '507' => 'Green+White+Graphics',
            '509' => 'Orange+Beige+Grey',
            '510' => 'Yellow+Orange+Grey',
            '515' => 'AMETHYST',
            '517' => 'BLACK,WHI,VIO,YELLOW',
            '518' => 'Blank',
            '519' => 'BLONDIE',
            '522' => 'Blue+Silver+Graphics',
            '524' => 'BLULTBLUE',
            '526' => 'BROWN+PURPLE',
            '527' => 'CHERRY',
            '530' => 'CREAMY',
            '531' => 'DARKBLUE',
            '532' => 'DARKGREEN',
            '533' => 'GRAPHITE',
            '535' => 'GREEN+GREY',
            '537' => 'Grey+Black+White',
            '538' => 'Grey+White+Back',
            '539' => 'GREY+WHITE+BLUE',
            '540' => 'GREYISHBLUEMETALLIC',
            '543' => 'LEAD',
            '545' => 'METALLIC',
            '546' => 'ODYSSEY',
            '547' => 'PEARLWHITE',
            '548' => 'PEARLWHITE+BEIGE',
            '549' => 'PLATINUIM',
            '550' => 'PLUM',
            '551' => 'PURPLE',
            '552' => 'RED+SILVER',
            '553' => 'RED+WHITE+GREEN',
            '554' => 'RED+GREY',
            '556' => 'Rose',
            '558' => 'SILVER+GRAPHITE',
            '559' => 'SILVER2',
            '560' => 'TEST',
            '565' => 'WHITE+GREY',
            '566' => 'WHITE+SILVER',
            '567' => 'WHITE+BEIGE',
            '568' => 'MAROON+RINGSILVER',
            '569' => 'RED+RINGSILVER',
            '570' => 'WHITE+GREEN+SILVER',
            '571' => 'BURGUNDY+SILVER',
            '573' => 'BURGUNDY+ORANGE',
            '574' => 'WHITE+BLACK+BLUE',
            '575' => 'Orange+Maroon',
            '576' => 'White+Yellow+Purple+Graphics',
            '577' => 'White+Black+Red+Graphics',
            '580' => 'Blue+White+Black',
            '589' => 'Brown+White+Graphics',
            '590' => 'Brown+Graphics',
            '597' => 'Grey+Graphics+White',
            '598' => 'Sky Blue+White',
            '599' => 'Blue+Red+White+Graphics',
            '601' => 'Blue+White+Trade name',
            '603' => 'White+Red+Black+Graphics',
            '605' => 'Graphics+Blue+Yellow',
            '610' => 'Green+Grey+Yellow',
            '612' => 'Black+Trade Name',
            '620' => 'Blue+Grey+Black',
            '621' => 'Red+Grey+Black',
            '650' => 'Black+Red+Blue',
            '656' => 'Gold+Beige+Graphics',
            '687' => 'Orange+Trade Name',
            '688' => 'Blue+Yellow+Orange',
            '695' => 'White+Orange+Trade name',
            '702' => 'Pink+Blue+Graphics',
            '723' => 'Silver+Black+Red',
            '750' => 'Green+Blue+Graphics',
            '778' => 'SILVER+BLACK+BLUE',
            '779' => 'White+Beige+Trade Name',
            '797' => 'Milky',
            '798' => 'Graphics+Blue+White',
            '800' => 'Blue+Orange+Black',
            '801' => 'Sunset',
            '900' => 'White+ Red+ Advertising Sticker',
            '992' => 'urban titanium',
            '993' => 'Black+Red+Blue+Silver',
            '999' => 'Others',
            'CRA' => 'Crayon',
            'WBS' => 'White+Black+Silver',
        ];

        foreach ($colors as $code => $text) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $code,
                'text' => $text,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function bankName()
    {
        $banks = [
            ['FI0092', 'OMAN ARAB BANK S.A.O.C.'],
            ['FI0029', 'AL OMANIA FINANCIAL SERVICES'],
            ['FI0001', 'AAFAQ ISLAMIC FINANCE COMPANY'],
            ['FI0065', 'GALADHARI AUTOMOBILES'],
            ['FI0045', 'BANK OF BARODA'],
            ['FI0107', 'SOHAR INTERNATIONAL BANK'],
            ['FI0105', 'SHARJAH ISLAMIC BANK'],
            ['FI0082', 'MUSCAT FINANCE CO'],
            ['FI0016', 'AL HABTOOR ROYAL CAR'],
            ['FI0048', 'BMW ALBATHA FINANCE P.S.C'],
            ['FI0104', 'SAUD BAHWAN AUTOMOTIVE'],
            ['FI0032', 'AL TAYER MOTORS'],
            ['FI0090', 'NOOR BANK'],
            ['FI0084', 'NATIONAL BANK OF DUBAI'],
            ['FI0068', 'GROFIN OMAN'],
            ['FI0079', 'MASRAF AL RAYAN'],
            ['FI0091', 'NUEC CO LLC.'],
            ['FI0033', 'AL WIFAQ FINANCE COMPANY'],
            ['FI0024', 'AL MASRAF'],
            ['FI0117', 'UNITED DIESEL LLC'],
            ['FI0021', 'AL JAZEERA FINANCE'],
            ['FI0076', 'JUMA AL MAJID EST.'],
            ['FI0025', 'AL MAZAYAH AL AULAH GENERAL TRADING LLC'],
            ['FI0121', 'ZUBAIR AUTOMOTIVE'],
            ['FI0102', 'RELIABLE INTERNATINAL AUTOMOBILES LLC'],
            ['FI0077', 'LIBERTY AUTOMOBILES'],
            ['FI0116', 'UNITED ARAB BANK'],
            ['FI0018', 'AL HASHAR'],
            ['FI0063', 'FIRST ABU DHABI BANK'],
            ['FI0096', 'OMAN TRADING ESTABLISHMENT'],
            ['FI0118', 'UNITED FINANCE'],
            ['FI0113', 'TOWELL AUTO CENTRE LLC'],
            ['FI0067', 'GENERAL AUTOMOTIVE'],
            ['FI0097', 'OMANI SERVICE FINANCE'],
            ['FI0030', 'AL ROSTAMANI TRADING CO.'],
            ['FI0110', 'SUHAIL BAHWAN AUTOMOBILES LLC'],
            ['FI0064', 'GALADARI AUTOMOBILES CO LTD'],
            ['FI0066', 'GENAVCO LLC'],
            ['FI0071', 'HSBC'],
            ['FI0074', 'INTERNATIONAL COMMERCIAL HOUSE'],
            ['FI0093', 'OMAN DEVELOPMENT BANK'],
            ['FI0085', 'NATIONAL BANK OF FUJAIRAH'],
            ['FI0101', 'RAS AL KHAIMAH NATIONAL BANK'],
            ['FI0043', 'BANK MUSCAT INTL'],
            ['FI0037', 'ARABIAN AUTOMOBILES CO. LLC'],
            ['FI0072', 'IBN AJYAN BANK'],
            ['FI0103', 'SATA LLC'],
            ['FI0034', 'AL YUSR ISLAMIC BANKING'],
            ['FI0069', 'GULF FINANCE CORPORATION PJSC'],
            ['FI0088', 'NATIONAL BANK OF UMM AL QUWAIN (PJSC)'],
            ['FI0108', 'SOHAR ISLAMIC BANK'],
            ['FI0122', 'ZUBAIR ENTERPRISES DAKHLIYA'],
            ['FI0111', 'SWAIDAN TRADING CO.'],
            ['FI0003', 'ABU DHABI ISLAMIC BANK'],
            ['FI0070', 'HABIB BANK A.G. ZURICH'],
            ['FI0078', 'MASHREQ BANK'],
            ['FI0112', 'TAAGEER FINANCE'],
            ['FI0123', 'ZUBAIR ENTERPRISES NORTHERN'],
            ['FI0017', 'AL HAIL ORIX FINANCE PSC'],
            ['FI0027', 'AL NOOR ISLAMIC BANK'],
            ['FI0083', 'NATIONAL BANK OF ABU DHABI'],
            ['FI0100', 'RAK BANK'],
            ['FI0012', 'AL FUTTAIM FINANCE'],
            ['FI0094', 'OMAN MARKETING AND SERVICES CO.'],
            ['FI0055', 'DHOFAR AUTOMOTIVE'],
            ['FI0036', 'ARAB BANK FOR INVESTMENT & FOREIGN TRADE'],
            ['FI0059', 'EMIRATES BANK'],
            ['FI0073', 'INTERNATIONAL BANK OF QATAR'],
            ['FI0028', 'AL OMANIA FINANCIAL COMPANY'],
            ['FI0080', 'MEETHAQ ISLAMIC BANKING'],
            ['FI0031', 'AL SHIRAWI ENTERPRISES'],
            ['FI0047', 'BLOM BANK FRANCE'],
            ['FI0022', 'AL JUNAIBI INTERNATIONAL AUTO'],
            ['FI0044', 'BANK NIZWA'],
            ['FI0008', 'AL AHLI BANK'],
            ['FI0086', 'NATIONAL BANK OF OMAN LTD'],
            ['FI0119', 'UNITED MOTORS & HEAVY EQUIPMENT CO.L.L.C'],
            ['FI0004', 'ADCB'],
            ['FI0051', 'COMMERCIAL BANK INTERNATIONAL PSC'],
            ['FI0061', 'EMIRATES MONEY'],
            ['FI0106', 'SME DEVELOPMENT FUND'],
            ['FI0050', 'CBI (COMMERCIAL BANK INTERNATIONAL)'],
            ['FI0020', 'AL IZZ ISLMAIC BANK'],
            ['FI0054', 'COMMERCIAL BANK OF QATAR'],
            ['FI0095', 'OMAN ORIX LEASING CO.'],
            ['FI0109', 'STANDARD CHARTERED BANK'],
            ['FI0038', 'BAHRAIN DEVELOPMENT BANK'],
            ['FI0058', 'DUBAI ISLAMIC BANK'],
            ['FI0007', 'AHLI BANK S A O G'],
            ['FI0006', 'AGMC'],
            ['FI0099', 'QATAR ISLAMIC BANK'],
            ['FI0120', 'WATTAYAH MOTORS LLC'],
            ['FI0009', 'AL BANK AL AHLI AL OMANI S.O.A.G.'],
            ['FI0114', 'TRADING ENTERPRISES'],
            ['FI0053', 'COMMERCIAL BANK OF DUBAI'],
            ['FI0035', 'AL ZUBAIR EST.'],
            ['FI0062', 'EMIRATES NBD'],
            ['FI0052', 'COMMERCIAL BANK OF ABU DHABI'],
            ['FI0087', 'NATIONAL BANK OF RAS AL KHAIMAH (PJSC)'],
            ['FI0002', 'ABU DHABI COMMERCIAL BANK'],
            ['FI0040', 'BANK DHOFAR'],
            ['FI0023', 'AL MAJID MOTORS'],
            ['FI0057', 'DUBAI COMMERCIAL BANK'],
            ['FI0098', 'OMASCO'],
            ['FI0005', 'ADCB BANK'],
            ['FI0060', 'EMIRATES ISLAMIC BANK'],
            ['FI0015', 'AL HABTOOR MOTORS CO. LLC'],
            ['FI0014', 'AL GHANDI AUTO'],
            ['FI0075', 'INVEST BANK'],
            ['FI0013', 'AL FUTTAIM MOTORS'],
            ['FI0019', 'AL HILAL ISLAMIC BANK'],
            ['FI0011', 'AL FUTTAIM AUTO AND MACHINERY LLC'],
            ['FI0041', 'BANK MUSCAT'],
            ['FI0115', 'UNION NATIONAL BANK-ABU DHABI'],
            ['FI0042', 'BANK MUSCAT (SAOG)'],
            ['FI0010', 'AL BARAKA ISLAMIC BANK'],
            ['FI0049', 'BNP PARIBAS'],
            ['FI0046', 'BANK OF BEIRUT'],
            ['FI0056', 'DOHA BANK'],
            ['FI0081', 'MOOSA ABDUL RAHMAN HASSAN & CO.LLC'],
            ['FI0026', 'AL MEERATH MOTORS LLC'],
            ['FI0039', 'BANK ALIZ'],
            ['FI0089', 'NATIONAL FINANCE CO.'],
            ['FI0124', 'HSBC BANK MIDDLE EAST LIMITED'],
            ['FI0125', 'EMIRATES NUCLEAR ENERGY CORPORATION'],
            ['FI0126', 'ABU DHABI POLYMERS COMPANY LTD'],
        ];

        foreach ($banks as $bank) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::BANK_NAME,
                'code' => $bank[0],
                'text' => $bank[1],
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function extraVehicleColors()
    {
         $colors = [
            '3' => 'Yellow',
            '5' => 'Purple',
            '7' => 'Grey',
            '10' => 'Beige',
            '12' => 'Orange',
            '14' => 'Gold',
            '15' => 'Pink',
            '17' => 'Violet',
            '22' => 'Yellow+Silver',
            '25' => 'Beige+Grey',
            '26' => 'Beige+Maroon',
            '30' => 'Black+White',
            '34' => 'Grey+Lilac',
            '36' => 'Grey+Gold',
            '41' => 'Black+Silver',
            '44' => 'Blue+Grey',
            '47' => 'Blue+Light Blue',
            '48' => 'Blue+Silver',
            '53' => 'Burgundy',
            '57' => 'Charcoal',
            '58' => 'Cream',
            '62' => 'Dark Green',
            '64' => 'Dark Maroon',
            '68' => 'Green+Brown',
            '78' => 'Maroon+Grey',
            '81' => 'Maroon+Silver',
            '89' => 'Pearl White',
            '90' => 'Platinum',
            '93' => 'Red+Beige',
            '97' => 'Red+White+Blue',
            '101' => 'Silver+Orange',
            '106' => 'White+Green',
            '107' => 'White+Green+Silver',
            '109' => 'White+Red+Orange',
            '111' => 'Yellow+Orange',
            '118' => 'Light Blue',
            '120' => 'White+Green+Blue',
            '125' => 'Silver+Dark Blue',
            '126' => 'White+Purple',
            '137' => 'Green+Orange+Grey',
            '139' => 'Silver+Orange+Grey',
            '151' => 'Silver(R)',
            '154' => 'Sand',
            '155' => 'Yellowishsilver',
            '160' => 'Yellow+Green+Graphics',
            '163' => 'White+Yellow+Blue',
            '166' => 'White+Red+Blue+Graphics',
            '167' => 'Green+White',
            '170' => 'Red+Green',
            '171' => 'Grey+Red',
            '176' => 'Maroon+Silver+Graphics',
            '183' => 'Orange+Yellow+Grey',
            '189' => 'Silver+White',
            '195' => 'Golden',
            '197' => 'Shining Ring Silver',
            '202' => 'Raspberry',
            '205' => 'Blue+Dark Blue',
            '207' => 'Black+Green',
            '217' => 'Grey+Blue',
            '224' => 'White+Blue+Red',
            '225' => 'Red+Cream',
            '226' => 'Maroon+Black+Graphics',
            '234' => 'Yellow+Black',
            '235' => 'Light Green+Black',
            '238' => 'Yellow+Red',
            '239' => 'Yellow+White',
            '244' => 'White+Beige+Blue',
            '246' => 'Red+Blue+White',
            '252' => 'Orange+Red',
            '259' => 'White+Orange+Green',
            '261' => 'Silver+Violet',
            '264' => 'White+Rose',
            '266' => 'Ivory White',
            '268' => 'Gold+Beige',
            '274' => 'White+Red+Green',
            '278' => 'Red+Graphics+White',
            '281' => 'Bluish Silver',
            '285' => 'White+Green+Yellow',
            '288' => 'White+Black+Graphics',
            '291' => 'Red+Black+Graphics',
            '293' => 'Grey+Black+Graphics',
            '294' => 'Red+Black+White',
            '298' => 'Silver+Red+Graphics',
            '301' => 'Yellow+Graphics+Maroon',
            '303' => 'Orange+Grey+Blue',
            '307' => 'White+Red+Blue+Advertising',
            '309' => 'Green+Yellow+Grey',
            '312' => 'Greyish Beige',
            '316' => 'Silver+Advertising Sticker',
            '318' => 'White+Graphics+Orange',
            '322' => 'Yellow+Orange+White',
            '329' => 'Orange+Grey+White',
            '359' => 'Red+Black+White+Graphics',
            '361' => 'White+Beige+Graphics',
            '387' => 'Blue+Graphics+White',
            '389' => 'Grey+Green+Yellow',
            '404' => 'White+Yellow+Blue+Graphics',
            '405' => 'White+Black+Red',
            '406' => 'Yellow+Brown+Graphics',
            '415' => 'Orange+Lead',
            '416' => 'Yellow+Red+Brown',
            '417' => 'Yellow+Silver+Black',
            '419' => 'Blackberry pearl',
            '420' => 'Orange+Grey+Graphics',
            '421' => 'Beige+White+Graphics',
            '423' => 'Grey+Orange+Advertising',
            '425' => 'White+Brown+Graphics',
            '427' => 'Red+Green+Graphics',
            '431' => 'Yellow+Black+Graphics',
            '437' => 'White+Gold+Graphics',
            '439' => 'Yellow+Red+Black',
            '450' => 'Yellow+Brown',
            '454' => 'Silver+Green',
            '463' => 'Black+Graphics',
            '466' => 'Blue+Grey+Graphics',
            '469' => 'Grey+Maroon',
            '470' => 'Purple+Yellow+Graphics',
            '473' => 'Orange+Green+Black',
            '488' => 'Greyish Blue',
            '490' => 'White+Orange+Black',
            '494' => 'Green+Yellow+Graphics',
            '503' => 'Pearl White+Trade Name',
            '508' => 'Blue+Trade name',
            '512' => 'Orange+Black+Graphics',
            '513' => 'White + Red+ Grey',
            '514' => 'ALLOY',
            '520' => 'White+Black+Grey',
            '528' => 'CINNAMON',
            '529' => 'COOPER',
            '534' => 'GREY+BLUE',
            '536' => 'GREY+BLACK',
            '541' => 'GREEN+SILVER',
            '544' => 'MAROON+WHITE',
            '555' => 'RINGSILVER',
            '561' => 'TITANIUM',
            '562' => 'TITANIUM2',
            '563' => 'TITSYLVER',
            '564' => 'WHITE+BLACK+BROWN',
            '572' => 'BEIGE+PURPLE',
            '578' => 'Blue+Orange+Red+Advt. Sticker',
            '592' => 'Granite Crystal Metallic',
            '600' => 'White+Graphics+Orange',
            '602' => 'Gold+Graphics',
            '611' => 'Silver+Trade Name',
            '666' => 'White+Blue+Trade Name',
            '667' => 'PINK+BLACK+GRAPHICS',
            '696' => 'Blue+Graphics+Yellow',
            '697' => 'Graphics+Blue',
            '698' => 'Yellow+Trade name',
            '699' => 'White+Red+Trade name',
            '700' => 'Red+Grey+Orange',
            '701' => 'Blue+Pink+Graphics',
            '777' => 'Red+Trade Name',
            '786' => 'Mercury',
            '787' => 'Red+Silver+Graphics',
            '861' => 'Silver+Red+Black',
            '901' => 'GREY+SILVER+RED',
            '990' => 'Violet+Black',
            '994' => 'YELLOW PEARL',
            '999' => 'Others',
            'BGY' => 'Black+Grey+Yellow',
            'BBO' => 'Blue+Black+Orange+Silver',
            'BRY' => 'Black+Red+Yellow',
            'BSR' => 'Black+Silver+Red',
            'COB' => 'Copper+Black',
            'CRA' => 'Crayon',
            'CSM' => 'Cosmos Silver Metallic',
            'FBM' => 'Fathom Blue Metallic',
            'GBO' => 'Grey+Black+Orange',
            'GBS' => 'GREY+BLACK+SILVER',
            'GBW' => 'Green+Grey+Black+White+Silver',
            'GRM' => 'Green Metallic',
            'IBM' => 'Infitie Black Metallic',
            'KKS' => 'Kaikoura Stone',
            'MSM' => 'Midnight Silver Metallic',
            'MUS' => 'Mustard',
            'OBD' => 'Orange+Black+Red',
            'OBS' => 'Orange+Black+Silver',
            'OGR' => 'Olive Grey',
            'QGM' => 'Quantum Grey Metallic',
            'RCM' => 'Rocky Mountain',
            'SWM' => 'Stellar White Metallic',
            'TBM' => 'TOURMALINE BLUE METALLIC',
            'WBG' => 'White+Black+Blue+Grey',
            'WBO' => 'White+Black+Gold',
            'WBS' => 'White+Black+Silver',
            'WGS' => 'WHITE+BLACK+GREY+SILVER',
            'ZRM' => 'Zenith Red Metallic',
        ];

        foreach ($colors as $code => $text) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $code,
                'text' => $text,
                'insurance_provider_id' => $this->insuranceProviderId,
            ], [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

}
