<?php

namespace Database\Seeders;

use App\Enums\DocumentTypeCode;
use App\Enums\QuoteTypeId;
use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $quoteDocuments = [
            // Quote category documents
            [
                'code' => 'CCL',
                'text' => 'Company Letter',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.docx,.jpeg,.jpg,.png',
                'max_files' => 20,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 10,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'PPR',
                'text' => 'Payment Proforma Request',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 14,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'AUDIT',
                'text' => 'Audit Record',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.txt,.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 22,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'FTC_CAR',
                'text' => 'Final terms and conditions',
                'description' => 'sample description',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 0,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CDPDR',
                'text' => 'Discount Proof',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.png,.pdf,.jpeg,.jpg',
                'max_files' => QuoteTypeId::CompanyCar,
                'max_size' => 30,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 3,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'EID_CAR',
                'text' => 'Emirates ID (both sides)',
                'description' => 'Please share a copy of your valid Emirates ID with us. Awaiting receipt of your first or renewed ID? Please share a copy of your Emirates ID application form to enable us to proceed.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.docx,.doc,.jpeg,.jpg,.png,.webp',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TAD',
                'text' => 'Passing Certificate',
                'description' => 'You may be required to submit additional documents to support the issuance of your policy. Any questions or concerns? Don\'t hesitate to contact your insurance advisor who\'ll be happy to help.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.docx,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => QuoteTypeId::CompanyCar,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'PP_CAR',
                'text' => 'Passport',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'VISA_CAR',
                'text' => 'Visa',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CTL',
                'text' => 'Trade License',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.xlsx,.pdf,.jpeg,.jpg,.docx,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'DL_CAR',
                'text' => 'Driver\'s license (both sides)',
                'description' => 'Please share a copy of your valid driving license with us. Don\'t have a valid one? Please contact your personal shopper for advice on how to proceed.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.docx,.doc,.jpeg,.jpg,.png,.webp',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'BAL',
                'text' => 'Broker Appointment letter',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 11,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPD',
                'text' => 'Payment Proof',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.png,.pdf,.jpeg,.jpg',
                'max_files' => QuoteTypeId::CompanyCar,
                'max_size' => 30,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_MULKIY',
                'text' => 'Registration card (Mulkiya)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.docx,.doc,.jpeg,.jpg,.png,.webp',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CEC',
                'text' => 'Establishment Card',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CKYCD',
                'text' => 'KYC (Know-Your-Customer) Documents',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 12,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'Others_Car',
                'text' => 'Others',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CVAT',
                'text' => 'VAT Certificate or Undertaking letter for non-VAT',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 9,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_CDP',
                'text' => 'Current Dated Photos',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 8,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'MAA_Car',
                'text' => 'Memorandum of association or Articles of Association',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],

            // Issuing documents
            [
                'code' => 'CTI',
                'text' => 'Tax Invoice',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'SCRDOC',
                'text' => 'Risk Score Document',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TI',
                'text' => 'Tax Invoice',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CTIRBB',
                'text' => 'Tax Invoice Raised By Buyer',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 14,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPC',
                'text' => 'Policy Certificate',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 12,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 1,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TAEA',
                'text' => 'Additional Email Attachments',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 20,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 16,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPS',
                'text' => 'Policy Schedule',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 11,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 1,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPDR',
                'text' => 'Receipt',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_ECARD',
                'text' => 'E-card',
                'description' => 'E-card',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 0,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_GL',
                'text' => 'Garage List',
                'description' => 'Garage List',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 0,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'HOME_SAL',
                'text' => 'Home SAL Declaration',
                'is_active' => 1,
                'quote_type_id' => 2,
                'folder_path' => 'home_sal',
                'accepted_files' => '.pdf',
                'max_files' => 5,
                'max_size' => 5,
                'is_required' => 0,
                'category' => DocumentTypeCode::QUOTE,
            ],
            [
                'code' => DocumentTypeCode::Illustration_Document,
                'text' => 'Illustration Document',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'life',
                'accepted_files' => '.pdf,.docx',
                'max_files' => 15,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => DocumentTypeCode::BOR_SIGN,
                'text' => 'Bor Signature',
                'quote_type_id' => null,
                'is_active' => 1,
                'folder_path' => 'bor',
                'accepted_files' => '.pdf,.png,.jpeg,.jpg',
                'max_files' => 5,
            ],
        ];

        foreach ($quoteDocuments as $document) {
            DocumentType::firstOrCreate(
                ['code' => $document['code'], 'quote_type_id' => $document['quote_type_id']],
                $document
            );
        }

        $this->createClaimDocumentTypes(); // Add this line
    }

    private function createClaimDocumentTypes(): void
    {
        $claimDocuments = [
            // Car claim documents
            [
                'code' => 'CLM_CAR_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Car,
                'folder_path' => 'claims/car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CAR_PR',
                'text' => 'Police Report',
                'description' => 'Upload a copy of the official police report for this incident.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Car,
                'folder_path' => 'claims/car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CAR_DL',
                'text' => 'Driver\'s License (both sides)',
                'description' => 'Please share the license (both sides) of the driver involved.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Car,
                'folder_path' => 'claims/car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CAR_MUL',
                'text' => 'Mulkiya (both sides)',
                'description' => 'Upload the valid registration card of your vehicle (both sides).',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Car,
                'folder_path' => 'claims/car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CAR_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Car,
                'folder_path' => 'claims/car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Travel claim documents
            [
                'code' => 'CLM_TRV_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Travel,
                'folder_path' => 'claims/travel',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_TRV_EID',
                'text' => 'Emirates ID',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Travel,
                'folder_path' => 'claims/travel',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_TRV_PP',
                'text' => 'Passport (front page & immigration stamps)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Travel,
                'folder_path' => 'claims/travel',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_TRV_ITI',
                'text' => 'Travel itinerary',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Travel,
                'folder_path' => 'claims/travel',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_TRV_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Travel,
                'folder_path' => 'claims/travel',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Home claim documents
            [
                'code' => 'CLM_HOM_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_PD',
                'text' => 'Photo of damages',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_EQD',
                'text' => 'Estimate/Quote of damages',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_TR',
                'text' => 'Technical report for damaged electrical items, gadgets, phones etc.',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_OPR',
                'text' => 'Original purchase receipt of damaged items (case to case basis for total loss claim)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_TD',
                'text' => 'Title deed',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HOM_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Home,
                'folder_path' => 'claims/home',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Pet claim documents
            [
                'code' => 'CLM_PET_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_CI',
                'text' => 'Clinic invoice',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_EID',
                'text' => 'EID of policy holder',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_MR',
                'text' => 'Medical report',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_FCH',
                'text' => 'Pet\'s Full clinical history',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_VC',
                'text' => 'Vaccination card',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_RP',
                'text' => 'Recent photo of Pet',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_VLC',
                'text' => 'Copy of Vet\'s License certificate',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_PET_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Pet,
                'folder_path' => 'claims/pet',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 8,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Bike claim documents
            [
                'code' => 'CLM_BIK_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Bike,
                'folder_path' => 'claims/bike',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BIK_PR',
                'text' => 'Police Report',
                'description' => 'Upload a copy of the official police report for this incident.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Bike,
                'folder_path' => 'claims/bike',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BIK_DL',
                'text' => 'Driver\'s License (both sides)',
                'description' => 'Please share the license (both sides) of the driver involved.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Bike,
                'folder_path' => 'claims/bike',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BIK_MUL',
                'text' => 'Mulkiya (both sides)',
                'description' => 'Upload the valid registration card of your vehicle (both sides).',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Bike,
                'folder_path' => 'claims/bike',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BIK_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Bike,
                'folder_path' => 'claims/bike',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Cycle claim documents
            [
                'code' => 'CLM_CYC_CF',
                'text' => 'Duly filled, signed and stamped Pedal Cycle Claim Form',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_DC',
                'text' => 'Details of the cycle',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_PI',
                'text' => 'Purchase Invoice of cycle',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_QE',
                'text' => 'Quotation / Estimates for repair (if repairable)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_PD',
                'text' => 'Photos of damage',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_ARD',
                'text' => 'Any other relevant documents pertaining to the loss',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_CYC_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Cycle,
                'folder_path' => 'claims/cycle',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Jetski claim documents
            [
                'code' => 'CLM_JET_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_JET_PR',
                'text' => 'Police Report / Coast guard report',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_JET_RE',
                'text' => 'Repair estimate',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_JET_PD',
                'text' => 'Photos of damage',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_JET_RC',
                'text' => 'Registration copy of the Yacht',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_JET_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Jetski,
                'folder_path' => 'claims/jetski',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Business insurance claim documents
            [
                'code' => 'CLM_BUS_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Business,
                'folder_path' => 'claims/business',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BUS_TL',
                'text' => 'Trade License',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Business,
                'folder_path' => 'claims/business',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BUS_IR',
                'text' => 'Incident report',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Business,
                'folder_path' => 'claims/business',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_BUS_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Business,
                'folder_path' => 'claims/business',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Yacht claim documents
            [
                'code' => 'CLM_YAC_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_PR',
                'text' => 'Police Report / Coast guard report',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_RE',
                'text' => 'Repair estimate',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_PD',
                'text' => 'Photos of damage',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_RC',
                'text' => 'Registration copy of the Yacht',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_SL',
                'text' => 'Skipper\'s license',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_YAC_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Yacht,
                'folder_path' => 'claims/yacht',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Health claim documents
            [
                'code' => 'CLM_HLT_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_MTR',
                'text' => 'Medical test report(s)',
                'description' => 'Include lab reports, imaging results, or other diagnostic tests that support the medical condition being treated.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_IPI',
                'text' => 'Itemised paid invoices & receipts',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_DR',
                'text' => 'Doctor\'s report(s)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_PP',
                'text' => 'Pharmacy prescription(s)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_DS',
                'text' => 'Discharge summary (for inpatient)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_HLT_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Health,
                'folder_path' => 'claims/health',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Life insurance claim documents
            [
                'code' => 'CLM_LIF_POD',
                'text' => 'Proof of diagnosis (Medical reports)',
                'description' => 'Include all lab results, blood tests, MRI/CT scans, or other diagnostic investigations.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_DC',
                'text' => 'Death certificate (if applicable)',
                'description' => 'Death certificate issued by the relevant authorities.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_CF',
                'text' => 'Claim form',
                'description' => 'Ensure that you have the form that\'s completed with details of symptoms, diagnosis, treatment, and your address. You will be able to download and fill out this form in the next steps.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_OD',
                'text' => 'Other documents',
                'description' => 'Please provide any other relevant documents and pictures of the incident, if available.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_LI_ID',
                'text' => 'Life Insured - ID copy',
                'description' => 'Provide policy holder\'s passport or identification document',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_BEN_ID',
                'text' => 'Beneficiary ID copy',
                'description' => 'Provide beneficiary\'s passport or identification document',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_DOC_CD',
                'text' => 'Doctors contact details',
                'description' => 'Provide the doctor\'s hospital ID and contact information.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_BEN_POA',
                'text' => 'Beneficiary proof of address',
                'description' => 'Include beneficiary\'s PO Box and UAE residence address.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 8,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_LI_BANK',
                'text' => 'Life Insured\'s Bank account details',
                'description' => 'Provide the account information for claim payment',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 9,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CLM_LIF_BEN_BANK',
                'text' => 'Beneficiary bank account details',
                'description' => 'Provide beneficiary\'s account information for claim payment',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'claims/life',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 10,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            // Savings claim documents
            [
                'code' => 'CLM_SAV_CF',
                'text' => 'Claim form',
                'description' => 'Upload your signed and completed claim form.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Savings,
                'folder_path' => 'claims/savings',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::CLAIM,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
        ];

        foreach ($claimDocuments as $document) {
            DocumentType::firstOrCreate(
                ['code' => $document['code'], 'quote_type_id' => $document['quote_type_id']],
                $document
            );
        }
    }
}
