<?php

namespace Database\Seeders;

use App\Enums\DocumentTypeCode;
use App\Enums\QuoteTypeId;
use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $quoteDocuments = [
            // Quote category documents
            [
                'code' => 'CCL',
                'text' => 'Company Letter',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.docx,.jpeg,.jpg,.png',
                'max_files' => 20,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 10,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'PPR',
                'text' => 'Payment Proforma Request',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 14,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'AUDIT',
                'text' => 'Audit Record',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.txt,.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 22,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'FTC_CAR',
                'text' => 'Final terms and conditions',
                'description' => 'sample description',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 0,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CDPDR',
                'text' => 'Discount Proof',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.png,.pdf,.jpeg,.jpg',
                'max_files' => QuoteTypeId::CompanyCar,
                'max_size' => 30,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 3,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'EID_CAR',
                'text' => 'Emirates ID (both sides)',
                'description' => 'Please share a copy of your valid Emirates ID with us. Awaiting receipt of your first or renewed ID? Please share a copy of your Emirates ID application form to enable us to proceed.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 3,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TAD',
                'text' => 'Passing Certificate',
                'description' => 'You may be required to submit additional documents to support the issuance of your policy. Any questions or concerns? Don\'t hesitate to contact your insurance advisor who\'ll be happy to help.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.docx,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => QuoteTypeId::CompanyCar,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'PP_CAR',
                'text' => 'Passport',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'VISA_CAR',
                'text' => 'Visa',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 2,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CTL',
                'text' => 'Trade License',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.xlsx,.pdf,.jpeg,.jpg,.docx,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 6,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'DL_CAR',
                'text' => 'Driver\'s license (both sides)',
                'description' => 'Please share a copy of your valid driving license with us. Don\'t have a valid one? Please contact your personal shopper for advice on how to proceed.',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'BAL',
                'text' => 'Broker Appointment letter',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 11,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPD',
                'text' => 'Payment Proof',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.png,.pdf,.jpeg,.jpg',
                'max_files' => QuoteTypeId::CompanyCar,
                'max_size' => 30,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_MULKIY',
                'text' => 'Registration card (Mulkiya)',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 5,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CEC',
                'text' => 'Establishment Card',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 7,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CKYCD',
                'text' => 'KYC (Know-Your-Customer) Documents',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 0,
                'sort_order' => 12,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'Others_Car',
                'text' => 'Others',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CVAT',
                'text' => 'VAT Certificate or Undertaking letter for non-VAT',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 9,
                'receive_from_customer' => 1,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_CDP',
                'text' => 'Current Dated Photos',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 8,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'MAA_Car',
                'text' => 'Memorandum of association or Articles of Association',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => null,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],

            // Issuing documents
            [
                'code' => 'CTI',
                'text' => 'Tax Invoice',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'SCRDOC',
                'text' => 'Risk Score Document',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TI',
                'text' => 'Tax Invoice',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 13,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CTIRBB',
                'text' => 'Tax Invoice Raised By Buyer',
                'description' => null,
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 14,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPC',
                'text' => 'Policy Certificate',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 12,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 1,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'TAEA',
                'text' => 'Additional Email Attachments',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 20,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 16,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPS',
                'text' => 'Policy Schedule',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 1,
                'send_to_customer' => 1,
                'sort_order' => 11,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 1,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CPDR',
                'text' => 'Receipt',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 4,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_ECARD',
                'text' => 'E-card',
                'description' => 'E-card',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 10,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 0,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'CAR_GL',
                'text' => 'Garage List',
                'description' => 'Garage List',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::CompanyCar,
                'folder_path' => 'car',
                'accepted_files' => '.pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png',
                'max_files' => 5,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 1,
                'sort_order' => 0,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::ISSUING_DOCUMENTS,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => 'HOME_SAL',
                'text' => 'Home SAL Declaration',
                'is_active' => 1,
                'quote_type_id' => 2,
                'folder_path' => 'home_sal',
                'accepted_files' => '.pdf',
                'max_files' => 5,
                'max_size' => 5,
                'is_required' => 0,
                'category' => DocumentTypeCode::QUOTE,
            ],
            [
                'code' => DocumentTypeCode::Illustration_Document,
                'text' => 'Illustration Document',
                'description' => '',
                'is_active' => 1,
                'quote_type_id' => QuoteTypeId::Life,
                'folder_path' => 'life',
                'accepted_files' => '.pdf,.docx',
                'max_files' => 15,
                'max_size' => 25,
                'is_required' => 0,
                'send_to_customer' => 0,
                'sort_order' => 1,
                'receive_from_customer' => 0,
                'category' => DocumentTypeCode::QUOTE,
                'is_required_for_send_policy' => 0,
                'business_type_of_insurance_id' => null,
                'business_type_of_customer' => null,
            ],
            [
                'code' => DocumentTypeCode::BOR_SIGN,
                'text' => 'Bor Signature',
                'quote_type_id' => null,
                'is_active' => 1,
                'folder_path' => 'bor',
                'accepted_files' => '.pdf,.png,.jpeg,.jpg',
                'max_files' => 5,
            ]
        ];

        foreach ($quoteDocuments as $document) {
            DocumentType::firstOrCreate(
                ['code' => $document['code'], 'quote_type_id' => $document['quote_type_id']],
                $document
            );
        }
    }
}
