<?php

namespace Database\Seeders;

use App\Enums\InsuranceProvidersEnum;
use App\Enums\LookupsEnum;
use App\Enums\QuoteTypeId;
use App\Models\InsuranceProvider;
use App\Models\Lookup;
use Illuminate\Database\Seeder;

class VehicleColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->tokioMarineVehicleColor();
        $this->qatarVehicleColor();
    }

    private function tokioMarineVehicleColor()
    {
        $insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::TM)->first()->id;

        $vehicleColorList = [
            [127, 'WHITE/GREEN/BLUE'],
            [126, 'WHITE/GREEN/YELLOW'],
            [125, 'WHITE / BROWN'],
            [124, 'DARK BROWN'],
            [123, 'GREY/WHITE'],
            [122, 'YELLOW/RED'],
            [121, 'WHITE/GREEN/ORANGE'],
            [1201, 'CUPPER'],
            [120, 'ORANGE/GREY'],
            [12, 'GOLD'],
            [111205, 'BROWNISH GREY'],
            [111, 'SILVER/BROWN'],
            [110, 'RED / GOLDEN'],
            [11, 'BROWN'],
            [109, 'WHITE/YELLOW/BROWN'],
            [108, 'GREY / GREEN / GOLD'],
            [107, 'GREY/BLUE'],
            [106, 'ORANGE/GREEN'],
            [105, 'YELLOW/GREEN'],
            [104, 'RED/GREEN'],
            [103, 'BLUE/YELLOW'],
            [99, 'OTHERS'],
            [98, 'RED/BLACK/YELLOW'],
            [97, 'GREY/PURPLE'],
            [96, 'YELLOW/WHITE/BLUE'],
            [95, 'GREEN/WHITE'],
            [93, 'YELLOW/WHITE'],
            [92, 'BEIGE/RED'],
            [94, 'RED/BLUE'],
            [91, 'BEIGE/SILVER'],
            [90, 'BEIGE / GREY'],
            [9, 'ORANGE'],
            [89, 'RED/BLUE/WHITE'],
            [88, 'BLUE/ ORANGE/YELLOW'],
            [87, 'SAND METALIC'],
            [86, 'WHITE/BLACK/RED'],
            [85, 'WHITE/BLUE'],
            [84, 'DARK BLUE'],
            [8301, 'SILVER/BLACK'],
            [83, 'SILVER/BEIGE'],
            [8201, 'BLACK/YELLOW'],
            [82, 'BLACK/SILVER'],
            [81, 'BLACK / ORANGE'],
            [80, 'RED / WHITE'],
            [8, 'INDIGO'],
            [79, 'PEARL'],
            [78, 'DEEP TURQUISE PEARL'],
            [77, 'BLUE/RED'],
            [76, 'WHITE/BLUE/RED'],
            [75, 'RED/BROWN/WHITE'],
            [74, 'PEARL/WHITE'],
            [73, 'SAND METALIC'],
            [72, 'WHITE/BEIGE'],
            [71, 'BLUE/ ORANGE'],
            [703, 'DARK OLIVE'],
            [702, 'DARK RED'],
            [701, 'YELLOW/GREEN/GREY'],
            [70, 'YELLOW / ORANGE /BLUE'],
            [7, 'VIOLET'],
            [69, 'GREYISH BROWN'],
            [68, 'AUTUMN BLAZE'],
            [67, 'KASHMIR'],
            [66, 'RED / BEIGE'],
            [65, 'RED BROWN'],
            [64, 'OLIVE'],
            [63, 'METALIC'],
            [62, 'GOLDEN'],
            [61, 'GOLDEN / SILVER'],
            [60, 'GREEN / GREY'],
            [6, 'YELLOW'],
            [102, 'YELLOW/BLUE'],
            [101, 'ORANGE/YELLOW'],
            [1000, 'BURGUNDY'],
            [100, 'YELLOW / SILVER'],
            [10, 'GREY'],
            [1, 'WHITE'],
            [58, 'BLACK / BLUE'],
            [57, 'WHITE/SILVER/BLUE'],
            [56, 'RED / SIVER'],
            [55, 'GREEN / GOLDEN'],
            [54, 'BLACK / GRAY'],
            [53, 'MAROON / BEIGE'],
            [52, 'MAROON / BLUE'],
            [511, 'GREEN/YELLOW/GREY'],
            [51, 'RED / WHITE'],
            [500, 'GREEN/ORANGE'],
            [50, 'BLACK / GREEN'],
            [5, 'GREEN'],
            [49, 'WHITE / GREEN'],
            [48, 'RED / GRAY'],
            [47, 'YELLOW / GRAY'],
            [46, 'GREEN / BLUE'],
            [45, 'BLACK / BROWN'],
            [44, 'WHITE / GOLDEN'],
            [430, 'WHITE/RED/GREEN'],
            [43, 'WHITE / RED'],
            [42, 'GREEN / RED'],
            [41, 'YELLOW / BLACK'],
            [400, 'WHITE/PEARL'],
            [40, 'BLACK / RED'],
            [4, 'RED'],
            [39, 'WHITE / YELLOW'],
            [38, 'PINK'],
            [37, 'GREEN / GREY'],
            [36, 'MAROON / GREY'],
            [35, 'WHITE / SILVER'],
            [34, 'GREEN / BEIGE'],
            [33, 'ORANGE / BLACK'],
            [32, 'ORANGE / SILVER'],
            [31, 'GREEN / SILVER'],
            [300, 'GRAY/SILVER'],
            [30, 'GOLDEN / MAROON'],
            [3, 'BLUE'],
            [29, 'BLUE / SILVER'],
            [28, 'RED / SILVER'],
            [27, 'WHITE / GRAY'],
            [26, 'PURPLE'],
            [25, 'BLACK / BEIGE'],
            [24, 'BLUE / WHITE'],
            [23, 'SILVER / MAROON'],
            [22, 'BROWN / BEIGE'],
            [21, 'GREEN / CREAM'],
            [202, 'GREYISH BEIGE'],
            [200, 'GREEN / BROWN'],
            [20, 'WHITE / BLACK'],
            [2, 'BLACK'],
            [19, 'SILVER / GREY'],
            [18, 'BLUE / GRAY'],
            [17, 'WHITE / ORANGE'],
            [16, 'CREAM'],
            [151, 'BLUE / GREEN / YELLOW'],
            [150, 'BROWNISH PURPLE'],
            [15, 'MAROON'],
            [1449101, 'SUPER RED 5-SILVER'],
            [14, 'BEIGE'],
            [133, 'BLUE / BLACK'],
            [132, 'BLUE / GOLD'],
            [131, 'BRONZE'],
            [130, 'BLUE/BROWN'],
            [13, 'SILVER'],
            [129, 'WHITE / MAROON'],
            [128, 'BROWN / GREY'],
        ];

        foreach ($vehicleColorList as $color) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $color[0],
                'text' => $color[1],
                'insurance_provider_id' => $insuranceProviderId,
            ]);
        }
    }

    private function qatarVehicleColor()
    {
        $insuranceProviderId = InsuranceProvider::where('code', InsuranceProvidersEnum::QIC)->first()->id;

        $vehicleColorList = [
            ['01', 'White'],
            ['02', 'Black'],
            ['03', 'Blue'],
            ['04', 'Red'],
            ['05', 'Green'],
            ['06', 'Yellow'],
            ['07', 'Violet'],
            ['08', 'Indigo'],
            ['09', 'Orange'],
            ['10', 'Gray'],
            ['100', 'Silver / Purple'],
            ['101', 'RED/BEIGE/YELLOW'],
            ['102', 'Red / Yellow'],
            ['103', 'Maroon / Black'],
            ['104', 'Gray/ blue/ silver'],
            ['105', 'Garnet'],
            ['106', 'Brown / Gray'],
            ['107', 'Gray / Blue / Yellow '],
            ['108', 'Gray / Yellow'],
            ['109', 'Liquid Platinum'],
            ['11', 'Brown'],
            ['110', 'Black/Red/Yellow'],
            ['111', 'Brown / Gold'],
            ['112', 'Red / Silver / Black'],
            ['113', 'Brownish Grey'],
            ['114', 'Fuji White'],
            ['115', 'Redline 2 Coat Pearl'],
            ['116', 'Dark Cherry'],
            ['117', 'Dark Sapphire'],
            ['118', 'Granite Crystal Meta'],
            ['119', 'Irish Cream'],
            ['12', 'Golden'],
            ['120', 'Orange Gray'],
            ['121', 'White / Beige'],
            ['122', 'Blue / Gold'],
            ['123', 'Golden / Gray'],
            ['124', 'Pink / Grey'],
            ['125', 'Black / Gray / Red'],
            ['126', 'Lead'],
            ['127', 'Yellow / White / Silver'],
            ['128', 'Red / Blue / Black'],
            ['129', 'Blue / black / Silver'],
            ['13', 'Silver'],
            ['130', 'White / Black / Orange'],
            ['131', 'Silver / Black'],
            ['132', 'Golden violet Blue'],
            ['133', 'Silver / Black / Orange'],
            ['134', 'Grey/Black/White/Silver'],
            ['135', 'Red / White / Blue'],
            ['136', 'White / Blue / Green'],
            ['137', 'Camouflage Beige'],
            ['138', 'Grey / Black /  Yellow'],
            ['139', 'Golden / Silver'],
            ['14', 'Beige'],
            ['140', 'Silver / Purple / Black'],
            ['15', 'Maroon'],
            ['16', 'Cream'],
            ['17', 'White / Orange'],
            ['18', 'Blue / Gray'],
            ['19', 'Silver / Grey'],
            ['20', 'White / Black'],
            ['21', 'Green / Cream'],
            ['22', 'Brown / Beige'],
            ['23', 'Silver / Maroon'],
            ['24', 'Blue / White'],
            ['25', 'Black / Beige'],
            ['26', 'Porpel'],
            ['27', 'White / Gray'],
            ['28', 'Red / Silver'],
            ['29', 'Blue / Silver'],
            ['30', 'Golden / Maroon'],
            ['31', 'Green / Silver'],
            ['32', 'Orange / Silver'],
            ['33', 'Orange / Black'],
            ['34', 'Green / Beige'],
            ['35', 'White / Silver'],
            ['36', 'Maroon / Grey'],
            ['37', 'Green / Grey'],
            ['38', 'Pink'],
            ['39', 'White / Yellow'],
            ['40', 'Black / Red'],
            ['41', 'Yellow / Black'],
            ['42', 'Green / Red'],
            ['43', 'White / Red'],
            ['44', 'White / Golden'],
            ['45', 'Black / Brown'],
            ['46', 'Green / Blue'],
            ['47', 'Yellow / Gray'],
            ['48', 'Red / Gray'],
            ['49', 'White / Green'],
            ['50', 'Green / Black'],
            ['51', 'Red / Maroon'],
            ['52', 'Maroon / Blue'],
            ['53', 'Maroon / Beige'],
            ['54', 'Black / Gray'],
            ['55', 'Green / Gray'],
            ['56', 'Red / Siver'],
            ['57', 'White / Silver / Blue'],
            ['58', 'Black / Blue'],
            ['59', 'White/Brown'],
            ['60', 'Purple'],
            ['61', 'Beige/Golden'],
            ['62', 'Black/Silver'],
            ['63', 'Blue/Yellow'],
            ['64', 'Brown / Red'],
            ['65', 'Maroon/Orange'],
            ['66', 'Maroon/White'],
            ['67', 'Red / Golden'],
            ['68', 'Red / Beige'],
            ['69', 'Red / Violet'],
            ['70', 'Silver / Brown'],
            ['71', 'Yellow / Silver'],
            ['72', 'Yellow / Green'],
            ['73', 'White / Gray / Red'],
            ['74', 'White / Blue / Gray'],
            ['75', 'RED / BROWN'],
            ['76', 'BLACK / ORANGE'],
            ['77', 'Pearl White'],
            ['78', 'Bronze'],
            ['79', 'Orange / Red'],
            ['80', 'Orange / Gray'],
            ['81', 'Green / Golden'],
            ['82', 'Blue / Red'],
            ['83', 'Platinum Graphite'],
            ['84', 'Black / Gold'],
            ['85', 'Yellow / Brown'],
            ['86', 'Orange / Gold'],
            ['87', 'Ingot Silver / White'],
            ['88', 'White / Violet'],
            ['89', 'Yellow / Blue / Green'],
            ['90', 'Red / Black'],
            ['91', 'WHITE / PURPLE'],
            ['92', 'Blue / Orange'],
            ['93', 'Silver / Red '],
            ['94', 'Apricot'],
            ['95', 'Brown / Black'],
            ['96', 'Brown / Orange'],
            ['97', 'White / Red / Black'],
            ['98', 'White / Black / Blue'],
            ['99', 'Others'],
        ];

        foreach ($vehicleColorList as $color) {
            Lookup::firstOrCreate([
                'quote_type_id' => QuoteTypeId::Car,
                'key' => LookupsEnum::VEHICLE_COLOR,
                'code' => $color[0],
                'text' => $color[1],
                'insurance_provider_id' => $insuranceProviderId,
            ]);
        }
    }
}
