trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

steps:
- task: DownloadSecureFile@1
  name: env
  displayName: 'Download env file'
  inputs:
    secureFile: '.env.crmstage'
    
- script: cp $(env.secureFilePath) $(System.DefaultWorkingDirectory)/
- script: |
    echo "Artifacts uploaded to $(System.DefaultWorkingDirectory)"

- publish: '$(System.DefaultWorkingDirectory)'
  artifact: myalfredcms
