trigger:
  - none

pool:
  vmImage: 'Ubuntu 20.04'

variables:
  - group: stg
  - name: imageName
    value: '$(imcrm):$(Build.BuildId)'

steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
  ## Build Starting notification
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl --request POST -u $(serviceaccount):$(SERVICE_TOKEN) 'https://deploymentnotification.azurewebsites.net/api/notificationfunction?code=ewX4tkwM_o-mQw4Q55GWF-HfV1HDfPUcP3A3hfLnTFdaAzFu1ynwMQ==' \
        --header 'Content-Type: application/json' \
        --data '{"message": {"text": "Building Project on $(Build.DefinitionName) is Initiated, Please wait..."}}'

  - script: |
      sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg && \
      curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo apt-key add - && \
      echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list && \
      sudo apt-get update && sudo apt-get install doppler
  - script: |
      sed -i "s/imcrmdev/imcrm$(dev)/g" "$(System.DefaultWorkingDirectory)/docker/nginx.conf"
      sed -i "s/development-alfredcrm/$(logenv)-alfredcrm/g" "$(System.DefaultWorkingDirectory)/docker/log_files.yml"
      doppler --token $(IMCRM_TOKEN) run -- docker build --build-arg IMCRM_TOKEN=$(IMCRM_TOKEN) -f Dockerfile_MS -t $(acrName).azurecr.io/$(imageName) .
      if [ $? -ne 0 ]; then
       curl --request POST -u $(serviceaccount):$(SERVICE_TOKEN) 'https://deploymentnotification.azurewebsites.net/api/notificationfunction?code=ewX4tkwM_o-mQw4Q55GWF-HfV1HDfPUcP3A3hfLnTFdaAzFu1ynwMQ==' \
        --header 'Content-Type: application/json' \
        --data '{"message": {"text": "Building Project Failed on $(Build.DefinitionName), Logs in Postman with BuildID $(Build.BuildId)..."}}'
       exit 1
      fi
    displayName: 'docker build'
  - script: docker login -u $(dockerId) -p $(dockerPassword) $(acrName).azurecr.io
    displayName: 'docker login'
  - script: docker push $(acrName).azurecr.io/$(imageName)
    displayName: 'docker push'
  ## Build Completed notification
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl --request POST -u $(serviceaccount):$(SERVICE_TOKEN) 'https://deploymentnotification.azurewebsites.net/api/notificationfunction?code=ewX4tkwM_o-mQw4Q55GWF-HfV1HDfPUcP3A3hfLnTFdaAzFu1ynwMQ==' \
        --header 'Content-Type: application/json' \
        --data '{"message": {"text": "Building Project on $(Build.DefinitionName) is Completed, Deploying now..."}}'

  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: '$(imcrm)'
