FROM php:8.2-fpm


# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    supervisor \
    libpng-dev \
    libgd-dev \
    libjpeg62-turbo-dev \
    libjpeg-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \ 
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && rm -rf /var/cache/apk/*

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

RUN install-php-extensions gd xdebug mysqli pdo_mysql mongodb mbstring zip exif pcntl


# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# install doppler
RUN curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh

# Copy existing application directory contents
COPY . /var/www

# Create and set permissions for log directory
RUN mkdir -p /var/log/supervisor \
    && chown -R www-data:www-data /var/log/supervisor \
    && chmod -R 755 /var/log/supervisor

# Ensure entrypoint script has Unix line endings and proper permissions
# file has Windows-style line endings (CRLF) instead of Unix-style line endings (LF). This can cause issues when running scripts in a Unix-like environment Alternatively, you can use sed to remove the ^M characters:
RUN sed -i 's/\r//' /var/www/docker-local/entrypoint.sh \
    && chmod +x /var/www/docker-local/entrypoint.sh
    
# Copy Supervisor configuration
COPY ./docker-local/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Add user for laravel application
# Switch to a non-root user for better security
RUN groupadd -g 1000 www && useradd -u 1000 -ms /bin/bash -g www www

# Set the correct permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
# Set the script as the entrypoint
ENTRYPOINT ["/var/www/docker-local/entrypoint.sh"]
CMD ["/usr/bin/supervisord"]
