FROM ubuntu:22.04 AS dependencies
RUN apt update && apt upgrade curl wget -y
ARG IMCRM_TOKEN
#RUN (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh
RUN echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list 
RUN curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
RUN apt-get update && apt-get install doppler
RUN doppler configure set token ${IMCRM_TOKEN}

FROM node:22.12.0 AS frontend
WORKDIR /var/www
COPY package*.json yarn.lock /var/www/
RUN yarn install --pure-lockfile

FROM php:8.2-fpm AS build
WORKDIR /app
# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync
RUN install-php-extensions mbstring pdo_mysql zip exif pcntl memcached
RUN pecl install redis \
    && docker-php-ext-enable redis

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential libssl-dev pkg-config \
    libpng-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    libicu-dev \
    zip \
    jpegoptim optipng pngquant gifsicle \
    unzip \
    git \
    curl \
    lua-zlib-dev \
    libmemcached-dev \
    wget \
    gnupg \
    libwebp-dev \
    qpdf

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp
RUN docker-php-ext-install -j$(nproc) gd
RUN php -r 'var_dump(function_exists("imagecreatefromwebp"));'
RUN pecl install mongodb-2.1.0 && docker-php-ext-enable mongodb

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY . /app
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install --optimize-autoloader --no-dev

FROM php:8.2-fpm
COPY --from=dependencies /root/.doppler/.doppler.yaml /root/.doppler/.doppler.yaml
COPY --from=dependencies /usr/bin/doppler /usr/bin/doppler
COPY --from=build /app/vendor/ /var/www/vendor
COPY --from=frontend /var/www/ /var/www
COPY --from=build /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=build /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/
COPY --from=build /usr/bin/ /usr/bin/
COPY --from=build /app /var/www/
#COPY --from=build /usr/local/etc/php/conf.d/newrelic.ini /usr/local/etc/php/conf.d/newrelic.ini
#COPY --from=build /var/log/newrelic/newrelic-daemon.log /var/log/newrelic/newrelic-daemon.log


RUN apt-get update && apt-get install -y \
nginx \
supervisor \
curl \
wget \
libfreetype6 \
libjpeg62-turbo \
libpng16-16 \
libzip-dev \
zlib1g \
libicu-dev \
libmemcached11 \
libwebp-dev \
qpdf

# Set working directory
WORKDIR /var/www

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Add user for laravel application
RUN groupadd -g 1000 www && \
useradd -u 1000 -ms /bin/bash -g www www

# PHP Error Log Files
RUN mkdir /var/log/php && \
touch /var/log/php/errors.log && chmod 777 /var/log/php/errors.log

EXPOSE 80
EXPOSE 443

# add root to www group
RUN chmod -R ugo+w /var/www/storage

# Copy nginx/php/supervisor configs
RUN cp docker/supervisor.conf /etc/supervisord.conf && \
cp docker/blanka.ini /usr/local/etc/php/conf.d/app.ini && \
cp docker/nginx.conf /etc/nginx/sites-enabled/default && \
cp -r docker/*.pem /etc/nginx/conf.d/

RUN chmod +x /var/www/docker/run.sh
RUN usermod -aG root www-data
RUN usermod -aG root www

RUN \
  wget -P /tmp -r -nd --no-parent -A 'newrelic-php5-*-linux.tar.gz' https://download.newrelic.com/php_agent/release/ && \
  cd /tmp/ && tar -zxvf newrelic-php5-*-linux.tar.gz && cd .. && \
  export NR_INSTALL_USE_CP_NOT_LN=1 && \
  export NR_INSTALL_SILENT=1 && \
  /tmp/newrelic-php5-*/newrelic-install install && \
  rm -rf /tmp/newrelic-php5-* /tmp/nrinstall* && \
  sed -i \
      -e 's/"REPLACE_WITH_REAL_KEY"/"${NEW_RELIC_LICENSE_KEY}"/' \
      -e 's/newrelic.appname = "PHP Application"/newrelic.appname = "${NEW_RELIC_APP_NAME}"/' \
      -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
      -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
      /usr/local/etc/php/conf.d/newrelic.ini

ENTRYPOINT ["/var/www/docker/run.sh"]
