FROM php:8.2-fpm


# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libgd-dev \
    libjpeg62-turbo-dev \
    libjpeg-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/


# Install extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN install-php-extensions gd xdebug mysqli pdo_mysql mongodb mbstring zip exif pcntl
# RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install redis \
    && docker-php-ext-enable redis

# install doppler
RUN curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Grant execute permissions to the script
RUN chmod +x /var/www/docker-local/entrypoint.sh

# file has Windows-style line endings (CRLF) instead of Unix-style line endings (LF). This can cause issues when running scripts in a Unix-like environment Alternatively, you can use sed to remove the ^M characters:
RUN sed -i 's/\r//' /var/www/docker-local/entrypoint.sh

# Expose port 9000 and start php-fpm server
EXPOSE 9000
# Set the script as the entrypoint
ENTRYPOINT ["/var/www/docker-local/entrypoint.sh"]
CMD ["php-fpm"]
