version: '3'

services:
  laravel:
    image: ${ACRNAME}.azurecr.io/imcrm${DOCKERENV}:Build.BuildId
    container_name: imcrm${DOCKERENV}
    environment:
      - DOPPLER_TOKEN
      - AXIOM_API_TOKEN=${AXIOM_API_TOKEN}
      - AXIOM_DATASET=${AXIOM_DATASET}
    ports:
      - '${WEB_PORT}:443'
    volumes:
      - /home/azureuser/imcrm/${LOGS}:/var/www/storage/logs
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - otel-collector

  otel-collector:
      image: otel/opentelemetry-collector-contrib
      container_name: otel-collector
      volumes:
        - ./docker/otel-collector-config.yaml:/etc/otel/config.yaml
        - ./storage/logs:/var/www/storage/logs
      environment:
        - AXIOM_API_TOKEN=${AXIOM_API_TOKEN}
        - AXIOM_DATASET=${AXIOM_DATASET}
      command: ["--config=/etc/otel/config.yaml"]
      ports:
        - "4317:4317"
      networks:
        - blanka-app-network


volumes:
  logs:
  stglogs:
  devlogs:
  dev01logs:
  dev02logs:
  uatlogs:
  uat2logs:
  testlogs:
