FROM ubuntu:22.04 as dependencies
RUN apt update && apt upgrade curl wget -y
ARG IMCRM_TOKEN
RUN (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh
RUN doppler configure set token ${IMCRM_TOKEN}

# Install papertrail
RUN wget https://github.com/papertrail/remote_syslog2/releases/download/v0.20/remote_syslog_linux_amd64.tar.gz && \
tar xzf ./remote_syslog*.tar.gz && \
cp remote_syslog/remote_syslog /usr/local/bin

FROM composer:latest as vendor
WORKDIR /app

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync
RUN install-php-extensions mbstring pdo_mysql zip exif pcntl memcached

# Install dependencies
RUN apk update 
RUN apk add --no-cache \
    autoconf \
    build-base \
    openssl-dev \
    pkgconfig \
    libpng-dev \
    libjpeg-turbo-dev \
    jpeg-dev \
    freetype-dev g++ make \
    wget
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) gd
RUN pecl install mongodb && docker-php-ext-enable mongodb
COPY --chown=www:www-data . /app
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install --optimize-autoloader --no-dev

FROM node:21.7.3 as frontend
WORKDIR /var/www
COPY --chown=www:www-data package*.json yarn.lock /var/www/
RUN yarn install --pure-lockfile

FROM php:8.1-fpm
COPY --from=dependencies /root/.doppler/.doppler.yaml /root/.doppler/.doppler.yaml
COPY --from=dependencies remote_syslog/remote_syslog /usr/local/bin/remote_syslog
COPY --from=dependencies /usr/bin/doppler /usr/bin/doppler
COPY --from=vendor /app/vendor/ /var/www/vendor
COPY --from=frontend /var/www/ /var/www

# Set working directory
WORKDIR /var/www

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync
RUN install-php-extensions mbstring pdo_mysql zip exif pcntl memcached
RUN pecl install redis \
    && docker-php-ext-enable redis

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential libssl-dev pkg-config \
    libpng-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    unzip \
    git \
    curl \
    lua-zlib-dev \
    libmemcached-dev \
    nginx \
    wget \
    gnupg \
    supervisor

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) gd
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Add user for laravel application
RUN groupadd -g 1000 www && \
useradd -u 1000 -ms /bin/bash -g www www

# PHP Error Log Files
RUN mkdir /var/log/php && \
touch /var/log/php/errors.log && chmod 777 /var/log/php/errors.log

EXPOSE 80
EXPOSE 443

COPY --chown=www:www-data . /var/www

# add root to www group
RUN chmod -R ugo+w /var/www/storage

# Copy nginx/php/supervisor configs
RUN cp docker/supervisor.conf /etc/supervisord.conf && \
cp docker/blanka.ini /usr/local/etc/php/conf.d/app.ini && \
cp docker/nginx.conf /etc/nginx/sites-enabled/default && \
cp -r docker/*.pem /etc/nginx/conf.d/ && \
cp docker/log_files.yml /etc/

RUN \
  wget -P /tmp -r -nd --no-parent -A 'newrelic-php5-*-linux.tar.gz' https://download.newrelic.com/php_agent/release/ && \
  cd /tmp/ && tar -zxvf newrelic-php5-*-linux.tar.gz && cd .. && \
  export NR_INSTALL_USE_CP_NOT_LN=1 && \
  export NR_INSTALL_SILENT=1 && \
  /tmp/newrelic-php5-*/newrelic-install install && \
  rm -rf /tmp/newrelic-php5-* /tmp/nrinstall* && \
  sed -i \
      -e 's/"REPLACE_WITH_REAL_KEY"/"${NEW_RELIC_LICENSE_KEY}"/' \
      -e 's/newrelic.appname = "PHP Application"/newrelic.appname = "${NEW_RELIC_APP_NAME}"/' \
      -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
      -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
      /usr/local/etc/php/conf.d/newrelic.ini

RUN chmod +x /var/www/docker/run.sh
RUN usermod -aG root www-data
RUN usermod -aG root www

ENTRYPOINT ["/var/www/docker/run.sh"]
