trigger:
  - main

pool:
  vmImage: ubuntu-latest
name: 1.0$(Rev:.r)

variables:
  phpVersion: 7.2

steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
    persistCredentials: true
  - script: |
      git tag main-$(Build.BuildId)
      git tag
      git push --tag

  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: myalfredcrm
