trigger:
- main

pool:
  vmImage: ubuntu-latest
name: 1.0$(Rev:.r)

variables:
  phpVersion: 7.2

steps:
#- task: DownloadSecureFile@1
#  name: env
#  displayName: 'Download env file'
#  inputs:
#    secureFile: '.env.crmprod'
#- script: cp $(env.secureFilePath) $(System.DefaultWorkingDirectory)/

- script: |
    echo "Artifacts uploaded to $(System.DefaultWorkingDirectory)"
- publish: '$(System.DefaultWorkingDirectory)'
  artifact: myalfredcrm
