sonar.projectKey=InsuranceMarket-ae_blanka
sonar.organization=myalfred
sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  storage/**,\
  bootstrap/cache/**,\
  public/storage/**,\
  public/css/**,\
  public/js/**,\
  public/build/**,\
  public/old/**,\
  public/dist/**,\
  public/vendor/**,\
  public/vendors/**,\
  tests/**,\
  **/*.json,\
  **/*.xml,\
  **/*.lock,\
  .env*,\
  artisan,\
  server.php

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=blanka
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
