<?php

namespace App\Services\PolicyIssuanceAutomation\Car;

class LivaInsurancePayloadMapping
{
    public function nationalityList()
    {
        return [
            ['id' => 87, 'text' => 'Afghan'],
            ['id' => 88, 'text' => 'Albanian'],
            ['id' => 86, 'text' => 'Algerian'],
            ['id' => 2, 'text' => 'American'],
            ['id' => 89, 'text' => 'Andorran'],
            ['id' => 90, 'text' => 'Angolan'],
            ['id' => 200, 'text' => 'Antiguan and Barbudan'],
            ['id' => 61, 'text' => 'Argentinian'],
            ['id' => 91, 'text' => 'Armenian'],
            ['id' => 18, 'text' => 'Australian'],
            ['id' => 17, 'text' => 'Austrian'],
            ['id' => 92, 'text' => 'Azerbaijani'],
            ['id' => 201, 'text' => 'Azores'],
            ['id' => 93, 'text' => 'Bahamian'],
            ['id' => 5, 'text' => 'Bahraini'],
            ['id' => 202, 'text' => 'Balearic Islands'],
            ['id' => 62, 'text' => 'Bangladeshi'],
            ['id' => 94, 'text' => 'Barbadian'],
            ['id' => 19, 'text' => 'Belgian'],
            ['id' => 96, 'text' => 'Belizean'],
            ['id' => 95, 'text' => 'Belorussian'],
            ['id' => 97, 'text' => 'Beninese'],
            ['id' => 203, 'text' => 'Bermuda'],
            ['id' => 98, 'text' => 'Bhutanese'],
            ['id' => 99, 'text' => 'Bolivian'],
            ['id' => 100, 'text' => 'Herzegovinian'],
            ['id' => 100, 'text' => 'Bosnian'],
            ['id' => 101, 'text' => 'Botswanan'],
            ['id' => 39, 'text' => 'Brazilian'],
            ['id' => 3, 'text' => 'British'],
            ['id' => 52, 'text' => 'Bruneian'],
            ['id' => 102, 'text' => 'Bulgarian'],
            ['id' => 103, 'text' => 'Burkinese'],
            ['id' => 104, 'text' => 'Burmese'],
            ['id' => 105, 'text' => 'Burundian'],
            ['id' => 107, 'text' => 'Cabo Verdean'],
            ['id' => 63, 'text' => 'Cambodian'],
            ['id' => 106, 'text' => 'Cameroonian'],
            ['id' => 12, 'text' => 'Canadian'],
            ['id' => 204, 'text' => 'Canary Islands'],
            ['id' => 225, 'text' => 'Central African'],
            ['id' => 108, 'text' => 'Chadian'],
            ['id' => 109, 'text' => 'Chilean'],
            ['id' => 27, 'text' => 'Chinese'],
            ['id' => 50, 'text' => 'Colombian'],
            ['id' => 198, 'text' => 'Comorian'],
            ['id' => 242, 'text' => 'Comoros Islands'],
            ['id' => 110, 'text' => 'Congolese'],
            ['id' => 111, 'text' => 'Costa Rican'],
            ['id' => 221, 'text' => "Cote d'Ivoire"],
            ['id' => 112, 'text' => 'Croatian'],
            ['id' => 113, 'text' => 'Cuban'],
            ['id' => 26, 'text' => 'Cypriot'],
            ['id' => 64, 'text' => 'Czech'],
            ['id' => 23, 'text' => 'Danish'],
            ['id' => 114, 'text' => 'Djiboutian'],
            ['id' => 115, 'text' => 'Dominican'],
            ['id' => 132, 'text' => 'Dutch'],
            ['id' => 227, 'text' => 'East Timorese'],
            ['id' => 117, 'text' => 'Ecuadorean'],
            ['id' => 43, 'text' => 'Egyptian'],
            ['id' => 223, 'text' => 'Emarat'],
            ['id' => 4, 'text' => 'Emirati'],
            ['id' => 228, 'text' => 'Equatoguinean'],
            ['id' => 119, 'text' => 'Eritrean'],
            ['id' => 120, 'text' => 'Estonian'],
            ['id' => 121, 'text' => 'Ethiopian'],
            ['id' => 205, 'text' => 'Faroe Islands'],
            ['id' => 122, 'text' => 'Fijian'],
            ['id' => 74, 'text' => 'Filipino'],
            ['id' => 84, 'text' => 'Finnish'],
            ['id' => 14, 'text' => 'French'],
            ['id' => 123, 'text' => 'Gabonese'],
            ['id' => 124, 'text' => 'Gambian'],
            ['id' => 125, 'text' => 'Georgian'],
            ['id' => 10, 'text' => 'German'],
            ['id' => 126, 'text' => 'Ghanaian'],
            ['id' => 206, 'text' => 'Gibraltar'],
            ['id' => 65, 'text' => 'Greek'],
            ['id' => 127, 'text' => 'Grenadian'],
            ['id' => 207, 'text' => 'Guadeloupe'],
            ['id' => 208, 'text' => 'Guam'],
            ['id' => 128, 'text' => 'Guatemalan'],
            ['id' => 220, 'text' => 'Guinea Bissau'],
            ['id' => 129, 'text' => 'Guinean'],
            ['id' => 130, 'text' => 'Guyanese'],
            ['id' => 131, 'text' => 'Haitian'],
            ['id' => 133, 'text' => 'Honduran'],
            ['id' => 51, 'text' => 'Hungarian'],
            ['id' => 134, 'text' => 'Icelandic'],
            ['id' => 13, 'text' => 'Indian'],
            ['id' => 38, 'text' => 'Indonesian'],
            ['id' => 66, 'text' => 'Iranian'],
            ['id' => 67, 'text' => 'Iraqi'],
            ['id' => 68, 'text' => 'Irish'],
            ['id' => 209, 'text' => 'Islas Canaria'],
            ['id' => 135, 'text' => 'Israeli'],
            ['id' => 15, 'text' => 'Italian'],
            ['id' => 241, 'text' => 'Ivory Coast'],
            ['id' => 136, 'text' => 'Jamaican'],
            ['id' => 21, 'text' => 'Japanese'],
            ['id' => 7, 'text' => 'Jordanian'],
            ['id' => 137, 'text' => 'Kazakh'],
            ['id' => 138, 'text' => 'Kenyan'],
            ['id' => 229, 'text' => 'Kiribatian'],
            ['id' => 34, 'text' => 'Korean'],
            ['id' => 230, 'text' => 'Kosovar'],
            ['id' => 6, 'text' => 'Kuwaiti'],
            ['id' => 197, 'text' => 'Kyrgyz'],
            ['id' => 140, 'text' => 'Laotian'],
            ['id' => 141, 'text' => 'Latvian'],
            ['id' => 28, 'text' => 'Lebanese'],
            ['id' => 142, 'text' => 'Liberian'],
            ['id' => 143, 'text' => 'Libyan'],
            ['id' => 144, 'text' => 'Liechtensteinian'],
            ['id' => 145, 'text' => 'Lithuanian'],
            ['id' => 146, 'text' => 'Luxembourgian'],
            ['id' => 147, 'text' => 'Macedonian'],
            ['id' => 148, 'text' => 'Madagascan'],
            ['id' => 210, 'text' => 'Madeira'],
            ['id' => 149, 'text' => 'Malawian'],
            ['id' => 36, 'text' => 'Malaysian'],
            ['id' => 150, 'text' => 'Maldivian'],
            ['id' => 151, 'text' => 'Malian'],
            ['id' => 152, 'text' => 'Maltese'],
            ['id' => 231, 'text' => 'Marshallese'],
            ['id' => 211, 'text' => 'Martinique'],
            ['id' => 153, 'text' => 'Mauritanian'],
            ['id' => 154, 'text' => 'Mauritian'],
            ['id' => 69, 'text' => 'Mexican'],
            ['id' => 232, 'text' => 'Micronesian'],
            ['id' => 155, 'text' => 'Moldovan'],
            ['id' => 156, 'text' => 'Monegasque'],
            ['id' => 157, 'text' => 'Mongolian'],
            ['id' => 158, 'text' => 'Montenegrin'],
            ['id' => 70, 'text' => 'Moroccan'],
            ['id' => 159, 'text' => 'Mozambican'],
            ['id' => 160, 'text' => 'Namibian'],
            ['id' => 233, 'text' => 'Nauruan'],
            ['id' => 71, 'text' => 'Nepalese'],
            ['id' => 25, 'text' => 'New Zealander'],
            ['id' => 161, 'text' => 'Nicaraguan'],
            ['id' => 57, 'text' => 'Nigerian'],
            ['id' => 162, 'text' => 'Nigerien'],
            ['id' => 163, 'text' => 'North Korean'],
            ['id' => 49, 'text' => 'Norwegian'],
            ['id' => 9, 'text' => 'Omani'],
            ['id' => 29, 'text' => 'Pakistani'],
            ['id' => 234, 'text' => 'Palauan'],
            ['id' => 72, 'text' => 'Palestinian'],
            ['id' => 164, 'text' => 'Panamanian'],
            ['id' => 165, 'text' => 'Papua New Guinean'],
            ['id' => 166, 'text' => 'Paraguayan'],
            ['id' => 73, 'text' => 'Peruvian'],
            ['id' => 75, 'text' => 'Polish'],
            ['id' => 46, 'text' => 'Portuguese'],
            ['id' => 212, 'text' => 'Puerto Rico'],
            ['id' => 8, 'text' => 'Qatari'],
            ['id' => 213, 'text' => 'Reunion'],
            ['id' => 167, 'text' => 'Romanian'],
            ['id' => 76, 'text' => 'Russian'],
            ['id' => 168, 'text' => 'Rwandan'],
            ['id' => 214, 'text' => 'Saint Kitts and Nevis'],
            ['id' => 215, 'text' => 'Saint Lucians'],
            ['id' => 216, 'text' => 'Saint Vincent and the Grenadines'],
            ['id' => 118, 'text' => 'Salvadorean'],
            ['id' => 235, 'text' => 'Sammarinese'],
            ['id' => 194, 'text' => 'Samoan'],
            ['id' => 236, 'text' => 'Sao Tome and Principe'],
            ['id' => 77, 'text' => 'Saudi'],
            ['id' => 169, 'text' => 'Senegalese'],
            ['id' => 170, 'text' => 'Serbian'],
            ['id' => 171, 'text' => 'Seychellois'],
            ['id' => 172, 'text' => 'Sierra Leonian'],
            ['id' => 24, 'text' => 'Singaporean'],
            ['id' => 173, 'text' => 'Slovak'],
            ['id' => 174, 'text' => 'Slovenian'],
            ['id' => 175, 'text' => 'Solomon Islands'],
            ['id' => 176, 'text' => 'Somali'],
            ['id' => 35, 'text' => 'South African'],
            ['id' => 237, 'text' => 'South Korea'],
            ['id' => 139, 'text' => 'South Korean'],
            ['id' => 16, 'text' => 'Spanish'],
            ['id' => 40, 'text' => 'Sri Lankan'],
            ['id' => 238, 'text' => 'St.Kitts'],
            ['id' => 239, 'text' => 'St.Vincent'],
            ['id' => 44, 'text' => 'Sudanese'],
            ['id' => 178, 'text' => 'Surinamese'],
            ['id' => 179, 'text' => 'Swazi'],
            ['id' => 22, 'text' => 'Swedish'],
            ['id' => 20, 'text' => 'Swiss'],
            ['id' => 31, 'text' => 'Syrian'],
            ['id' => 226, 'text' => 'TONGAN'],
            ['id' => 217, 'text' => 'Tahiti'],
            ['id' => 33, 'text' => 'Taiwanese'],
            ['id' => 180, 'text' => 'Tajik'],
            ['id' => 181, 'text' => 'Tanzanian'],
            ['id' => 37, 'text' => 'Thai'],
            ['id' => 182, 'text' => 'Togolese'],
            ['id' => 183, 'text' => 'Trinidadian And Toboggan'],
            ['id' => 85, 'text' => 'Tunisian'],
            ['id' => 80, 'text' => 'Turkish'],
            ['id' => 184, 'text' => 'Turkmen'],
            ['id' => 185, 'text' => 'Tuvaluan'],
            ['id' => 186, 'text' => 'Ugandan'],
            ['id' => 187, 'text' => 'Ukrainian'],
            ['id' => 188, 'text' => 'Uruguayan'],
            ['id' => 189, 'text' => 'Uzbek'],
            ['id' => 190, 'text' => 'Vanuatuan'],
            ['id' => 191, 'text' => 'Vatican City'],
            ['id' => 192, 'text' => 'Venezuelan'],
            ['id' => 81, 'text' => 'Vietnamese'],
            ['id' => 218, 'text' => 'Virgin Islands ( British)'],
            ['id' => 219, 'text' => 'Virgin Islands (Usa)'],
            ['id' => 222, 'text' => 'West Indian'],
            ['id' => 240, 'text' => 'Western Samoa'],
            ['id' => 83, 'text' => 'Yemeni'],
            ['id' => 195, 'text' => 'Zairean'],
            ['id' => 196, 'text' => 'Zambian'],
            ['id' => 53, 'text' => 'Zimbabwean'],
        ];
    }

    public function useCode($useCode)
    {
        return match ($useCode) {
            1 => 'Social, Domestic and Pleasure',
            2 => 'Social, Domestic, Pleasure and Commuting',
            3 => 'Social, Domestic, Pleasure, Commuting and Personal Biz Use',
            4 => 'Commercial',
            5 => 'Limited to TP only',
            6 => 'Taxi',
            7 => 'Rent A Car',
            8 => 'Driving School',
            9 => 'Gas/Fuel Tankers',
            10 => 'Water and Sewerage Tankers',
            default => null
        };
    }

    public function vehicleMakeList($make)
    {
        return match ($make) {
            'ACURA' => 302,
            'ALBANY' => 446,
            'ALFA ROMEO' => 303,
            'APRILIA' => 394,
            'ASTON MARTIN' => 305,
            'AUDI' => 131,
            'AUSTIN-HEALEY' => 410,
            'BACKDRAFT' => 457,
            'BAIC' => 458,
            'BESTUNE' => 522,
            'BMW' => 141,
            'BRILLIANCE' => 456,
            'BYD' => 534,
            'BAJAJ' => 346,
            'BAOTIAN' => 453,
            'BENTLEY' => 306,
            'BIG BEAR CHOPPER' => 411,
            'BIG DOG' => 434,
            'BOSS HOSS' => 392,
            'BRAMWITH' => 401,
            'BUELL' => 418,
            'BUGATTI' => 420,
            'BUICK' => 146,
            'C P I' => 425,
            'CHANGAN' => 464,
            'CADILLAC' => 137,
            'CAN AM' => 408,
            'CAPMAN' => 423,
            'CARVER' => 451,
            'CATERHAM' => 398,
            'CFMOTO' => 450,
            'CHERY' => 379,
            'CHEVROLET' => 14,
            'CHRYSLER' => 133,
            'CITROEN' => 142,
            'DEEPAL' => 840,
            'DONGFENG' => 600,
            'DAEWOO' => 130,
            'DAIHATSU' => 147,
            'DAIMLER' => 307,
            'DODGE' => 123,
            'DUCATI' => 301,
            'ENERGICA' => 555,
            'EXEED' => 805,
            'EXILE' => 428,
            'FACTORY FIVE' => 462,
            'FANTIC' => 800,
            'FERRARI' => 308,
            'FIAT' => 309,
            'FORD' => 34,
            'FUQI' => 391,
            'GASGAS' => 610,
            'GENESIS' => 470,
            'GMC' => 135,
            'GTS' => 375,
            'GAC' => 454,
            'GEELY' => 400,
            'GILERA' => 445,
            'GREAT WALL' => 340,
            'HAVAL' => 557,
            'HONGQI' => 488,
            'HUSQVARNA' => 463,
            'HAIMA' => 393,
            'HARLEY DAVIDSON' => 310,
            'HEADBANGER' => 447,
            'HELLBOUND STEEL' => 436,
            'HERO' => 493,
            'HONDA' => 134,
            'HOTROD' => 543,
            'HUMMER' => 337,
            'HYUNDAI' => 36,
            'INDIAN' => 461,
            'INEOS' => 803,
            'INFINITI' => 382,
            'INTERNATIONAL' => 165,
            'ISUZU' => 4,
            'JAC' => 177,
            'JENSEN' => 459,
            'JAGUAR' => 138,
            'JEEP' => 22,
            'JETOUR' => 615,
            'KIA' => 129,
            'KTM' => 381,
            'KAWASAKI' => 380,
            'KOVE' => 748,
            'KRAZYHORSE' => 431,
            'KYMCO' => 412,
            'LI' => 838,
            'LAMBORGHINI' => 383,
            'LANCIA' => 314,
            'LANDROVER' => 136,
            'LEXUS' => 5,
            'LINCOLN' => 316,
            'LML' => 441,
            'LOTUS' => 317,
            'M G B' => 403,
            'M G F' => 414,
            'MG' => 444,
            'MV AUGUSTA' => 426,
            'MAHINDRA' => 331,
            'MASERATI' => 318,
            'MAXUS' => 491,
            'MAZDA' => 119,
            'MC LAREN' => 442,
            'MERCEDES BENZ' => 6,
            'MERCURY' => 390,
            'MINI' => 319,
            'MITSUBISHI' => 121,
            'MORGAN' => 455,
            'MOTO ENDURO' => 448,
            'MOTO GUZZI' => 430,
            'NIO' => 820,
            'NISSAN' => 7,
            'NORTON' => 443,
            'OLDSMOBILE' => 159,
            'OPEL' => 158,
            'P' => 429,
            'POLESTAR' => 553,
            'PEUGEOT' => 28,
            'PGO' => 384,
            'PIAGGIO' => 432,
            'PONTIAC' => 9,
            'PORSCHE' => 320,
            'PROTON' => 321,
            'RAM' => 471,
            'ROX' => 813,
            'RENAULT' => 127,
            'RIDLEY' => 440,
            'ROLLS ROYCE' => 322,
            'ROVER' => 323,
            'ROYAL ENFIELD' => 419,
            'SHARMAX' => 846,
            'SOUEAST' => 821,
            'SAAB' => 33,
            'SATURN' => 437,
            'SEAT' => 25,
            'SHELBY' => 399,
            'SKODA' => 124,
            'SMART' => 324,
            'SPYDER' => 406,
            'SSANG YONG' => 164,
            'SUBARU' => 35,
            'SUZUKI' => 10,
            'TESLA' => 460,
            'TVS' => 421,
            'TAZZARI' => 427,
            'TOYOTA' => 112,
            'TRAVERTSON' => 438,
            'TRIUMPH' => 395,
            'UM' => 422,
            'ULTIMA' => 405,
            'URAL' => 433,
            'V' => 415,
            'V P G' => 452,
            'VESPA' => 424,
            'VICTORY' => 402,
            'VMOTO' => 413,
            'VOLKSWAGEN' => 139,
            'VOLVO' => 113,
            'WATCO' => 449,
            'WIESMANN' => 439,
            'XIAOMI' => 835,
            'XPENG' => 816,
            'YAMAHA' => 339,
            'ZERO' => 801,
            'ZDO NOTUSE ENFIELD' => 354,
            'ZEEKR' => 809,
            'ZENVO' => 409,
            default => null
        };
    }

    /**
     * Map document types to LIVA document type codes
     */
    public function getDocumentType($documentType): string
    {
        return match ($documentType) {
            'CEID' => '16', // Emirates ID (Front side & Back side)
            'DL' => '4', // Driving License (Front side & Back side)
            'CAR_MULKIY' => '5', // Registration card (Mulkiya)
            default => null
        };
    }
}
