receivers:
  filelog:
    include: [ "/var/www/storage/logs/laravel-*.log" ]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^\[(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (?P<env>\w+)\.(?P<level>\w+): (?P<message>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'

processors:
  batch:

exporters:
  otlphttp:
    endpoint: https://api.axiom.co
    headers:
      authorization: Bearer ${AXIOM_API_TOKEN}
      x-axiom-dataset: ${AXIOM_DATASET}
    compression: gzip

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp]
