[supervisord]
nodaemon=true
loglevel = info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[group:laravel-worker]
priority=999
programs=nginx,php-fpm,horizon

[program:nginx]
priority=10
autostart=true
autorestart=true
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true
command=/usr/sbin/nginx -g 'daemon off;'
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:php-fpm]
priority=5
autostart=true
autorestart=true
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
command=/usr/local/sbin/php-fpm -R
stderr_logfile=/var/log/nginx/php-error.log
stdout_logfile=/var/log/nginx/php-access.log

[program:laravel-schedule]
numprocs=1
autostart=true
autorestart=true
redirect_stderr=true
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan schedule:work
stdout_logfile=/var/log/nginx/schedule.log

# [program:laravel-queue]
# numprocs=2
# autostart=true
# autorestart=true
# redirect_stderr=true
# process_name=%(program_name)s_%(process_num)02d
# stdout_logfile=/var/log/nginx/worker.log
# command=php /var/www/artisan queue:work redis --tries=3 --backoff=3 --queue=default,renewals


[program:horizon]
process_name=%(program_name)s
command=php /var/www/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/nginx/horizon.log
stopwaitsecs=3600

# Permission Fixer (runs before starting services)
[program:fix_permissions]
command=sh -c "while true; do chmod -R 777 /var/www/storage /var/www/bootstrap/cache /var/www/storage/framework/cache/; sleep 120; done"
autostart=true
autorestart=true
priority=30
stderr_logfile=/var/log/supervisor/fix_permissions.err.log
stdout_logfile=/var/log/supervisor/fix_permissions.out.log
