[supervisord]
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/www/storage/logs/php-fpm.err.log
stdout_logfile=/var/www/storage/logs/php-fpm.out.log

[program:laravel-horizon]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/horizon.log