[supervisord]
logfile=/var/www/storage/logs/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0770                      ; socket file mode (default 0700)
chown=www:www                   ; (username:group)


[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/www/storage/logs/php-fpm.err.log
stdout_logfile=/var/www/storage/logs/php-fpm.out.log

[program:horizon]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan horizon
autostart=true
autorestart=true
user=www
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/horizon.log
stopwaitsecs=3
startretries=3
stopasgroup=true
killasgroup=true