<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class ApplicationStorageEnums extends Enum
{
    public const ACTIVE = 1;
    public const INACTIVE = 0;
    public const CAR_LEAD_ALLOCATION_JOB_SWITCH = 'CAR_LEAD_ALLOCATION_JOB_SWITCH';
    public const CAR_LEAD_ALLOCATION_START_TIME = 'CAR_LEAD_ALLOCATION_START_TIME';
    public const SATURDAY_CAP_RESET_TIME = 'SATURDAY_CAP_RESET_TIME';
    public const NORMAL_CAP_RESET_TIME = 'NORMAL_CAP_RESET_TIME';
    public const CAR_LEAD_ALLOCATION_MASTER_SWITCH = 'CAR_LEAD_ALLOCATION_MASTER_SWITCH';
    public const SIB_CAR_DRIP_LIST_ID = 'SIB_CAR_DRIP_LIST_ID';
    public const SIB_HEALTH_EBP_LIST_ID = 'SIB_HEALTH_EBP_LIST_ID';
    public const RENEWAL_ALLOCATION_LEAD_EMAIL_CC = 'RENEWAL_ALLOCATION_LEAD_EMAIL_CC';
    public const HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS = 'HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS';
    public const LMS_INTRO_EMAIL_BCC = 'LMS_INTRO_EMAIL_BCC';
    public const TIER_ASSIGNMENT_SWITCH = 'TIER_ASSIGNMENT_SWITCH';
    public const LMS_INTRO_EMAIL_ATTACHMENT_URL = 'LMS_INTRO_EMAIL_ATTACHMENT_URL';
    public const TIER_ASSIGNMENT_PROCESS_START_DATE = 'TIER_ASSIGNMENT_PROCESS_START_DATE';
    public const CAR_LEAD_PICKUP_FIFO = 'CAR_LEAD_PICKUP_FIFO';
    public const CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS = 'CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS';
    public const JOB_FAILED_EMAIL_RECIPIENTS = 'ahsan.ashfaq@insurancemarket.ae,hussain.fakhruddin@insurancemarket.ae,daniyal.shahid@insurancemarket.ae,faisal.abbas@insurancemarket.ae';
    public const CAR_SOLD_STATUS_REJECTION_TEMPLATE = 'CAR_SOLD_STATUS_REJECTION_TEMPLATE';
    public const UNCONTACTABLE_STATUS_REJECTION_TEMPLATE = 'UNCONTACTABLE_STATUS_REJECTION_TEMPLATE';
    public const CAR_SOLD_RESUBMISSIONS_TEMPLATE = 'CAR_SOLD_RESUBMISSIONS_TEMPLATE';
    public const UNCON_RENEWALS_REMINDER_TEMPLATE = 'UNCON_RENEWALS_REMINDER_TEMPLATE';
    public const CAR_SOLD_RESUBMISSIONS_TO = 'CAR_SOLD_RESUBMISSIONS_TO';
    public const CAR_SOLD_RESUBMISSIONS_CC = 'CAR_SOLD_RESUBMISSIONS_CC';
    public const CAR_LOST_REJECTION_EMAIL_CC = 'CAR_LOST_REJECTION_EMAIL_CC';
    public const VAT_VALUE = 'VAT_VALUE';
    public const USER_INACTIVE_THRESHOLD = 'USER_INACTIVE_THRESHOLD';
    public const CAR_LEAD_ALLOCATION_END_TIME = 'CAR_LEAD_ALLOCATION_END_TIME';
    public const QUOTE_ALLOCATION_SWITCH = 'QUOTE_ALLOCATION_SWITCH';
    public const REASSIGNMENT_START_TIME = 'REASSIGNMENT_START_TIME';
    public const REASSIGNMENT_END_TIME = 'REASSIGNMENT_END_TIME';
    public const ENABLE_AUTO_FOLLOWUP = 'ENABLE_AUTO_FOLLOWUP';
    public const APPLY_DUBAI_NOW_EXCLUSION = 'APPLY_DUBAI_NOW_EXCLUSION';
    public const ENABLE_CAMMY_FOLLOWUP = 'ENABLE_CAMMY_FOLLOWUP';
    public const OCB_NEW_BUSINESS_MULTIPLE_PLANS = 'OCB_NEW_BUSINESS_MULTIPLE_PLANS';
    public const OCB_NEW_BUSINESS_ZERO_PLAN = 'OCB_NEW_BUSINESS_ZERO_PLAN';
    public const OCB_NEW_BUSINESS_SINGLE_PLAN = 'OCB_NEW_BUSINESS_SINGLE_PLAN';
    public const DTT_AFTER_TWO_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWO_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWO_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWO_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITH_PLAN';
    public const ENABLE_LEAD_REASSIGNMENT = 'ENABLE_LEAD_REASSIGNMENT';
    public const DUBAI_NOW_CC_GROUP = 'DUBAI_NOW_CC_GROUP';
    public const SAGE_ENABLED = 'SAGE_ENABLED';
    public const DTT_ENABLED = 'DTT_ENABLED';
    public const DTT_ADVISOR = 'DTT_ADVISOR';
    public const DTT_REPLY_TO = 'DTT_REPLY_TO';
    public const ENABLE_PLAN_MODIFY_VALIDATION = 'ENABLE_PLAN_MODIFY_VALIDATION';
    public const EP_MDX_V2_FROM = 'EP_MDX_V2_FROM';
    public const ADVISOR_ONLINE_NOTIFICATION_EMAILS_ENABLE = 'ADVISOR_ONLINE_NOTIFICATION_EMAILS_ENABLE';
    public const EMAIL_CAMPAIGN = 'EMAIL_CAMPAIGN';
    public const INVITATION_EMAIL_TEMPLATE_FOR_CAMPAIGN = 'INVITATION_EMAIL_TEMPLATE_FOR_CAMPAIGN';
    public const CAR_BOOK_POLICY_TEMPLATE = 'CAR_BOOK_POLICY_TEMPLATE';
    public const TRAVEL_BOOK_POLICY_TEMPLATE = 'TRAVEL_BOOK_POLICY_TEMPLATE';
    public const BIKE_BOOK_POLICY_TEMPLATE = 'BIKE_BOOK_POLICY_TEMPLATE';
    public const HEALTH_BOOK_POLICY_TEMPLATE = 'HEALTH_BOOK_POLICY_TEMPLATE';
    public const LIFE_BOOK_POLICY_TEMPLATE = 'LIFE_BOOK_POLICY_TEMPLATE';
    public const HOME_BOOK_POLICY_TEMPLATE = 'HOME_BOOK_POLICY_TEMPLATE';
    public const PET_BOOK_POLICY_TEMPLATE = 'PET_BOOK_POLICY_TEMPLATE';
    public const CYCLE_BOOK_POLICY_TEMPLATE = 'CYCLE_BOOK_POLICY_TEMPLATE';
    public const YACHT_BOOK_POLICY_TEMPLATE = 'YACHT_BOOK_POLICY_TEMPLATE';
    public const GROUP_MEDICAL_BOOK_POLICY_TEMPLATE = 'GROUP_MEDICAL_BOOK_POLICY_TEMPLATE';
    public const CORPLINE_BOOK_POLICY_TEMPLATE = 'CORPLINE_BOOK_POLICY_TEMPLATE';
    public const VAT = 0.05;
    public const QUOTE_SYNC_CLEANUP_ENABLED = 'QUOTE_SYNC_CLEANUP_ENABLED';
    public const QUOTE_SYNC_CLEANUP_DAYS = 'QUOTE_SYNC_CLEANUP_DAYS';
    public const ALFRED_FOLLOWUP_TEMPLATE = 'ALFRED_FOLLOWUP_TEMPLATE';
}
