<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class ApplicationStorageEnums extends Enum
{
    const ACTIVE = 1;
    const INACTIVE = 0;
    const CAR_LEAD_ALLOCATION_JOB_SWITCH = 'CAR_LEAD_ALLOCATION_JOB_SWITCH';
    const CAR_LEAD_ALLOCATION_START_TIME = 'CAR_LEAD_ALLOCATION_START_TIME';
    const SATURDAY_CAP_RESET_TIME = 'SATURDAY_CAP_RESET_TIME';
    const NORMAL_CAP_RESET_TIME = 'NORMAL_CAP_RESET_TIME';
    const CAR_LEAD_ALLOCATION_MASTER_SWITCH = 'CAR_LEAD_ALLOCATION_MASTER_SWITCH';
    const SIB_CAR_DRIP_LIST_ID = 'SIB_CAR_DRIP_LIST_ID';
    const SIB_HEALTH_EBP_LIST_ID = 'SIB_HEALTH_EBP_LIST_ID';
    const RENEWAL_ALLOCATION_LEAD_EMAIL_CC = 'RENEWAL_ALLOCATION_LEAD_EMAIL_CC';
    const HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS = 'HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS';
    const LMS_INTRO_EMAIL_BCC = 'LMS_INTRO_EMAIL_BCC';
    const TIER_ASSIGNMENT_SWITCH = 'TIER_ASSIGNMENT_SWITCH';
    const LMS_INTRO_EMAIL_ATTACHMENT_URL = 'LMS_INTRO_EMAIL_ATTACHMENT_URL';
    const TIER_ASSIGNMENT_PROCESS_START_DATE = 'TIER_ASSIGNMENT_PROCESS_START_DATE';
    const CAR_LEAD_PICKUP_FIFO = 'CAR_LEAD_PICKUP_FIFO';
    const CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS = 'CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS';
    const JOB_FAILED_EMAIL_RECIPIENTS = 'ahsan.ashfaq@insurancemarket.ae,hussain.fakhruddin@insurancemarket.ae,daniyal.shahid@insurancemarket.ae,faisal.abbas@insurancemarket.ae';

    const CAR_SOLD_STATUS_REJECTION_TEMPLATE = 'CAR_SOLD_STATUS_REJECTION_TEMPLATE';
    const UNCONTACTABLE_STATUS_REJECTION_TEMPLATE = 'UNCONTACTABLE_STATUS_REJECTION_TEMPLATE';
}
