name: Build JS and CSS assets

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.x'

      - name: Setup yarn
        run: npm install -g yarn

      - run: yarn && yarn vite build

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: yarn prod
