name: Postmman API Test

on:
  push:
    branches:
      - pause_bridger_API_test

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run ${{ secrets.BRIDGER_COLLECTION }} -e ${{ secrets.ENVIRONMENT_STAGE }}

      - name: Assign PR when failed
        if: failure() && github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # E2E_TESTER_USERNAMES can be separated by "\n" e.g. "manalliaquat\nabdullahinsurance"
          assignees: ${{ secrets.E2E_TESTER_USERNAMES }}
          number: ${{ github.event.number }}
